### PR TITLE
Coerce and cast decimal sum

### LINKED ISSUE #4966: Decimal sum can overflow
### Describe the bug

Now that we finally enabled sum stat for decimals, seems like some workflow end up overflowing.
```
Error: Failed to execute query: Executor Error: Overflow when summing decimal 2147475288 + 1094250
Backtrace:
   0: vortex_array::arrays::decimal::compute::sum::<impl vortex_array::compute::sum::SumKernel for vortex_array::arrays::decimal::vtable::DecimalVTable>::sum::{{closure}}
             at ./vortex-array/src/arrays/decimal/compute/sum.rs:30:36
   1: core::option::Option<T>::ok_or_else
             at /home/runner/.rustup/toolchains/1.89-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:1340:25
   2: vortex_array::arrays::decimal::compute::sum::<impl vortex_array::compute::sum::SumKernel for vortex_array::arrays::decimal::vtable::DecimalVTable>::sum
             at ./vortex-array/src/arrays/decimal/compute/sum.rs:30:22
   3: <vortex_array::compute::sum::SumKernelAdapter<V> as vortex_array::compute::Kernel>::invoke
             at ./vortex-array/src/compute/sum.rs:113:17
   4: vortex_array::compute::sum::sum_impl
             at ./vortex-array/src/compute/sum.rs:146:38
   5: <vortex_array::compute::sum::Sum as vortex_array::compute::ComputeFnVTable>::invoke
             at ./vortex-array/src/compute/sum.rs:60:26
   6: vortex_array::compute::ComputeFn::invoke
             at ./vortex-array/src/compute/mod.rs:143:34
   7: vortex_array::compute::sum::sum
             at ./vortex-array/src/compute/sum.rs:35:10
   8: vortex_array::stats::array::StatsSetRef::compute_stat::{{closure}}
             at ./vortex-array/src/stats/array.rs:149:25
   9: core::bool::<impl bool>::then
             at /home/runner/.rustup/toolchains/1.89-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/bool.rs:62:24
  10: vortex_array::stats::array::StatsSetRef::compute_stat
             at ./vortex-array/src/stats/array.rs:147:22
  11: vortex_array::stats::array::StatsSetRef::compute_all
             at ./vortex-array/src/stats/array.rs:190:35
  12: <vortex_layout::layouts::zoned::writer::ZonedStrategy as vortex_layout::strategy::LayoutStrategy>::write_stream::{{closure}}::{{closure}}::{{closure}}
             at ./vortex-layout/src/layouts/zoned/writer.rs:94:44
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AdamGS**
- Closes https://github.com/vortex-data/vortex/issues/4966

At this point I'm considering adding "Decimal expert" to my CV 😢

### CODE REVIEW

**Review by robert3005 — APPROVED** [review]

**Review by robert3005 — COMMENTED** [review]
I think we want a test as well

File: vortex-array/src/arrays/decimal/compute/sum.rs [hunk 1]
```diff
@@ -51,29 +55,281 @@ impl SumKernel for DecimalVTable {
...
+        let large_neg = -(i64::MAX / 2);
+        let decimal = DecimalArray::new(
+            buffer![large_pos, large_neg, large_pos, 1000i64],
+            DecimalDType::new(19, 3),
+            Validity::AllValid,
+        );
+
+        let result = sum(decimal.as_ref()).unwrap();
+
+        let expected_sum = (large_pos as i128) + (large_neg as i128) + (large_pos as i128) + 1000;
```
Comment (a10y) [inline vortex-array/src/arrays/decimal/compute/sum.rs:236]: this is just large_pos + 1000 right?

File: vortex-array/src/arrays/decimal/compute/sum.rs [hunk 2]
```diff
@@ -51,29 +55,281 @@ impl SumKernel for DecimalVTable {
...
+
+        assert_eq!(result, expected);
+    }
+
+    #[test]
+    fn test_sum_large_i64_values() {
+        // Test with large i64 values that require i128 accumulation
+        let large_val = i64::MAX / 4;
+        let decimal = DecimalArray::new(
+            buffer![large_val, large_val, large_val, large_val],
```
Comment (a10y) [inline vortex-array/src/arrays/decimal/compute/sum.rs]: can you tweak this test to demonstrate that it would overflow the i64 range, but it still returns b/c it coerces up to i128? basically just change one of these to large_val + 1 or something?

**Review by a10y — APPROVED** [review]
FWIW, AFAICT both DuckDB and DataFusion don't attempt to catch overflow on SUM, they just let it wrap

**Comment by robert3005** [comment]
I think because we widen the return type you can let it wrap and if it wraps you would have a type error anyway
