### PR TITLE
fix: Prevent compressor from choosing SequenceArray for dictionary codes

### LINKED ISSUE #3976: Don't compress array with dictionary encoding if codes are a sequence
We are just shifting plain values into code lookups for no added benefit. This is likely caused by the fact that SequenceArray has nbytes of 0

### PR DESCRIPTION
**Pull request by robert3005**
fix #3976

Signed-off-by: Robert Kruszewski <github@robertk.io>

### CODE REVIEW

File: vortex-btrblocks/src/integer.rs [hunk 1]
```diff
@@ -589,7 +589,7 @@ impl Scheme for DictScheme {
         let dict = dictionary_encode(stats)?;
 
         // Cascade the codes child
-        let mut new_excludes = vec![DICT_SCHEME];
+        let mut new_excludes = vec![DICT_SCHEME, SEQUENCE_SCHEME];
```
Comment (AdamGS) [inline vortex-btrblocks/src/integer.rs:593]: maybe add comment here documenting why? feels like its very likely that in a few months we'll randomly revisit it

**Review by AdamGS — APPROVED** [review]
