### PR TITLE
Use Buffer for BitPackedArray

### LINKED ISSUE #850: BitPackedArray should store packed values in Buffer
Currently it's stored in PrimitiveArray, but the semantics are wrong: the PType is the PType for the unpacked array

### PR DESCRIPTION
**Pull request by a10y**
Fixes #850

### CODE REVIEW

File: encodings/fastlanes/src/bitpacking/mod.rs [hunk 1]
```diff
@@ -29,28 +32,30 @@ pub struct BitPackedMetadata {
...
         validity: Validity,
         patches: Option<Array>,
         bit_width: usize,
         length: usize,
         offset: usize,
     ) -> VortexResult<Self> {
-        let dtype = packed.dtype().with_nullability(validity.nullability());
-        if !dtype.is_unsigned_int() {
-            vortex_bail!(MismatchedTypes: "uint", &dtype);
-        }
```
Comment (robert3005) [inline encodings/fastlanes/src/bitpacking/mod.rs:53]: you still want this check, the ptype has to be unsigned

File: encodings/fastlanes/src/bitpacking/compress.rs [hunk 2]
```diff
@@ -22,28 +23,51 @@ pub fn bitpack_encode(array: PrimitiveArray, bit_width: usize) -> VortexResult<B
...
+        let packed_vec: Vec<$P> = bitpack_primitive(parray.maybe_null_slice::<$P>(), bit_width);
+        let (ptr, len, cap) = packed_vec.into_raw_parts();
+        let ptr_u8: *mut u8 = ptr.cast();
+        let len_u8 = len * std::mem::size_of::<$P>();
+        let cap_u8 = cap * std::mem::size_of::<$P>();
+
+        // SAFETY: we are simply reinterpreting the packed_vec as a Vec<u8>.
+        let packed_u8 = unsafe {
+            Vec::from_raw_parts(ptr_u8, len_u8, cap_u8)
+        };
```
Comment (robert3005) [inline encodings/fastlanes/src/bitpacking/compress.rs]: max performance, don't check alignment 👍

**Review by robert3005 — APPROVED** [review]

File: encodings/fastlanes/src/bitpacking/compress.rs [hunk 3]
```diff
@@ -22,28 +23,51 @@ pub fn bitpack_encode(array: PrimitiveArray, bit_width: usize) -> VortexResult<B
...
+
+        Buffer::from(packed_u8)
```
Comment (lwwmanning) [inline encodings/fastlanes/src/bitpacking/compress.rs]: trivial, but consider moving Lines 52-62 might to be inside `bitpack_primitive` (and make that fn return `Buffer`). better to avoid doing complicated logic within a macro block since IDEs generally don't work well in those contexts

File: encodings/fastlanes/src/bitpacking/compress.rs [hunk 4]
```diff
@@ -22,28 +23,51 @@ pub fn bitpack_encode(array: PrimitiveArray, bit_width: usize) -> VortexResult<B
...
+pub fn bitpack(parray: &PrimitiveArray, bit_width: usize) -> VortexResult<Buffer> {
     // We know the min is > 0, so it's safe to re-interpret signed integers as unsigned.
     let parray = parray.reinterpret_cast(parray.ptype().to_unsigned());
     let packed = match_each_unsigned_integer_ptype!(parray.ptype(), |$P| {
-        PrimitiveArray::from(bitpack_primitive(parray.maybe_null_slice::<$P>(), bit_width))
+        let packed_vec: Vec<$P> = bitpack_primitive(parray.maybe_null_slice::<$P>(), bit_width);
+        let (ptr, len, cap) = packed_vec.into_raw_parts();
+        let ptr_u8: *mut u8 = ptr.cast();
+        let len_u8 = len * std::mem::size_of::<$P>();
+        let cap_u8 = cap * std::mem::size_of::<$P>();
```
Comment (AdamGS) [inline encodings/fastlanes/src/bitpacking/compress.rs]: real nit - `len_bytes`/`cap_bytes`? Logically its just bytes and not integers

File: encodings/fastlanes/src/bitpacking/compress.rs [hunk 5]
```diff
@@ -53,6 +77,9 @@ pub fn bitpack_primitive<T: NativePType + BitPacking>(array: &[T], bit_width: us
     let num_chunks = (array.len() + 1023) / 1024;
     let num_full_chunks = array.len() / 1024;
     let packed_len = 128 * bit_width / size_of::<T>();
+    // packed_len says how many values of size T we're going to include.
+    // 1024 * bit_width / 8 == the number of bytes we're going to get.
+    // then we divide by the size of T to get the number of elements.
 
     // Allocate a result byte array.
     let mut output = Vec::with_capacity(num_chunks * packed_len);
```
Comment (lwwmanning) [inline encodings/fastlanes/src/bitpacking/compress.rs]: for alignment: should just allocate this as a Buffer of the correct size (with Arrow), then assemble Vec::from_raw_parts (wrapped in ManuallyDrop), then have this function return the Buffer

Comment (robert3005) [reply encodings/fastlanes/src/bitpacking/compress.rs]: arrow buffers can `into_vec`

File: encodings/fastlanes/src/bitpacking/compute/scalar_at.rs [hunk 6]
```diff
@@ -36,7 +37,8 @@ mod test {
     #[test]
     fn invalid_patches() {
         let packed_array = BitPackedArray::try_new(
-            PrimitiveArray::from(vec![0u32; 32]).into_array(),
+            Buffer::from(vec![0u8; 128]),
```
Comment (a10y) [inline encodings/fastlanes/src/bitpacking/compute/scalar_at.rs:40]: u32 -> u8 == *4

File: vortex-buffer/src/lib.rs [hunk 7]
```diff
@@ -36,6 +39,32 @@ unsafe impl Send for Buffer {}
...
+    /// # Panics
+    /// This method will panic if the vector is empty.
+    #[allow(clippy::as_ptr_cast_mut)]
+    pub fn from_vec<T: Sized + Send + Sync + RefUnwindSafe + 'static>(input: Vec<T>) -> Self {
+        if input.is_empty() {
+            return Self::from_len_zeroed(0);
+        }
+
+        unsafe {
+            ArrowBuffer::from_custom_allocation(
```
Comment (robert3005) [inline vortex-buffer/src/lib.rs]: You don't need this - Buffer::from_vec can take a vec

Comment (robert3005) [reply vortex-buffer/src/lib.rs]: custom allocation is not mutable

Comment (a10y) [reply vortex-buffer/src/lib.rs:57]: but only a Vec<u8>

Comment (a10y) [reply vortex-buffer/src/lib.rs]: i think then we'd need to put a NativePType bound on the T

Comment (lwwmanning) [reply vortex-buffer/src/lib.rs]: only if T is `ArrowNativeType`

Comment (robert3005) [reply vortex-buffer/src/lib.rs]: yeah, you need to put ArrowNativeType bound which is annoying but imho better. Those buffers are immutable which loses out on performance. If we want to get rid of arrow in api we have to have our own buffer type
