### PR TITLE
fix: #4503

### LINKED ISSUE #4503: bug: pco fails to round-trip the size two i32 array: [null, 1].
I expected this to exit successfully; instead, the `decompress()` call fails.
```rust
    let array = PrimitiveArray::from_option_iter([None, Some(1)]);
    let compressed = PcoArray::from_primitive(&array, 3, 0).unwrap();
    assert_eq!(compressed.scalar_at(0), Scalar::null_typed::<i32>());
    assert_eq!(compressed.scalar_at(1), Scalar::from(Some(1)));
    let decompressed = compressed.decompress();
    assert_eq!(decompressed.scalar_at(0), Scalar::null_typed::<i32>());
    assert_eq!(decompressed.scalar_at(1), Scalar::from(Some(1)));
```
```
thread 'test::test_compress_decompress_big' panicked at /Users/danielking/projects/vortex/vortex-buffer/src/buffer.rs:266:13:
range end out of bounds: 2 <= 1
```

### PR DESCRIPTION
**Pull request by danking**
Fixes #4503 

Pco mistakenly used the number of values rather than the number of _valid_ values.

### CODE REVIEW

File: encodings/pco/src/test.rs [hunk 1]
```diff
@@ -42,6 +43,18 @@ fn test_compress_decompress() {
...
+#[test]
+#[should_panic]
+fn test_compress_decompress_big() {
+    let array = PrimitiveArray::from_option_iter([None, Some(1)]);
+    let compressed = PcoArray::from_primitive(&array, 3, 0).unwrap();
+    assert_eq!(compressed.scalar_at(0), Scalar::null_typed::<i32>());
+    assert_eq!(compressed.scalar_at(1), Scalar::from(Some(1)));
+    let decompressed = compressed.decompress();
+    assert_eq!(decompressed.scalar_at(0), Scalar::null_typed::<i32>());
+    assert_eq!(decompressed.scalar_at(1), Scalar::from(Some(1)));
```
Comment (a10y) [inline encodings/pco/src/test.rs:54]: Which one should panic? there are 4 different asserts here

Comment (danking) [reply encodings/pco/src/test.rs:54]: It's actually the decompression that panics. I'll add a message check

Comment (danking) [reply encodings/pco/src/test.rs:54]: Actually I found the fix.

**Review by robert3005 — APPROVED** [review]
