### PR TITLE
fix: Sum from stats has to account for accumulator

### LINKED ISSUE #5434: Fuzzing Crash: array_ops - Sum operation produces incorrect result after Slice on ChunkedArray with mixed validity
### Analysis

**Crash Location**: `fuzz/fuzz_targets/array_ops.rs:93`

**Error Message**:
```
called `Result::unwrap()` on an `Err` value: Scalar mismatch: expected 17307u64, got 26942u64 in step 2
```

**Stack Trace**:
```
   0: __rustc::rust_begin_unwind
             at /rustc/07bdbaedc63094281483c40a88a1a8f2f8ffadc5/library/std/src/panicking.rs:690:5
   1: core::panicking::panic_fmt
             at /rustc/07bdbaedc63094281483c40a88a1a8f2f8ffadc5/library/core/src/panicking.rs:80:14
   2: core::result::unwrap_failed
             at /rustc/07bdbaedc63094281483c40a88a1a8f2f8ffadc5/library/core/src/result.rs:1867:5
   3: unwrap<(), vortex_fuzz::error::VortexFuzzError>
             at /rustc/07bdbaedc63094281483c40a88a1a8f2f8ffadc5/library/core/src/result.rs:1233:23
   4: __libfuzzer_sys_run
             at ./fuzz/fuzz_targets/array_ops.rs:93:70
   5: rust_fuzzer_test_input
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:363:60
   6: {closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:62:9
   7: do_call<libfuzzer_sys::test_input_wrap::{closure_env#0}>
             at /rustc/07bdbaedc63094281483c40a88a1a8f2f8ffadc5/library/std/src/panicking.rs:582:40
```

**Root Cause**: The fuzzer detected incorrect Sum computation after a Slice operation on a ChunkedArray with mixed validity patterns.

The test flow:
1. Starts with a ChunkedArray (U8, Nullable) with 164 elements across 3 chunks:
   - Chunk 0: 79 elements, AllValid validity
   - Chunk 1: 57 elements, Array validity (some nulls, validity bitmap: [240, 255, ...])
   - Chunk 2: 28 elements, AllInvalid validity (all nulls)
2. Applies Sum operation (step 0) → Expected: 26942u64, Got: 26942u64 ✓
3. Applies Slice operation (47..140) → produces 93-element array (step 1) ✓
4. **Applies Sum operation (step 2) → Expected: 17307u64, Got: 26942u64 ✗**

The issue is that after slicing the ChunkedArray from indices 47-140, the Sum operation incorrectly returns the original array's sum (26942) instead of computing the sum for only the sliced range (17307).

This indicates that:
- Either the Slice operation is not correctly updating chunk offsets/ranges for ChunkedArray
- Or the Sum operation is not correctly respecting the slice boundaries when iterating over chunks
- The validity information after slicing may not be properly maintained, causing Sum to include elements it shouldn't

The debug output shows the sliced array has the correct validity pattern (85 valid elements out of 93 according to stats), so the bug likely lies in how Sum traverses chunks after a slice.

<details>
<summary>Debug Output</summary>

```
FuzzArrayAction {
    array: ChunkedArray {
        dtype: Primitive(
            U8,
            Nullable,
        ),
        len: 164,
        chunk_offsets: Buffer<u64> {
            length: 4,
            alignment: Alignment(
                8,
            ),
            as_slice: [0, 79, 136, 164],
        },
        chunks: [
            PrimitiveArray {
                dtype: Primitive(
                    U8,
                    Nullable,
                ),
                buffer: Buffer<u8> {
                    length: 79,
                    alignment: Alignment(
                        1,
                    ),
                    as_slice: [223, 223, 223, 223, 65, 65, 65, 65, 65, 65, 237, 237, 237, 237, 237, 237, ...],
                },
                validity: AllValid,
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
            PrimitiveArray {
                dtype: Primitive(
                    U8,
                    Nullable,
                ),
                buffer: Buffer<u8> {
                    length: 57,
                    alignment: Alignment(
                        1,
                    ),
                    as_slice: [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, ...],
                },
                validity: Array(
                    BoolArray {
                        dtype: Bool(
                            NonNullable,
                        ),
                        buffer: BitBuffer {
                            buffer: Buffer<u8> {
                                length: 8,
                                alignment: Alignment(
                                    1,
                                ),
                                as_slice: [240, 255, 255, 255, 255, 255, 255, 1],
                            },
                            offset: 0,
                            len: 57,
                        },
                        validity: NonNullable,
                        stats_set: ArrayStats {
                            inner: RwLock {
                                data: StatsSet {
                                    values: [],
                                },
                            },
                        },
                    },
                ),
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
            PrimitiveArray {
                dtype: Primitive(
                    U8,
                    Nullable,
                ),
                buffer: Buffer<u8> {
                    length: 28,
                    alignment: Alignment(
                        1,
                    ),
                    as_slice: [255, 159, 159, 159, 159, 159, 159, 159, 157, 211, 211, 211, 211, 211, 71, 71, ...],
                },
                validity: AllInvalid,
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
        ],
        stats_set: ArrayStats {
            inner: RwLock {
                data: StatsSet {
                    values: [],
                },
            },
        },
    },
    actions: [
        (
            Sum,
            Scalar(
                Scalar {
                    dtype: Primitive(
                        U64,
                        Nullable,
                    ),
                    value: ScalarValue(
                        Primitive(
                            U64(
                                26942,
                            ),
                        ),
                    ),
                },
            ),
        ),
        (
            Slice(
                47..140,
            ),
            Array(
                PrimitiveArray {
                    dtype: Primitive(
                        U8,
                        Nullable,
                    ),
                    buffer: Buffer<u8> {
                        length: 93,
                        alignment: Alignment(
                            1,
                        ),
                        as_slice: [211, 211, 211, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, ...],
                    },
                    validity: Array(
                        BoolArray {
                            dtype: Bool(
                                NonNullable,
                            ),
                            buffer: BitBuffer {
                                buffer: Buffer<u8> {
                                    length: 13,
                                    alignment: Alignment(
                                        1,
                                    ),
                                    as_slice: [255, 255, 255, 255, 127, 248, 255, 255, 255, 255, 255, 255, 0],
                                },
                                offset: 7,
                                len: 93,
                            },
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [
                                            (
                                                Sum,
                                                Exact(
                                                    ScalarValue(
                                                        Primitive(
                                                            U64(
                                                                85,
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ),
                                        ],
                                    },
                                },
                            },
                        },
                    ),
                    stats_set: ArrayStats {
                        inner: RwLock {
                            data: StatsSet {
                                values: [
                                    (
                                        Sum,
                                        Exact(
                                            ScalarValue(
                                                Primitive(
                                                    U64(
                                                        17307,
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ],
                            },
                        },
                    },
                },
            ),
        ),
        (
            Sum,
            Scalar(
                Scalar {
                    dtype: Primitive(
                        U64,
                        Nullable,
                    ),
                    value: ScalarValue(
                        Primitive(
                            U64(
                                17307,
                            ),
                        ),
                    ),
                },
            ),
        ),
        (
            Sum,
            Scalar(
                Scalar {
                    dtype: Primitive(
                        U64,
                        Nullable,
                    ),
                    value: ScalarValue(
                        Primitive(
                            U64(
                                17307,
                            ),
                        ),
                    ),
                },
            ),
        ),
    ],
}
```
</details>

### Summary

- **Target**: `array_ops`
- **Crash File**: `crash-3fa138fe87016203a69866a79b6134c082298b5c`
- **Branch**: develop
- **Commit**: bec5098c9d88761d3c8c172de9c5db6b3ba206fa
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/19555639405/artifacts/4635065268

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/19555639405/artifacts/4635065268
   - Or find `operations-fuzzing-crash-artifacts` at: https://github.com/vortex-data/vortex/actions/runs/19555639405
   - Extract the zip file

2. Reproduce locally:
```bash
# The artifact contains array_ops/crash-3fa138fe87016203a69866a79b6134c082298b5c
cargo +nightly fuzz run --sanitizer=none array_ops array_ops/crash-3fa138fe87016203a69866a79b6134c082298b5c
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run --sanitizer=none array_ops array_ops/crash-3fa138fe87016203a69866a79b6134c082298b5c
```

---
*Auto-created by fuzzing workflow with Claude analysis*

### PR DESCRIPTION
**Pull request by robert3005**
fix: #5434 

Signed-off-by: Robert Kruszewski <github@robertk.io>

### CODE REVIEW

File: vortex-array/src/compute/sum.rs [hunk 1]
```diff
@@ -102,15 +103,27 @@ impl ComputeFnVTable for Sum {
 
         // Short-circuit using array statistics.
         if let Some(Precision::Exact(sum)) = array.statistics().get(Stat::Sum) {
-            return Ok(sum.into());
+            let sum_from_stat = sum
+                .as_primitive()
+                .checked_add(&accumulator.as_primitive())
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/sum.rs]: swap the order

File: vortex-array/src/compute/sum.rs [hunk 2]
```diff
@@ -102,15 +103,27 @@ impl ComputeFnVTable for Sum {
...
+        // Update the statistics with the computed sum. Stored statistic shouldn't include the accumulator.
+        if let Some(less_accumulator) = sum_scalar
+            .as_primitive()
+            .checked_sub(&accumulator.as_primitive())
+        {
+            array.statistics().set(
+                Stat::Sum,
+                Precision::Exact(Scalar::from(less_accumulator).value().clone()),
+            );
+        }
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/sum.rs:165]: dont do this for float, require acc == 0 for floats

File: vortex-array/src/compute/sum.rs [hunk 3]
```diff
@@ -102,15 +103,54 @@ impl ComputeFnVTable for Sum {
...
         }
 
         let sum_scalar = sum_impl(array, accumulator, kernels)?;
 
-        // Update the statistics with the computed sum.
-        array
-            .statistics()
-            .set(Stat::Sum, Precision::Exact(sum_scalar.value().clone()));
+        // Update the statistics with the computed sum. Stored statistic shouldn't include the accumulator.
+        if sum_dtype.is_float() && accumulator == &Scalar::zero_value(sum_dtype.clone()) {
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/sum.rs]: shall we add a is_zero() method?

File: vortex-array/src/compute/sum.rs [hunk 4]
```diff
@@ -102,15 +103,54 @@ impl ComputeFnVTable for Sum {
...
+                    .into());
+            } else if sum_dtype.is_decimal() {
+                let sum_from_stat = accumulator
+                    .as_decimal()
+                    .checked_binary_numeric(&sum.as_decimal(), NumericOperator::Add)
+                    .map(Scalar::from);
+                return Ok(sum_from_stat
+                    .unwrap_or_else(|| Scalar::null(sum_dtype))
+                    .into());
+            }
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/sum.rs]: match and fail if type differs

File: vortex-array/src/compute/sum.rs [hunk 5]
```diff
@@ -102,15 +103,66 @@ impl ComputeFnVTable for Sum {
 
         // Short-circuit using array statistics.
         if let Some(Precision::Exact(sum)) = array.statistics().get(Stat::Sum) {
-            return Ok(sum.into());
+            // For floats only use stats if accumulator is zero. otherwise we might have numerical stability issues.
+            match sum_dtype {
+                DType::Primitive(p, _) => {
+                    if p.is_float() {
+                        return Ok(sum.into());
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/sum.rs:110]: acc == 0 check?

File: vortex-array/src/compute/sum.rs [hunk 6]
```diff
@@ -102,15 +103,66 @@ impl ComputeFnVTable for Sum {
...
-            .statistics()
-            .set(Stat::Sum, Precision::Exact(sum_scalar.value().clone()));
+        // Update the statistics with the computed sum. Stored statistic shouldn't include the accumulator.
+        match sum_dtype {
+            DType::Primitive(p, _) => {
+                if p.is_float() && accumulator.is_zero() {
+                    array
+                        .statistics()
+                        .set(Stat::Sum, Precision::Exact(sum_scalar.value().clone()));
+                } else if p.is_int()
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/sum.rs:142]: would be nice is this was an assert that p is_int.

**Review by joseph-isaacs — APPROVED** [review]
Need the acc == 0, other optional

File: vortex-array/src/compute/sum.rs (hunk 6 above)
Comment (robert3005) [reply vortex-array/src/compute/sum.rs:142]: We cannot, we will fall through for floats with an accumulator
