### PR TITLE
fix sum decimal array overflow behavior with scalars

### LINKED ISSUE #6429: Fuzzing Crash: VortexError in file_io
### Analysis

**Crash Location**: `vortex-error/src/lib.rs:310:vortex_expect`

**Error Message**:
```
unable to construct a decimal `Scalar`:
  Incompatible dtype decimal(76,-74)? with value decimal256(-16999999999999999999999999999999999999999999999999999999999999999999999999983)
```

**Stack Trace**:
```
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/panicking.rs:80:14
   2: panic_display<vortex_error::VortexError>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/panicking.rs:259:5
   3: {closure#1}<vortex_scalar::scalar::Scalar, vortex_error::VortexError>
             at ./vortex-error/src/lib.rs:457:9
   4: unwrap_or_else<vortex_scalar::scalar::Scalar, vortex_error::VortexError, vortex_error::{impl#11}::vortex_expect::{closure_env#1}<vortex_scalar::scalar::Scalar, vortex_error::VortexError>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/result.rs:1622:23
   5: vortex_expect<vortex_scalar::scalar::Scalar, vortex_error::VortexError>
             at ./vortex-error/src/lib.rs:310:14
   6: decimal
             at ./vortex-scalar/src/constructor.rs:61:10
   7: sum
             at ./vortex-array/src/arrays/decimal/compute/sum.rs:57:32
   8: invoke<vortex_array::arrays::decimal::vtable::DecimalVTable>
             at ./vortex-array/src/compute/sum.rs:226:17
   9: sum_impl
             at ./vortex-array/src/compute/sum.rs:250:38
  10: invoke
             at ./vortex-array/src/compute/sum.rs:146:26
  11: invoke
             at ./vortex-array/src/compute/mod.rs:144:34
  12: sum_with_accumulator
             at ./vortex-array/src/compute/sum.rs:53:10
  13: sum
             at ./vortex-array/src/compute/sum.rs:70:5
  14: {closure#2}
             at ./vortex-array/src/stats/array.rs:159:25
  15: then<core::result::Result<vortex_scalar::scalar::Scalar, vortex_error::VortexError>, vortex_array::stats::array::{impl#3}::compute_stat::{closure_env#2}>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/bool.rs:66:24
  16: compute_stat
             at ./vortex-array/src/stats/array.rs:157:22
  17: push_chunk
             at ./vortex-layout/src/layouts/zoned/zone_map.rs:211:49
  18: process
             at ./vortex-layout/src/layouts/file_stats.rs:105:41
  19: {closure#0}
             at ./vortex-layout/src/layouts/file_stats.rs:36:36
  20: poll_next<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::file_stats::FileStatsAccumulator, core::future::ready::Ready<core::option::Option<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>>>, vortex_layout::layouts::file_stats::accumulate_stats::{closure_env#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/scan.rs:92:38
  21: poll_next<futures_util::stream::stream::scan::Scan<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::file_stats::FileStatsAccumulator, core::future::ready::Ready<core::option::Option<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>>>, vortex_layout::layouts::file_stats::accumulate_stats::{closure_env#0}>>
             at ./vortex-layout/src/sequence.rs:311:48
  22: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  23: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/fuse.rs:53:39
  24: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/peek.rs:203:21
  25: poll_next<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  26: poll_next_unpin<core::pin::Pin<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/mod.rs:1638:24
  27: poll<core::pin::Pin<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/next.rs:32:21
  28: {async_block#1}
             at ./vortex-layout/src/layouts/repartition.rs:133:70
  29: poll_next<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, vortex_layout::layouts::repartition::{impl#5}::write_stream::{async_block#0}::{async_block_env#1}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-stream-0.3.6/src/async_stream.rs:56:26
  30: poll_next<async_stream::async_stream::AsyncStream<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, vortex_layout::layouts::repartition::{impl#5}::write_stream::{async_block#0}::{async_block_env#1}>>
             at ./vortex-layout/src/sequence.rs:311:48
  31: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  32: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::zoned::writer::{impl#2}::write_stream::{async_block#0}::{closure_env#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/map.rs:58:47
  33: poll_next<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::zoned::writer::{impl#2}::write_stream::{async_block#0}::{closure_env#0}>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/fuse.rs:53:39
  34: poll_next<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::zoned::writer::{impl#2}::write_stream::{async_block#0}::{closure_env#0}>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/buffered.rs:66:40
  35: poll_next<futures_util::stream::stream::buffered::Buffered<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::zoned::writer::{impl#2}::write_stream::{async_block#0}::{closure_env#0}>>>
             at ./vortex-layout/src/sequence.rs:311:48
  36: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  37: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::zoned::writer::{impl#2}::write_stream::{async_block#0}::{closure_env#1}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/map.rs:58:47
  38: poll_next<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::zoned::writer::{impl#2}::write_stream::{async_block#0}::{closure_env#1}>>
             at ./vortex-layout/src/sequence.rs:311:48
  39: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  40: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::repartition::{impl#5}::write_stream::{async_block#0}::{closure_env#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/map.rs:58:47
  41: poll_next<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::repartition::{impl#5}::write_stream::{async_block#0}::{closure_env#0}>>
             at ./vortex-layout/src/sequence.rs:311:48
  42: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  43: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/fuse.rs:53:39
  44: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/peek.rs:203:21
  45: poll_next<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  46: poll_next_unpin<core::pin::Pin<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/mod.rs:1638:24
  47: poll<core::pin::Pin<&mut futures_util::stream::stream::peek::Peekable<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/next.rs:32:21
  48: {async_block#1}
             at ./vortex-layout/src/layouts/repartition.rs:133:70
  49: poll_next<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, vortex_layout::layouts::repartition::{impl#5}::write_stream::{async_block#0}::{async_block_env#1}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-stream-0.3.6/src/async_stream.rs:56:26
  50: poll_next<async_stream::async_stream::AsyncStream<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, vortex_layout::layouts::repartition::{impl#5}::write_stream::{async_block#0}::{async_block_env#1}>>
             at ./vortex-layout/src/sequence.rs:311:48
  51: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  52: poll_next<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::compressed::{impl#5}::write_stream::{async_block#0}::{closure_env#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/map.rs:58:47
  53: poll_next<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::compressed::{impl#5}::write_stream::{async_block#0}::{closure_env#0}>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/fuse.rs:53:39
  54: poll_next<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::compressed::{impl#5}::write_stream::{async_block#0}::{closure_env#0}>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/buffered.rs:66:40
  55: poll_next<futures_util::stream::stream::buffered::Buffered<futures_util::stream::stream::map::Map<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>, vortex_layout::layouts::compressed::{impl#5}::write_stream::{async_block#0}::{closure_env#0}>>>
             at ./vortex-layout/src/sequence.rs:311:48
  56: poll_next<&mut (dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send)>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  57: poll_next_unpin<core::pin::Pin<&mut (dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send)>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/mod.rs:1638:24
  58: poll<core::pin::Pin<&mut (dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send)>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/next.rs:32:21
  59: {async_block#0}
             at ./vortex-layout/src/layouts/buffered.rs:64:60
  60: poll_next<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, vortex_layout::layouts::buffered::{impl#2}::write_stream::{async_block#0}::{async_block_env#0}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-stream-0.3.6/src/async_stream.rs:56:26
  61: poll_next<async_stream::async_stream::AsyncStream<core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>, vortex_layout::layouts::buffered::{impl#2}::write_stream::{async_block#0}::{async_block_env#0}>>
             at ./vortex-layout/src/sequence.rs:311:48
  62: poll_next<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  63: poll_next_unpin<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/mod.rs:1638:24
  64: poll<core::pin::Pin<alloc::boxed::Box<(dyn vortex_layout::sequence::SequentialStream<Item=core::result::Result<(vortex_layout::sequence::SequenceId, alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>), vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/next.rs:32:21
  65: {async_block#1}
             at ./vortex-layout/src/layouts/chunked/writer.rs:58:51
  66: poll_next<vortex_io::runtime::handle::Task<core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>>, vortex_layout::layouts::chunked::writer::{impl#2}::write_stream::{async_block#0}::{async_block_env#1}>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-stream-0.3.6/src/async_stream.rs:56:26
  67: poll_next<async_stream::async_stream::AsyncStream<vortex_io::runtime::handle::Task<core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>>, vortex_layout::layouts::chunked::writer::{impl#2}::write_stream::{async_block#0}::{async_block_env#1}>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/fuse.rs:53:39
  68: poll_next<async_stream::async_stream::AsyncStream<vortex_io::runtime::handle::Task<core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>>, vortex_layout::layouts::chunked::writer::{impl#2}::write_stream::{async_block#0}::{async_block_env#1}>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/buffered.rs:66:40
  69: try_poll_next<futures_util::stream::stream::buffered::Buffered<async_stream::async_stream::AsyncStream<vortex_io::runtime::handle::Task<core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>>, vortex_layout::layouts::chunked::writer::{impl#2}::write_stream::{async_block#0}::{async_block_env#1}>>, alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:206:14
  70: poll<futures_util::stream::stream::buffered::Buffered<async_stream::async_stream::AsyncStream<vortex_io::runtime::handle::Task<core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>>, vortex_layout::layouts::chunked::writer::{impl#2}::write_stream::{async_block#0}::{async_block_env#1}>>, alloc::vec::Vec<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, alloc::alloc::Global>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/try_stream/try_collect.rs:46:47
  71: {async_block#0}
             at ./vortex-layout/src/layouts/chunked/writer.rs:85:91
  72: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  73: {async_block#0}
             at ./vortex-layout/src/layouts/buffered.rs:105:14
  74: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  75: {async_block#0}
             at ./vortex-layout/src/layouts/compressed.rs:137:14
  76: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  77: {async_block#0}
             at ./vortex-layout/src/layouts/repartition.rs:179:14
  78: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  79: {async_block#0}
             at ./vortex-layout/src/layouts/dict/writer.rs:141:18
  80: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  81: {async_block#0}
             at ./vortex-layout/src/layouts/zoned/writer.rs:135:14
  82: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  83: {async_block#0}
             at ./vortex-layout/src/layouts/repartition.rs:179:14
  84: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  85: {async_block#0}
             at ./vortex-layout/src/layouts/table.rs:203:18
  86: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, vortex_error::VortexError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  87: {async_block#0}<vortex_file::writer::BlockingWriteAdapter<&mut vortex_buffer::buffer_mut::BufferMut<u8>>>
             at ./vortex-file/src/writer.rs:185:18
  88: {async_block#0}<vortex_file::writer::{impl#2}::write_internal::{async_fn#0}::{closure#2}::{async_block_env#0}<vortex_file::writer::BlockingWriteAdapter<&mut vortex_buffer::buffer_mut::BufferMut<u8>>>, core::result::Result<(alloc::sync::Arc<dyn vortex_layout::layout::Layout, alloc::alloc::Global>, alloc::sync::Arc<[vortex_file::footer::segment::SegmentSpec], alloc::alloc::Global>), vortex_error::VortexError>>
             at ./vortex-io/src/runtime/handle.rs:71:34
  89: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/future/future.rs:133:9
  90: poll<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.3/src/lib.rs:1197:31
  91: {closure#1}<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-task-4.7.1/src/raw.rs:550:21
  92: call_once<async_task::raw::{impl#3}::run::{closure_env#1}<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>, ()>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/ops/function.rs:250:5
  93: call_once<core::task::poll::Poll<()>, async_task::raw::{impl#3}::run::{closure_env#1}<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/core/src/panic/unwind_safe.rs:274:9
  94: do_call<core::panic::unwind_safe::AssertUnwindSafe<async_task::raw::{impl#3}::run::{closure_env#1}<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>>, core::task::poll::Poll<()>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panicking.rs:581:40
  95: __rust_try
  96: catch_unwind<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<async_task::raw::{impl#3}::run::{closure_env#1}<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panicking.rs:544:19
  97: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<async_task::raw::{impl#3}::run::{closure_env#1}<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>>, core::task::poll::Poll<()>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panic.rs:359:14
  98: run<async_executor::AsyncCallOnDrop<core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>, async_executor::{impl#5}::spawn_inner::{closure_env#0}<(), core::pin::Pin<alloc::boxed::Box<(dyn core::future::future::Future<Output=()> + core::marker::Send), alloc::alloc::Global>>>>, (), async_executor::{impl#5}::schedule::{closure_env#0}, ()>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-task-4.7.1/src/raw.rs:549:23
  99: run<()>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-task-4.7.1/src/runnable.rs:781:18
 100: {async_block#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.3/src/lib.rs:751:30
 101: poll<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>, async_executor::{impl#13}::run::{async_fn#0}::{async_block_env#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-lite-2.6.1/src/future.rs:454:46
 102: {async_fn#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.3/src/lib.rs:758:32
 103: {async_fn#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-executor-1.13.3/src/lib.rs:344:34
 104: {closure#1}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, async_executor::{impl#5}::run::{async_fn_env#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-io-2.6.0/src/driver.rs:204:53
 105: try_with<core::cell::RefCell<(parking::Parker, core::task::wake::Waker, alloc::sync::Arc<core::sync::atomic::AtomicBool, alloc::alloc::Global>)>, async_io::driver::block_on::{closure_env#1}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, async_executor::{impl#5}::run::{async_fn_env#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>>, core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/thread/local.rs:513:12
 106: with<core::cell::RefCell<(parking::Parker, core::task::wake::Waker, alloc::sync::Arc<core::sync::atomic::AtomicBool, alloc::alloc::Global>)>, async_io::driver::block_on::{closure_env#1}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, async_executor::{impl#5}::run::{async_fn_env#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>>, core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/thread/local.rs:477:20
 107: block_on<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, async_executor::{impl#5}::run::{async_fn_env#0}<core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>, vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>>>
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/async-io-2.6.0/src/driver.rs:180:11
 108: block_on<vortex_file::writer::{impl#4}::write::{async_block_env#0}<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>, core::result::Result<vortex_file::writer::WriteSummary, vortex_error::VortexError>>
             at ./vortex-io/src/runtime/current.rs:102:9
 109: write<vortex_io::runtime::current::CurrentThreadRuntime, &mut vortex_buffer::buffer_mut::BufferMut<u8>, vortex_array::iter::ArrayIteratorAdapter<vortex_array::iter::ArrayChunkIterator>>
             at ./vortex-file/src/writer.rs:385:22
 110: __libfuzzer_sys_run
             at ./fuzz/fuzz_targets/file_io.rs:73:10
 111: rust_fuzzer_test_input
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:363:60
 112: {closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:62:9
 113: do_call<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panicking.rs:581:40
 114: __rust_try
 115: catch_unwind<i32, libfuzzer_sys::test_input_wrap::{closure_env#0}>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panicking.rs:544:19
 116: catch_unwind<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/9e79395f92bff6a8f536430e42a4beae69f60ff8/library/std/src/panic.rs:359:14
 117: test_input_wrap
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:60:22
 118: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:619:13
 119: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEbPb
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:516:7
 120: _ZN6fuzzer6Fuzzer25ReadAndExecuteSeedCorporaERSt6vectorINS_9SizedFileESaIS2_EE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:834:7
 121: _ZN6fuzzer6Fuzzer4LoopERSt6vectorINS_9SizedFileESaIS2_EE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:872:3
 122: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerDriver.cpp:915:6
 123: main
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerMain.cpp:20:10
 124: <unknown>
 125: __libc_start_main
 126: _start
```

<details>
<summary>Debug Output</summary>

```
FuzzFileAction {
    array: DecimalArray {
        dtype: Decimal(
            DecimalDType {
                precision: 75,
                scale: -74,
            },
            NonNullable,
        ),
        values: BufferHandle(
            Host(
                Buffer<u8> {
                    length: 544,
                    alignment: Alignment(
                        16,
                    ),
                    as_slice: [1, 0, 0, 0, 0, 0, 0, 0, 0, 24, 113, 65, 206, 213, 13, 116, ...],
                },
            ),
        ),
        values_type: I256,
        validity: NonNullable,
        stats_set: ArrayStats {
            inner: RwLock {
                data: StatsSet {
                    values: [],
                },
            },
        },
    },
    projection_expr: None,
    filter_expr: None,
    compressor_strategy: Compact,
}
```
</details>

### Summary

- **Target**: `file_io`
- **Crash File**: `crash-0164570dfaa7bef3f85335192ff058bc4d4c6ebe`
- **Branch**: ji/fixup-fizz-issue-gen-backtrace
- **Commit**: 1c201557bd65a6fd6b056caf3a2db809da28c616
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/21910901665/artifacts/5467812019

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/21910901665/artifacts/5467812019
   - Extract the zip file

2. Reproduce locally:
```bash
cargo +nightly fuzz run -D --sanitizer=none file_io file_io/crash-0164570dfaa7bef3f85335192ff058bc4d4c6ebe -- -rss_limit_mb=0
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run -D --sanitizer=none file_io file_io/crash-0164570dfaa7bef3f85335192ff058bc4d4c6ebe -- -rss_limit_mb=0
```

---
*Auto-created by fuzzing workflow*

### PR DESCRIPTION
**Pull request by connortsui20**
Fixes https://github.com/vortex-data/vortex/issues/6429

Also refactors the code a bit so that we dont need a clippy allow complexity

### CODE REVIEW

**Comment by robert3005** [comment]
What was the bug here? That we returned overflow value even though it didn't fit into the declared dtype?

File: vortex-array/src/arrays/decimal/compute/sum.rs [hunk 1]
```diff
@@ -24,75 +26,79 @@ use crate::expr::stats::Stat;
...
+        let mask = array.validity_mask()?;
+        if matches!(&mask, Mask::AllFalse(_)) {
+            vortex_bail!("invalid state, all-null array should be checked by top-level sum fn")
         }
+
+        let validity = match &mask {
+            Mask::AllTrue(_) => None,
+            Mask::Values(mask_values) => Some(mask_values.bit_buffer()),
+            Mask::AllFalse(_) => unreachable!("handled above"),
+        };
```
Comment (joseph-isaacs) [inline vortex-array/src/arrays/decimal/compute/sum.rs:50]: odd to match on `Mask::AllFalse(_)` twice

Comment (connortsui20) [reply vortex-array/src/arrays/decimal/compute/sum.rs:50]: fixed

**Review by joseph-isaacs — APPROVED** [review]

**Review by robert3005 — APPROVED** [review]

**Comment by joseph-isaacs** [comment]
overflow the precision but not the storage type?

**Comment by connortsui20** [comment]
> That we returned overflow value even though it didn't fit into the declared dtype?

Yep, so the summation of the decimal array might not have fit the return dtype (even if it did not overflow the storage value). The regression test included in this change does something similar to what the fuzzer found.

**Comment by connortsui20** [comment]
> overflow the precision but not the storage type?

Previously it only checked overflow on the storage type (in the `sum_decimal` and `sum_decimal_with_validity` functions with `CheckedAdd::checked_add`), now it does both

**Comment by robert3005** [comment]
Thanks, I should have read the test before asking my question
