### PR TITLE
fix: `SequenceVTable` bounds check

### LINKED ISSUE #5332: Phantom reads
### Describe the bug

I am on [vortex@31b56](https://github.com/vortex-data/vortex/commit/31b5671996af0ac93edcbec3f57f9584b29ed49d)

Suppose, I have a file with vortex array: 

```
┌──────────┐
│ col_v0_a │
├──────────┤
│ 0u8      │
├──────────┤
│ 20u8     │
├──────────┤
│ 40u8     │
└──────────┘
```

When loading the file, I explicitly load just row 1. This is my loaded `array`

```
┌──────────┐
│ col_v0_a │
├──────────┤
│ 20u8     │
└──────────┘
```

Later, I do `take(array, [0, 2])`. I except to see `index out of bounds: the len is 1 but the index is 2` but instead I see the data **that were never in the array**

```
┌──────────┐
│ col_v0_a │
├──────────┤
│ 20u8     │
├──────────┤
│ 60u8     │
└──────────┘
```

### To Reproduce

```rust
let session = VortexSession::default().with_tokio();

let array = session
    .open_options()
    .open("S0lD7meT611rRYbr7e--W.vortex")
    .await?
    .scan()?
    .with_row_indices(PrimitiveArray::from_iter([1u64]).into_buffer::<u64>())
    .into_array_stream()?
    .read_all()
    .await?;

println!("{}", array.display_table());

let expanded_array = take(&array, &PrimitiveArray::from_iter([0, 2]).into_array()).unwrap();

println!("{}", expanded_array.display_table());
```

[S0lD7meT611rRYbr7e--W.vortex.zip](https://github.com/user-attachments/files/23531453/S0lD7meT611rRYbr7e--W.vortex.zip)

### Expected behavior

`index out of bounds: the len is 1 but the index is 2`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by blaginin**
Closes https://github.com/vortex-data/vortex/issues/5332

### CODE REVIEW

**Comment by blaginin** [comment]
Should we just have a top level check directly at take? Probably not? 

image

**Comment by joseph-isaacs** [comment]
Do we not have this?

File: encodings/sequence/src/compute/take.rs [hunk 1]
```diff
@@ -34,6 +36,17 @@ impl TakeKernel for SequenceVTable {
     }
 }
 
+fn check_bounds<T: IntegerPType>(indices: &[T], len: usize) -> VortexResult<()> {
```
Comment (joseph-isaacs) [inline encodings/sequence/src/compute/take.rs]: have the merge with below

**Review by joseph-isaacs — APPROVED** [review]
