### PR TITLE
fix: Adjust the constant optimization in `list_contains`

### LINKED ISSUE #3210: Non-deterministic assertion failure in `FlatEvaluation`
Hey folks! Thanks a lot for your work on Vortex.

In [this repository](https://github.com/stuhood/vfts/blob/706cec06a5d6428ad62778980d02621371479ab1/src/vortex.rs#L171-L220) (at [706cec06](https://github.com/stuhood/vfts/tree/706cec06a5d6428ad62778980d02621371479ab1)), creating an index at `out.vortex` with:
```bash
cargo run -- index vortex out.vortex 256
```
... succeeds deterministically.

But scanning that file fails non-deterministically (roughly 50% of the time):
```bash
RUST_BACKTRACE=1 cargo run -- search vortex out.vortex "well wisdom"
```
...with the following stacktrace:
```
thread 'main' panicked at /Users/stuhood/.cargo/git/checkouts/vortex-45c4be85f8d34026/d4c14e4/vortex-mask/src/intersect_by_rank.rs:26:9:
assertion `left == right` failed
  left: 15
 right: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f8a913b1381e90379c7ca63ac2b88b9518936628/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at /rustc/f8a913b1381e90379c7ca63ac2b88b9518936628/library/core/src/panicking.rs:75:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/f8a913b1381e90379c7ca63ac2b88b9518936628/library/core/src/panicking.rs:380:5
   4: vortex_mask::intersect_by_rank::<impl vortex_mask::Mask>::intersect_by_rank
   5: <vortex_layout::layouts::flat::eval_expr::FlatEvaluation as vortex_layout::reader::MaskEvaluation>::invoke::{{closure}}
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: <vortex_layout::layouts::filter::FilterEvaluation as vortex_layout::reader::MaskEvaluation>::invoke::{{closure}}
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
   9: vortex_layout::scan::ScanBuilder<A>::build::{{closure}}::{{closure}}
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
  11: vortex_layout::scan::ScanBuilder<A>::build::{{closure}}::{{closure}}
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
  13: <futures_util::stream::futures_ordered::OrderWrapper<T> as core::future::future::Future>::poll
  14: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
  15: futures_util::stream::stream::StreamExt::poll_next_unpin
  16: <futures_util::stream::futures_ordered::FuturesOrdered<Fut> as futures_core::stream::Stream>::poll_next
  17: futures_util::stream::stream::StreamExt::poll_next_unpin
  18: <futures_util::stream::stream::buffered::Buffered<St> as futures_core::stream::Stream>::poll_next
  19: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
  20: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
  21: futures_util::stream::stream::StreamExt::poll_next_unpin
  22: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
  23: df_v_fts::vortex::vortex_search::{{closure}}
  24: df_v_fts::main::{{closure}}
  25: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
  26: tokio::runtime::park::CachedParkThread::block_on
  27: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
  28: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
  29: tokio::runtime::context::runtime::enter_runtime
  30: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  31: tokio::runtime::runtime::Runtime::block_on_inner
  32: tokio::runtime::runtime::Runtime::block_on
  33: df_v_fts::main
  34: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The crash only seems to occur when I'm using the new `list_contains` and the [`ListContainsExpr`](https://github.com/stuhood/vfts/blob/706cec06a5d6428ad62778980d02621371479ab1/src/vortex_list_expr.rs#L13-L18) wrapper that I added in the repo, so it's possible that I did something wrong there.

Thanks!

### PR DESCRIPTION
**Pull request by stuhood**
The constant optimization in `list_contains` was incorrect (and could cause a crash like #3210), because it:
1. produced a `ConstantArray` with the length of the `elements` array, rather than with the length of the input `ListArray`.
2. produced a `ConstantArray(true)` when all `elements` matched, without correlating with the `offsets` (which might contain empty lists).

This change adjusts the constant optimization to only trigger if no elements match, and to produce a `ConstantArray` of the appropriate length.

Fixes #3210.

### CODE REVIEW

File: vortex-array/src/compute/list.rs [hunk 1]
```diff
@@ -62,13 +62,12 @@ pub fn list_contains(array: &dyn Array, value: Scalar) -> VortexResult<ArrayRef>
     let matching_elements = compare(elems, &rhs, Operator::Eq)?;
     let matches = matching_elements.to_bool()?;
 
-    // Fast path: all elements match or none match.
+    // Fast path: no elements match.
     if let Some(pred) = matches.as_constant() {
-        return match pred.as_bool().value() {
+        if matches!(pred.as_bool().value(), None | Some(false)) {
             // TODO(aduffy): how do we handle null?
-            None | Some(false) => Ok(ConstantArray::new::<bool>(false, matches.len()).into_array()),
```
Comment (a10y) [inline vortex-array/src/compute/list.rs:69]: gah, embarrassing. sorry about that

**Review by a10y — APPROVED** [review]
Thank you for fixing this!

**Comment by gatesn** [comment]
Still intrigued by the non-determinism...

**Comment by stuhood** [comment]
> Still intrigued by the non-determinism...

That's answered on the ticket: sorry. It was Rust's usual randomized hash order causing the non-determinism when we got `Exprs` in a different order.
