### PR TITLE
fix: cfg disable unix-specific operations

### LINKED ISSUE #5311: FFI does not build on windows
### Describe the bug

```
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> vortex-io\src\file\object_store.rs:5:14
   |
5  | use std::os::unix::fs::FileExt;
   |              ^^^^ could not find `unix` in `os`
   |
note: found an item that was configured out
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:36:9
   |
36 | pub mod unix {}
   |         ^^^^
note: the item is gated here
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:28:1
   |
28 | / #[cfg(all(
29 | |     doc,
30 | |     any(
31 | |         all(target_arch = "wasm32", not(target_os = "wasi")),
...  |
34 | | ))]
   | |___^
note: found an item that was configured out
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:85:9
   |
85 | pub mod unix;
   |         ^^^^
note: the item is gated here
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:84:1
   |
84 | #[cfg(all(not(target_os = "hermit"), any(unix, doc)))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: could not find `unix` in `os`
  --> vortex-io\src\file\std_file.rs:5:14
   |
5  | use std::os::unix::fs::FileExt;
   |              ^^^^ could not find `unix` in `os`
   |
note: found an item that was configured out
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:36:9
   |
36 | pub mod unix {}
   |         ^^^^
note: the item is gated here
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:28:1
   |
28 | / #[cfg(all(
29 | |     doc,
30 | |     any(
31 | |         all(target_arch = "wasm32", not(target_os = "wasi")),
...  |
34 | | ))]
   | |___^
note: found an item that was configured out
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:85:9
   |
85 | pub mod unix;
   |         ^^^^
note: the item is gated here
  --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\os\mod.rs:84:1
   |
84 | #[cfg(all(not(target_os = "hermit"), any(unix, doc)))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `read_exact_at` found for struct `std::fs::File` in the current scope
    --> vortex-io\src\file\object_store.rs:134:42
     |
134  | ...                   file.read_exact_at(&mut buffer, range.start)?;
     |                            ^^^^^^^^^^^^^
     |
help: there is a method `read_exact` with a similar name, but with different arguments
    --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\io\mod.rs:1044:5
     |
1044 |     fn read_exact(&mut self, buf: &mut [u8]) -> Result<()> {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `read_exact_at` found for struct `Arc<std::fs::File>` in the current scope
    --> vortex-io\src\file\std_file.rs:85:48
     |
85   |                         req.resolve(match file.read_exact_at(&mut buffer, offset) {
     |                                                ^^^^^^^^^^^^^
     |
help: there is a method `read_exact` with a similar name, but with different arguments
    --> C:\Users\fjapl\.rustup\toolchains\1.89-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\std\src\io\mod.rs:1044:5
     |
1044 |     fn read_exact(&mut self, buf: &mut [u8]) -> Result<()> {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `vortex-io` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

I think some system calls require linux

### To Reproduce

Running command `cargo build --release -p vortex-ffi`

### Expected behavior

Builds and gives me a .dll file i can use

### Additional context

On windows 10.

This works on linux Arch and i get a .so file. But i cant get it to work on windows.

### PR DESCRIPTION
**Pull request by danking**
Fixes #5311.

I think seek-then-read is safe because we own this File. No one else should be relying on its cursor.

vortex_io::file::std_file appears to only be used in tests.

### CODE REVIEW

**Comment by AdamGS** [comment]
There's an old `object_store` [issue](https://github.com/apache/arrow-rs-object-store/issues/18) about this exact point, I think its a bit ambiguous but probably fine for 99.999% of usage

**Review by AdamGS — APPROVED** [review]

**Review by a10y — APPROVED** [review]

File: vortex-io/src/file/object_store.rs [hunk 1]
```diff
@@ -129,10 +130,18 @@ impl ReadSource for ObjectStoreIoSource {
...
                                 .spawn_blocking(move || {
-                                    file.read_exact_at(&mut buffer, range.start)?;
-                                    Ok::<_, io::Error>(buffer)
+                                    #[cfg(unix)] {
+                                        file.read_exact_at(&mut buffer, range.start)?;
+                                        Ok::<_, io::Error>(buffer)
+                                    }
+                                    #[cfg(not(unix))] {
+                                        file.seek(range.start)?;
+                                        file.read_exact(&mut buffer)?;
```
Comment (robert3005) [inline vortex-io/src/file/object_store.rs:142]: state of these confuses me deeply in rust standard library. I thought there's an equivalent read_exact_at but no you have to map and unmap the file which would be bad
