### PR TITLE
Add `ByteBoolArray` type and fixe a bug in `BoolArray`

### LINKED ISSUE #335: Add a ByteBoolArray
Where each boolean is represented as a single byte. This allows zero-copy from formats that use this layout, e.g. Vec<bool>

### PR DESCRIPTION
**Pull request by AdamGS**
The main two contributions in this PR are:
1. A new `ByteBoolArray` type (closes #335)
2. An important fix for slicing and initialization of `BoolArray`

### CODE REVIEW

File: vortex-array/src/array/bool/compute/scalar_at.rs [hunk 1]
```diff
@@ -9,7 +9,12 @@ use crate::ArrayDType;
 impl ScalarAtFn for BoolArray {
     fn scalar_at(&self, index: usize) -> VortexResult<Scalar> {
         if self.is_valid(index) {
-            Ok(self.boolean_buffer().value(index).into())
+            let value = self.boolean_buffer().value(index);
+            let s = Scalar::new(
```
Comment (gatesn) [inline vortex-array/src/array/bool/compute/scalar_at.rs]: I wonder if we should wrap the native type -> scalar conversions in #cfg(test), they're just too dangerous

File: vortex-array/src/array/bool/mod.rs [hunk 2]
```diff
@@ -37,14 +37,19 @@ impl BoolArray {
 
 impl BoolArray {
     pub fn try_new(buffer: BooleanBuffer, validity: Validity) -> VortexResult<Self> {
+        let buffer_len = buffer.len();
+        let buffer_offset = buffer.offset();
+
+        let inner = buffer.into_inner().bit_slice(buffer_offset, buffer_len);
```
Comment (gatesn) [inline vortex-array/src/array/bool/mod.rs]: So I think this only partially fixes the bug. The problem is that the BoolArray itself doesn't hold an offset, meaning the first bit is always considered to be byte aligned.

Maybe in another PR can fix for real by adding a bit_offset (from 0..8) field to BoolMetadata. The SliceFn compute function and maybe others must also respect it.

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 3]
```diff
@@ -0,0 +1,242 @@
...
+        slice::SliceFn, take::TakeFn, ArrayCompute,
+    },
+    encoding::ArrayEncodingRef,
+    stats::StatsSet,
+    validity::ArrayValidity,
+    ArrayDType, ArrayData, ArrayTrait, IntoArray,
+};
+
+impl ArrayCompute for ByteBoolArray {
+    fn as_arrow(&self) -> Option<&dyn crate::compute::as_arrow::AsArrowArray> {
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: Nit: move the fully qualified names to imports

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 4]
```diff
@@ -0,0 +1,242 @@
...
+
+impl ScalarAtFn for ByteBoolArray {
+    fn scalar_at(&self, index: usize) -> VortexResult<Scalar> {
+        if index >= self.len() {
+            vortex_bail!(OutOfBounds: index, 0, self.len());
+        }
+
+        let scalar = match self.is_valid(index).then(|| self.buffer()[index] == 1) {
+            Some(b) => Scalar::new(
+                vortex_dtype::DType::Bool(self.validity().nullability()),
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: This can also be `self.dtype().clone()` right?

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 5]
```diff
@@ -0,0 +1,242 @@
...
+                vortex_scalar::ScalarValue::Bool(b),
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: Remove fully qualified

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 6]
```diff
@@ -0,0 +1,242 @@
...
+        Ok(scalar)
+    }
+}
+
+impl AsArrowArray for ByteBoolArray {
+    fn as_arrow(&self) -> VortexResult<ArrowArrayRef> {
+        let nulls = self.logical_validity().to_null_buffer()?;
+
+        let mut builder = BooleanBufferBuilder::new(self.len());
+        builder.append_slice(self.as_ref());
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: This AsRef feels dangerous. The problem is validity/nulls. It makes it too easy to forget about them. Would rather it be an explicit accessor like `self.maybe_null_slice()`. We should rename `PrimitiveArray.typed_data` to `PrimitiveArray.maybe_null_slice()` too!

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 7]
```diff
@@ -0,0 +1,242 @@
...
+}
+
+impl SliceFn for ByteBoolArray {
+    fn slice(&self, start: usize, stop: usize) -> VortexResult<crate::Array> {
+        let length = stop - start;
+
+        let validity = self.validity().slice(start, stop)?;
+
+        let slice_metadata = Arc::new(ByteBoolMetadata {
+            validity: validity.to_metadata(length)?,
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: Just a note, this eagerly re-computes whether the slice is AllValid/AllInvalid. Which is nice, just maybe leave a comment since it's perhaps not obvious why this is done

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 8]
```diff
@@ -0,0 +1,242 @@
...
+        let validity = self.validity();
+        let indices = indices.clone().flatten_primitive()?;
+        let bools = self.as_ref();
+
+        let bools = match_each_integer_ptype!(indices.ptype(), |$I| {
+            indices.typed_data::<$I>()
+            .iter()
+            .map(|&idx| {
+                let idx = idx.as_();
+                if validity.is_valid(idx) {
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: It might be better to first match on validity and short-cut for AllValid / AllInvalid.

Then convert validity to a null_buffer, and `iter().zip()`.

Currently this makes a function call for every element, which can be quite expensive.

File: vortex-array/src/array/byte_bool/compute/mod.rs [hunk 9]
```diff
@@ -0,0 +1,242 @@
...
+            Operator::Lte => lhs.not().bitor(&rhs),
+        };
+
+        let mut validity = Vec::with_capacity(self.len());
+
+        let lhs_validity = self.validity();
+        let rhs_validity = flattened.validity();
+
+        for idx in 0..self.len() {
+            let l = lhs_validity.is_valid(idx);
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/compute/mod.rs]: Similar here, this is an expensive validity check

File: vortex-array/src/array/byte_bool/mod.rs [hunk 10]
```diff
@@ -0,0 +1,161 @@
...
+
+mod compute;
+mod stats;
+
+impl_encoding!("vortex.byte_bool", ByteBool);
+
+#[derive(Clone, Debug, Serialize, Deserialize)]
+pub struct ByteBoolMetadata {
+    validity: ValidityMetadata,
+    length: usize,
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/mod.rs]: I don't think we need length for ByteBool do we? Since length == `buffer.len()`

File: vortex-array/src/array/byte_bool/mod.rs [hunk 11]
```diff
@@ -0,0 +1,161 @@
...
+
+        let buffer = Buffer::from(bytes);
+        let typed = TypedArray::try_from_parts(
+            DType::Bool(validity.nullability()),
+            ByteBoolMetadata {
+                validity: validity.to_metadata(length)?,
+                length,
+            },
+            Some(buffer),
+            validity.into_array_data().into_iter().collect_vec().into(),
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/mod.rs]: I think this should just be `vec![validity.into_array_data()]`?

File: vortex-array/src/array/byte_bool/mod.rs [hunk 12]
```diff
@@ -0,0 +1,161 @@
...
+
+    pub fn buffer(&self) -> &Buffer {
+        self.array().buffer().expect("missing mandatory buffer")
+    }
+}
+
+impl From<Vec<bool>> for ByteBoolArray {
+    fn from(value: Vec<bool>) -> Self {
+        let value_len = value.len();
+        Self::try_with_validity(value, NullBuffer::new_valid(value_len)).unwrap()
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/mod.rs]: Just a note, this will create a nullable bool array I think? Not sure if that was intended?

File: vortex-array/src/array/byte_bool/mod.rs [hunk 13]
```diff
@@ -0,0 +1,161 @@
...
+        let validity = Validity::from_iter(value.iter());
+
+        // This doesn't reallocate, and the compiler even vectorizes it
+        let data = value.into_iter().map(|b| b.unwrap_or_default()).collect();
+
+        Self::try_with_validity(data, validity).unwrap()
+    }
+}
+
+impl AsRef<[bool]> for ByteBoolArray {
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/mod.rs]: Yeah, this is the one I don't like. These damn nulls!

File: vortex-array/src/array/byte_bool/mod.rs [hunk 14]
```diff
@@ -0,0 +1,161 @@
...
+    fn as_ref(&self) -> &[bool] {
+        // Safety: bool and u8 are the same size. We don't care about logically null values here.
+        unsafe { std::mem::transmute(self.buffer().as_slice()) }
+    }
+}
+
+impl ArrayTrait for ByteBoolArray {
+    fn len(&self) -> usize {
+        self.metadata().length
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/mod.rs]: `self.buffer().len()`

File: vortex-array/src/array/byte_bool/stats.rs [hunk 15]
```diff
@@ -0,0 +1,41 @@
...
+};
+
+impl ArrayStatisticsCompute for ByteBoolArray {
+    fn compute_statistics(&self, stat: Stat) -> VortexResult<StatsSet> {
+        if self.is_empty() {
+            return Ok(StatsSet::new());
+        }
+
+        match self.logical_validity() {
+            LogicalValidity::AllValid(len) => Ok(all_true_bool_stats(len)),
```
Comment (gatesn) [inline vortex-array/src/array/byte_bool/stats.rs]: I don't think this works? Just because all values are non-null, doesn't mean all values are true.

Comment (AdamGS) [reply vortex-array/src/array/byte_bool/stats.rs]: 100%

**Comment by gatesn** [comment]
The other high-level comment, we should move this encoding into a crate. The main vortex-array encodings are (mostly) only those that convert 1:1 to Arrow. Anything else is an "extension"

File: vortex-array/src/array/bool/mod.rs (hunk 2 above)
Comment (AdamGS) [reply vortex-array/src/array/bool/mod.rs]: `bit_slice` actually copies the buffer if the offset isn't byte aligned so this operation isn't as cheap as it used to be. Whether that's a reasonable tradeoff is up to you.
I do agree with the second point, I'm obviously not familiar with every part of the codebase here but taking the offset logic management into vortex will probably be valuable.

Comment (gatesn) [reply vortex-array/src/array/bool/mod.rs]: Yeah, the general idea is that construction and SliceFn should be constant time and not re-allocate. Which is why lots of arrays hold offsets.

Reminds me, we should have some logic to slice out those offsets during serialization!

File: vortex-array/src/array/bool/compute/scalar_at.rs (hunk 1 above)
Comment (AdamGS) [reply vortex-array/src/array/bool/compute/scalar_at.rs]: Honestly already pretty hard to work with scalars IMO, but I don't have a much better idea here.

File: vortex-array/src/array/byte_bool/compute/mod.rs (hunk 6 above)
Comment (AdamGS) [reply vortex-array/src/array/byte_bool/compute/mod.rs]: In your mind, should `maybe_null_slice` should still return `&[bool]`? I can also just make it a private method, so users won't be able to shoot themselves in the foot.

File: vortex-array/src/array/bool/compute/scalar_at.rs (hunk 1 above)
Comment (gatesn) [reply vortex-array/src/array/bool/compute/scalar_at.rs]: Maybe an improved API is `Scalar::bool(...)` and `Scalar::nullable_bool(...)` and we just explicitly write out the constructors.

File: vortex-array/src/array/byte_bool/compute/mod.rs (hunk 6 above)
Comment (gatesn) [reply vortex-array/src/array/byte_bool/compute/mod.rs]: Keep it public, users might need to access the bools themselves, but `pub fn maybe_null_slice(&self) -> &[bool]`

I merged the rename from `typed_data -> maybe_null_slice(&self) -> &[T]`

File: vortex-array/src/array/byte_bool/mod.rs (hunk 11 above)
Comment (AdamGS) [reply vortex-array/src/array/byte_bool/mod.rs]: No, took this snippet from `BoolArray`, it can probably be simplified but I suspect that's going to take a bigger change

File: vortex-array/src/array/byte_bool/mod.rs (hunk 13 above)
Comment (AdamGS) [reply vortex-array/src/array/byte_bool/mod.rs]: Removed

**Comment by AdamGS** [comment]
Pushed fixes for most comment, I think stats are the last thing I need to fix here

File: vortex-array/src/array/byte_bool/compute/mod.rs (hunk 7 above)
Comment (AdamGS) [reply vortex-array/src/array/byte_bool/compute/mod.rs]: Not sure I understand, seems like it just keeps the existing validity, with slight adjustment for arrays.

Comment (robert3005) [reply vortex-array/src/array/byte_bool/compute/mod.rs]: Not sure what Nick meant here, it's `to_logical` that does the evaluation

File: encodings/byte_bool/src/compute/mod.rs [hunk 16]
```diff
@@ -0,0 +1,265 @@
...
+    fn slice(&self, start: usize, stop: usize) -> VortexResult<Array> {
+        let length = stop - start;
+
+        let validity = self.validity().slice(start, stop)?;
+
+        let slice_metadata = Arc::new(ByteBoolMetadata {
+            validity: validity.to_metadata(length)?,
+        });
+
+        ArrayData::try_new(
```
Comment (robert3005) [inline encodings/byte_bool/src/compute/mod.rs:73]: You generally want to go through the typed constructor where possible. So you want a 
```try_new(buffer: Buffer, validity: Validity) -> Self``` and then rename existing `try_with_validity` to `from_vec`?

File: encodings/byte_bool/src/stats.rs [hunk 17]
```diff
@@ -0,0 +1,101 @@
...
+use super::ByteBoolArray;
+
+impl ArrayStatisticsCompute for ByteBoolArray {
+    fn compute_statistics(&self, stat: Stat) -> VortexResult<StatsSet> {
+        if self.is_empty() {
+            return Ok(StatsSet::new());
+        }
+
+        let bools = self.as_array_ref().clone().into_canonical()?.into_bool()?;
+        bools.compute_statistics(stat)
```
Comment (robert3005) [inline encodings/byte_bool/src/stats.rs:17]: note for future this could be optimized to avoid copy but for now this is enough

**Review by robert3005 — COMMENTED** [review]
Only note about changing constructor though could be convinced that we should keep it as is

File: encodings/byte_bool/src/compute/mod.rs (hunk 16 above)
Comment (AdamGS) [reply encodings/byte_bool/src/compute/mod.rs:73]: That makes sense, introduced `try_new` and renamed to `try_from_vec`

File: encodings/byte_bool/src/stats.rs (hunk 17 above)
Comment (AdamGS) [reply encodings/byte_bool/src/stats.rs:17]: added a TODO comment

**Review by robert3005 — APPROVED** [review]

**Comment by AdamGS** [comment]
~~Seems like one of my recent changes broke tests, looking into~~ Fixed

**Review by robert3005 — APPROVED** [review]
