### PR TITLE
Fix empty zctl flag

### LINKED ISSUE #6882: Fuzzing Crash: AssertionFailed in array_ops
### Analysis

**Crash Location**: `vortex-array/src/arrays/listview/conversion.rs:112:list_from_list_view`

**Error Message**:
```
assertion failed: zctl_array.is_zero_copy_to_list()
```

<details>
<summary>Stack Trace</summary>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/panicking.rs:80:14
   2: core::panicking::panic
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/panicking.rs:150:5
   3: list_from_list_view
             at ./vortex-array/src/arrays/listview/conversion.rs:112:5
   4: compress_canonical
             at ./vortex-btrblocks/src/canonical_compressor.rs:250:38
   5: compress
             at ./vortex-btrblocks/src/canonical_compressor.rs:128:14
   6: compress_array
             at ./fuzz/src/array/mod.rs:528:14
   7: run_fuzz_action
             at ./fuzz/src/array/mod.rs:577:33
   8: __libfuzzer_sys_run
             at ./fuzz/fuzz_targets/array_ops.rs:18:11
   9: rust_fuzzer_test_input
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/src/lib.rs:363:60
  10: {closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/src/lib.rs:62:9
  11: do_call<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:581:40
  12: __rust_try
  13: catch_unwind<i32, libfuzzer_sys::test_input_wrap::{closure_env#0}>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:544:19
  14: catch_unwind<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panic.rs:359:14
  15: test_input_wrap
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/src/lib.rs:60:22
  16: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/libfuzzer/FuzzerLoop.cpp:619:13
  17: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEbPb
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/libfuzzer/FuzzerLoop.cpp:516:7
  18: _ZN6fuzzer6Fuzzer16MutateAndTestOneEv
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/libfuzzer/FuzzerLoop.cpp:765:19
  19: _ZN6fuzzer6Fuzzer4LoopERSt6vectorINS_9SizedFileESaIS2_EE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/libfuzzer/FuzzerLoop.cpp:910:5
   ... (7 more frames truncated)
```
</details>

### Root Cause Analysis

The crash is an assertion failure at vortex-array/src/arrays/listview/conversion.rs:112 where a debug_assert checks that a ListViewArray is zero-copy convertible to a ListArray after calling rebuild(MakeExact), but the rebuilt array's is_zero_copy_to_list flag is false. The root cause is that the rebuild(MakeExact) method fails to produce a zero-copy-compatible ListViewArray for certain edge cases, specifically when the input is a zero-length ListViewArray with AllInvalid validity, empty offsets/sizes buffers, and VarBinViewArray elements — the rebuild logic likely does not correctly handle this degenerate case and returns an array that still fails the zero-copy check. The fix should either make rebuild(MakeExact) correctly handle empty/all-null ListViewArrays (ensuring the output satisfies is_zero_copy_to_list), or convert the debug_assert into a proper error that falls back to the expensive rebuild path when the invariant is not met.

### Summary

- **Target**: `array_ops`
- **Crash File**: `crash-5e731d9863141e25ff290d8ba98fa5c285bdf012`
- **Branch**: develop
- **Commit**: bf6303dfec0005e5c8e25feab991b6669654daee
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/22952093470/artifacts/5870884170

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/22952093470/artifacts/5870884170
   - Extract the zip file

2. Reproduce locally:
```bash
cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-5e731d9863141e25ff290d8ba98fa5c285bdf012 -- -rss_limit_mb=0
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-5e731d9863141e25ff290d8ba98fa5c285bdf012 -- -rss_limit_mb=0
```

---
*Auto-created by fuzzing workflow*

### PR DESCRIPTION
**Pull request by connortsui20**
## Summary

Closes: https://github.com/vortex-data/vortex/issues/6882

Didn't set the ZCTL flag for empty list view arrays after rebuilding. This can happen when we slice off everything.

Maybe we want to add checks on slice where if we slice into an empty array we add the flag? Rebuild is probably sufficient though.

## Testing

Added a regression test.

### CODE REVIEW

File: vortex-array/src/canonical.rs [hunk 1]
```diff
@@ -206,6 +206,7 @@ impl Canonical {
                         .into_array(),
                     Validity::from(n),
                 )
+                // An empty list view is trivially copyable to a list.
```
Comment (joseph-isaacs) [inline vortex-array/src/canonical.rs:209]: safety?

**Review by joseph-isaacs — APPROVED** [review]

File: vortex-array/src/canonical.rs (hunk 1 above)
Comment (connortsui20) [reply vortex-array/src/canonical.rs:209]: Yeah that would be nice, but really it should be on every unsafe comment in that file
