### PR TITLE
Fix alp null handling

### LINKED ISSUE #621: ALP compressor outputs an array that `scalar` says is null in a specific index but actually has a value in the original data
This error is a result of fuzzing, the assert failure message is:
```
-0.12401960784313724 != null at index 0, lhs is vortex.primitive(0x03) rhs is vortex.alp(0x0d)
```
crash artifact is attached to help with reproduction: [crash.zip](https://github.com/user-attachments/files/16614002/crash.zip)

### PR DESCRIPTION
**Pull request by AdamGS**
Closes #621

### CODE REVIEW

File: encodings/alp/src/compute.rs [hunk 1]
```diff
@@ -22,11 +22,26 @@ impl ArrayCompute for ALPArray {
...
+        {
             return Ok(patch);
         }
+
         let encoded_val = scalar_at(&self.encoded(), index)?;
+
         match_each_alp_float_ptype!(self.ptype(), |$T| {
+            // If we have a null value, no need to decode it
+            if !encoded_val.is_valid() {
+                return Ok(Scalar::null(<$T as ALPFloat>::dtype()));
```
Comment (robert3005) [inline encodings/alp/src/compute.rs]: `DType::from(<$T>::PTYPE).as_nullable()`

**Review by robert3005 — APPROVED** [review]
