### PR TITLE
fix: Fix shr overflow in FoR compare

### LINKED ISSUE #2175: Running clickbench in `dev` profiles results in a panic
`attempt to shift right with overflow` coming from FoR compare.

run command is:
```bash
cargo run --bin clickbench --profile dev -- -i 1 -q 1
```

```
   6: vortex_fastlanes::for::compute::compare::compare_constant
             at ./encodings/fastlanes/src/for/compute/compare.rs:52:15
   7: vortex_fastlanes::for::compute::compare::<impl vortex_array::compute::compare::CompareFn<vortex_fastlanes::for::FoRArray> for vortex_fastlanes::for::FoREncoding>::compare
             at ./encodings/fastlanes/src/for/compute/compare.rs:22:17
   8: <E as vortex_array::compute::compare::CompareFn<vortex_array::data::Array>>::compare
             at ./vortex-array/src/compute/compare.rs:86:9
   9: vortex_array::compute::compare::compare::{{closure}}
```
the stack trace is really big, this seems to be the relevant part.

### PR DESCRIPTION
**Pull request by AdamGS**
closes #2175

### CODE REVIEW

File: encodings/fastlanes/src/for/compute/compare.rs [hunk 1]
```diff
@@ -53,10 +51,13 @@ where
         if let Some(reference) = reference {
             rhs = rhs.wrapping_sub(&reference);
         }
-        if lhs.shift() > 0 {
-            // Since compare requires that both sides are of same dtype this will always succeed and not panic
-            rhs = rhs >> (lhs.shift() as u32)
-        }
+        // Since compare requires that both sides are of same dtype this will always succeed and not panic
```
Comment (robert3005) [inline encodings/fastlanes/src/for/compute/compare.rs]: This comment is wrong now? The issue is that the sub is wrapping so it will succeed and produce 0 instead of skipping the comparison. Would it be simpler to detect this case and short circuit?

Comment (robert3005) [reply encodings/fastlanes/src/for/compute/compare.rs]: IE it only happens for values < reference?

File: encodings/fastlanes/src/for/compute/compare.rs [hunk 2]
```diff
@@ -53,10 +51,15 @@ where
...
+
+        let zero = T::zero();
+        let rhs = match rhs.checked_shr(lhs.shift() as u32) {
```
Comment (gatesn) [inline encodings/fastlanes/src/for/compute/compare.rs]: Can we just use `if lhs.shift() == T::bit_width() { if rhs == T::zero() { ... } else { vortex_panic() }` and handle the case explicitly?

**Comment by AdamGS** [comment]
I think this is a reasonable fix, with less if/match/branches.

File: encodings/fastlanes/src/for/compute/compare.rs [hunk 3]
```diff
@@ -53,11 +51,12 @@ where
         if let Some(reference) = reference {
             rhs = rhs.wrapping_sub(&reference);
         }
-        if lhs.shift() > 0 {
-            // Since compare requires that both sides are of same dtype this will always succeed and not panic
-            rhs = rhs >> (lhs.shift() as u32)
-        }
-        rhs
+
+        let bit_width = (size_of::<T>() * 8) as u32;
```
Comment (gatesn) [inline encodings/fastlanes/src/for/compute/compare.rs]: T::bit_width()

File: encodings/fastlanes/src/for/compute/compare.rs [hunk 4]
```diff
@@ -35,7 +33,7 @@ fn compare_constant<T>(
     operator: Operator,
 ) -> VortexResult<Option<Array>>
 where
-    T: NativePType + Shr<u32, Output = T> + WrappingSub,
+    T: NativePType + WrappingSub + CheckedShr<Output = T>,
```
Comment (robert3005) [inline encodings/fastlanes/src/for/compute/compare.rs]: you no longer use checkedshr just shr

**Review by gatesn — APPROVED** [review]
