### PR TITLE
fix: Implement compact for ListArray

### LINKED ISSUE #3640: issue: vortex file is too large than parquet
After I convert parquet file to vortex file, I find that vortex file is too large than I expected.
```
2019809413   seq.parquet
9463239652   seq.vortex
```

I extract one column which type is struct<struct<list<int64>>>, and this issue can be reproduced, but the compressed vortex array size is **157182932**, a little bit bigger than parquet.
```
150732338  single_column_multigroups.parquet
628437016  single_column_multigroups.vortex
```

If I slice first 1000 line, the file size is very close.
```
6315041  single_column_1000.parquet
6577728  single_column_1000.vortex
```

I just follow [quick start](https://docs.vortex.dev/quickstart/python) to do these things.

I have uploaded test file to google drive - https://drive.google.com/file/d/1Fuk7KUO9PHJzbsmOsGJw2UpzztHeCDU4/view?usp=sharing , and its md5 is e8adb6e279c6a3cfbd2845c5370da869.

### PR DESCRIPTION
**Pull request by robert3005**
fix #3640

### CODE REVIEW

File: vortex-array/src/arrays/varbinview/compact.rs [hunk 1]
```diff
@@ -11,68 +11,67 @@ use crate::builders::{ArrayBuilder, VarBinViewBuilder};
...
-    }
+impl VarBinViewArray {
+    /// Returns a compacted copy of the input array, where all wasted space has been cleaned up. This
+    /// operation can be very expensive, in the worst cast copying all existing string data into
+    /// a new allocation.
+    ///
+    /// After slicing/taking operations `VarBinViewArray`s can continue to hold references to buffers
+    /// that are no longer visible. We detect when there is wasted space in any of the buffers, and if
+    /// so, will aggressively compact all visile outlined string data into a single new buffer.
+    pub fn compact_buffers(&self) -> VortexResult<VarBinViewArray> {
```
Comment (robert3005) [inline vortex-array/src/arrays/varbinview/compact.rs:22]: I have arbitrarily made some functions here memeber functions of the array

File: vortex-array/src/arrays/list/mod.rs [hunk 2]
```diff
@@ -100,40 +101,58 @@ impl ListArray {
...
     }
 
-    // TODO: fetches the elements of the array ignoring validity
+    /// Returns the elements array.
     pub fn elements(&self) -> &ArrayRef {
         &self.elements
     }
+
+    /// Create a copy of this array by adjusting offsets to start at 0 and removing elements not referenced by the offsets
+    pub fn offset_to_0(&self) -> VortexResult<Self> {
```
Comment (robert3005) [inline vortex-array/src/arrays/list/mod.rs]: not convinced by the name. In the end though its changing starting offset to 0 is why you need to prune elements

File: vortex-array/src/arrays/list/mod.rs [hunk 3]
```diff
@@ -100,40 +101,58 @@ impl ListArray {
         })
     }
 
-    // TODO: merge logic with varbin
-    // TODO(ngates): should return a result if it requires canonicalizing offsets
-    pub fn offset_at(&self, index: usize) -> usize {
```
Comment (a10y) [inline vortex-array/src/arrays/list/mod.rs]: this feels like a weird use of result

File: vortex-array/src/arrays/list/mod.rs (hunk 2 above)
Comment (a10y) [reply vortex-array/src/arrays/list/mod.rs]: I'd call this `reset_offsets()`

**Comment by a10y** [comment]
Does rezeroing the offsets actually do anything to reduce the space usage?

**Comment by a10y** [comment]
Ah yea, in the case of list it does, elements is left intact and offsets are sliced

File: vortex-array/src/arrays/list/mod.rs [hunk 4]
```diff
@@ -346,4 +367,66 @@ mod test {
...
+                    Arc::new(I32.into()),
+                    vec![4.into(), 5.into(), 6.into()],
+                    Nullability::NonNullable,
+                )
+                .as_list(),
+            )
+            .vortex_unwrap();
+        builder
+            .append_value(
+                Scalar::list(
```
Comment (a10y) [inline vortex-array/src/arrays/list/mod.rs:403]: We could probably change Scalar::list to take an `Into<Arc<DType>>` instead of `Arc<DType>`

**Comment by a10y** [comment]
The top-level BtrBlocksCompressor::compress function is only called once per column in the write path, so we might want to recursively compact the List array? Same for StructArray actually for when we write nested structs

**Comment by robert3005** [comment]
In order to prune the elements you need to rewrite offsets

File: vortex-array/src/arrays/list/mod.rs (hunk 3 above)
Comment (robert3005) [reply vortex-array/src/arrays/list/mod.rs]: Indeed, we moved the varbin to return result so I made this match. Can swap both tbh

File: vortex-array/src/arrays/list/mod.rs [hunk 5]
```diff
@@ -100,40 +101,64 @@ impl ListArray {
...
     }
 
-    // TODO: merge logic with varbin
-    // TODO(ngates): should return a result if it requires canonicalizing offsets
+    /// Returns the offset at the given index from the list array.
+    ///
+    /// Panics if the index is out of bounds.
     pub fn offset_at(&self, index: usize) -> usize {
+        assert!(
+            index < self.len() + 1,
```
Comment (a10y) [inline vortex-array/src/arrays/list/mod.rs]: Could you make these <= Len? Len+1 looks fishy

**Review by a10y — APPROVED** [review]
