### PR TITLE
fix: make PrimitiveArray cast properly handle validity/nullability

### LINKED ISSUE #260: PrimitiveArray cast to respect nullability

### PR DESCRIPTION
**Pull request by lwwmanning**
fixes #260

### CODE REVIEW

File: vortex-array/src/array/primitive/compute/cast.rs [hunk 1]
```diff
@@ -8,23 +8,37 @@ use crate::{Array, ArrayDType, IntoArray};
...
-
-        // Short-cut if we can just change the nullability
-        if self.ptype() == ptype && !self.dtype().is_nullable() && dtype.is_nullable() {
-            return Ok(PrimitiveArray::new(
-                self.buffer().clone(),
-                self.ptype(),
-                Validity::AllValid,
-            )
-            .into_array());
+        let DType::Primitive(new_ptype, new_nullability) = dtype.clone() else {
```
Comment (robert3005) [inline vortex-array/src/array/primitive/compute/cast.rs:11]: genuinely no clue how this gets compiled down but given nullability and ptype are copy I would drop the clone here

**Review by robert3005 — COMMENTED** [review]
Just the one comment about weird use of clone

**Review by a10y — APPROVED** [review]
Modulo Rob's comment LGTM

File: vortex-array/src/array/primitive/compute/cast.rs (hunk 1 above)
Comment (lwwmanning) [reply vortex-array/src/array/primitive/compute/cast.rs:11]: they are, but DType is clone, not copy... so to have owned PType/Nullability from the destructuring (instead of a ref) requires cloning the dtype

Comment (robert3005) [reply vortex-array/src/array/primitive/compute/cast.rs:11]: But you can copy them after you got the borrowed value

Comment (robert3005) [reply vortex-array/src/array/primitive/compute/cast.rs:11]: this https://github.com/spiraldb/vortex/pull/972
