### PR TITLE
fix handling of fill_null precondition cast

### LINKED ISSUE #6496: Fuzzing Crash: VortexError in array_ops
### Analysis

**Crash Location**: `vortex-array/src/arrays/scalar_fn/vtable/mod.rs:148:execute`

**Error Message**:
```
to_canonical should succeed in fuzz test:
  Scalar function vortex.fill_null() returned another ScalarFnArray with all columnar inputs, a concrete array was expected
```

<details>
<summary>Stack Trace</summary>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/panicking.rs:80:14
   2: panic_display<vortex_error::VortexError>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/panicking.rs:259:5
   3: {closure#1}<vortex_array::canonical::Canonical, vortex_error::VortexError>
             at ./vortex-error/src/lib.rs:457:9
   4: unwrap_or_else<vortex_array::canonical::Canonical, vortex_error::VortexError, vortex_error::{impl#11}::vortex_expect::{closure_env#1}<vortex_array::canonical::Canonical, vortex_error::VortexError>>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/result.rs:1622:23
   5: vortex_expect<vortex_array::canonical::Canonical, vortex_error::VortexError>
             at ./vortex-error/src/lib.rs:310:14
   6: run_fuzz_action
             at ./fuzz/src/array/mod.rs:567:22
   7: __libfuzzer_sys_run
             at ./fuzz/fuzz_targets/array_ops.rs:14:11
   8: rust_fuzzer_test_input
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:363:60
   9: {closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:62:9
  10: do_call<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:581:40
  11: __rust_try
  12: catch_unwind<i32, libfuzzer_sys::test_input_wrap::{closure_env#0}>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:544:19
  13: catch_unwind<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panic.rs:359:14
  14: test_input_wrap
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/src/lib.rs:60:22
  15: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:619:13
  16: _ZN6fuzzer6Fuzzer6RunOneEPKhmbPNS_9InputInfoEbPb
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:516:7
  17: _ZN6fuzzer6Fuzzer25ReadAndExecuteSeedCorporaERSt6vectorINS_9SizedFileESaIS2_EE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:834:7
  18: _ZN6fuzzer6Fuzzer4LoopERSt6vectorINS_9SizedFileESaIS2_EE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerLoop.cpp:872:3
  19: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.10/libfuzzer/FuzzerDriver.cpp:915:6
   ... (5 more frames truncated)
```
</details>

### Root Cause Analysis

The crash occurs at vortex-array/src/arrays/scalar_fn/vtable/mod.rs:148 where the fill_null scalar function returns another ScalarFnArray instead of a concrete (materialized) array, even though all of its inputs are already columnar (AnyColumnar). This happens because the fill_null implementation for ChunkedArray with empty Decimal chunks (precision 41, scale -20, length 0) fails to fully resolve into a concrete DecimalArray and instead wraps the result in another lazy ScalarFnArray. The fix should ensure that the fill_null scalar function's execute method produces a concrete array when given fully materialized columnar inputs, likely by adding a canonicalize or to_canonical call on the result within the fill_null implementation before returning.

### Summary

- **Target**: `array_ops`
- **Crash File**: `crash-a0690a150dda810c510451c6297a036a7de6d9d0`
- **Branch**: develop
- **Commit**: ab6d2eba9ac6fbcbca57ef50ef699c37b17ca72f
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/21994901469/artifacts/5502607937

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/21994901469/artifacts/5502607937
   - Extract the zip file

2. Reproduce locally:
```bash
cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-a0690a150dda810c510451c6297a036a7de6d9d0 -- -rss_limit_mb=0
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-a0690a150dda810c510451c6297a036a7de6d9d0 -- -rss_limit_mb=0
```

---
*Auto-created by fuzzing workflow*

### PR DESCRIPTION
**Pull request by a10y**
## Does this PR closes an open issue or discussion?

Closes #6496

## What changes are included in this PR?

fill_null scalar fn execution will execute() its precondition result. In this case, the precondition was returning an unexecuted `CastArray` which breaks the assumption that ScalarFn::execute() always makes forward progress toward `Columnar`

### CODE REVIEW

**Review by robert3005 — APPROVED** [review]

File: vortex-array/src/expr/exprs/fill_null/mod.rs [hunk 1]
```diff
@@ -157,7 +157,9 @@ fn fill_null_canonical(
     ctx: &mut ExecutionCtx,
 ) -> VortexResult<ArrayRef> {
     if let Some(result) = precondition(canonical.as_ref(), fill_value)? {
-        return Ok(result);
+        // The result of precondition may return another ScalarFn, in which case we should
+        // apply it immediately.
+        return result.execute::<ArrayRef>(ctx);
```
Comment (joseph-isaacs) [inline vortex-array/src/expr/exprs/fill_null/mod.rs:162]: do an optimize first?

Comment (joseph-isaacs) [reply vortex-array/src/expr/exprs/fill_null/mod.rs:162]: also can we add a BIG todo to remove this once we have a better driver check?
