### PR TITLE
Fix: arrow struct comparison

### LINKED ISSUE #5947: Fuzzing Crash: Arrow Struct comparison not supported in filter expressions
### Analysis

**Crash Location**: `vortex-array/src/expr/exprs/binary.rs:153`

**Error Message**:
```
Invalid argument error: Nested comparison: Struct("0": Float32, "1": Boolean) == Struct("0": Float32, "1": Boolean) (hint: use make_comparator instead)
```

**Stack Trace**:
```
   0: std::backtrace_rs::backtrace::libunwind::trace
   1: std::backtrace_rs::backtrace::trace_unsynchronized
   2: <std::backtrace::Backtrace>::create
   3: from
             at ./vortex-error/src/lib.rs:473:49
   4: from_residual
             at /rustc/2f1bd3f3781c90a8447e37d65a898442b8618895/library/core/src/result.rs:2189:27
   5: execute
             at ./vortex-array/src/expr/exprs/binary.rs:153:29
   6: execute
             at ./vortex-array/src/expr/vtable.rs:481:22
   7: execute
             at ./vortex-array/src/expr/scalar_fn.rs:126:30
```

**Root Cause**: The fuzzer generated a filter expression that attempts to compare two struct-typed fields using the equality operator (`Operator::Eq`). The code path is:

1. Filter expression with `Eq` operator comparing struct fields
2. Binary expression execution at `binary.rs:153` calls `cmp::eq(lhs, rhs)`
3. This invokes `arrow_compare` for nested types at `compare.rs:332-343`
4. Arrow's `make_comparator` doesn't support direct struct comparison and returns an error

The error originates from Apache Arrow, which requires using `make_comparator` differently for nested types. However, the current implementation assumes `make_comparator` will work for all nested types, but it explicitly doesn't support struct comparisons.

**Possible Fix**: The code needs to either:
- Implement custom struct comparison logic (field-by-field comparison)
- Detect struct types and provide a better error message
- Use a different comparison strategy for structs (e.g., comparing fields individually and combining results)

<details>
<summary>Debug Output</summary>

```
FuzzFileAction {
    array: StructArray {
        len: 1,
        dtype: Struct(
            StructFields {
                names: FieldNames(
                    [
                        FieldName(
                            "",
                        ),
                    ],
                ),
                dtypes: [
                    FieldDType {
                        inner: Owned(
                            Struct(
                                StructFields {
                                    names: FieldNames(
                                        [
                                            FieldName(
                                                "}}4\n",
                                            ),
                                            FieldName(
                                                "",
                                            ),
                                        ],
                                    ),
                                    dtypes: [
                                        FieldDType {
                                            inner: Owned(
                                                Primitive(
                                                    F32,
                                                    NonNullable,
                                                ),
                                            ),
                                        },
                                        FieldDType {
                                            inner: Owned(
                                                Bool(
                                                    NonNullable,
                                                ),
                                            ),
                                        },
                                    ],
                                },
                                NonNullable,
                            ),
                        ),
                    },
                ],
            },
            NonNullable,
        ),
        fields: [
            StructArray {
                len: 1,
                dtype: Struct(
                    StructFields {
                        names: FieldNames(
                            [
                                FieldName(
                                    "}}4\n",
                                ),
                                FieldName(
                                    "",
                                ),
                            ],
                        ),
                        dtypes: [
                            FieldDType {
                                inner: Owned(
                                    Primitive(
                                        F32,
                                        NonNullable,
                                    ),
                                ),
                            },
                            FieldDType {
                                inner: Owned(
                                    Bool(
                                        NonNullable,
                                    ),
                                ),
                            },
                        ],
                    },
                    NonNullable,
                ),
                fields: [
                    ChunkedArray {
                        dtype: Primitive(
                            F32,
                            NonNullable,
                        ),
                        len: 1,
                        chunk_offsets: PrimitiveArray {
                            dtype: Primitive(
                                U64,
                                NonNullable,
                            ),
                            buffer: Buffer<u8> {
                                length: 24,
                                alignment: Alignment(
                                    8,
                                ),
                                as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...],
                            },
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [],
                                    },
                                },
                            },
                        },
                        chunks: [
                            PrimitiveArray {
                                dtype: Primitive(
                                    F32,
                                    NonNullable,
                                ),
                                buffer: Buffer<u8> {
                                    length: 4,
                                    alignment: Alignment(
                                        4,
                                    ),
                                    as_slice: [1, 125, 5, 112],
                                },
                                validity: NonNullable,
                                stats_set: ArrayStats {
                                    inner: RwLock {
                                        data: StatsSet {
                                            values: [],
                                        },
                                    },
                                },
                            },
                            PrimitiveArray {
                                dtype: Primitive(
                                    F32,
                                    NonNullable,
                                ),
                                buffer: Buffer<u8> {
                                    length: 0,
                                    alignment: Alignment(
                                        4,
                                    ),
                                    as_slice: [],
                                },
                                validity: NonNullable,
                                stats_set: ArrayStats {
                                    inner: RwLock {
                                        data: StatsSet {
                                            values: [],
                                        },
                                    },
                                },
                            },
                        ],
                        stats_set: ArrayStats {
                            inner: RwLock {
                                data: StatsSet {
                                    values: [],
                                },
                            },
                        },
                    },
                    ChunkedArray {
                        dtype: Bool(
                            NonNullable,
                        ),
                        len: 1,
                        chunk_offsets: PrimitiveArray {
                            dtype: Primitive(
                                U64,
                                NonNullable,
                            ),
                            buffer: Buffer<u8> {
                                length: 32,
                                alignment: Alignment(
                                    8,
                                ),
                                as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                            },
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [],
                                    },
                                },
                            },
                        },
                        chunks: [
                            BoolArray {
                                dtype: Bool(
                                    NonNullable,
                                ),
                                bits: BitBuffer {
                                    buffer: Buffer<u8> {
                                        length: 0,
                                        alignment: Alignment(
                                            1,
                                        ),
                                        as_slice: [],
                                    },
                                    offset: 0,
                                    len: 0,
                                },
                                validity: NonNullable,
                                stats_set: ArrayStats {
                                    inner: RwLock {
                                        data: StatsSet {
                                            values: [],
                                        },
                                    },
                                },
                            },
                            BoolArray {
                                dtype: Bool(
                                    NonNullable,
                                ),
                                bits: BitBuffer {
                                    buffer: Buffer<u8> {
                                        length: 0,
                                        alignment: Alignment(
                                            1,
                                        ),
                                        as_slice: [],
                                    },
                                    offset: 0,
                                    len: 0,
                                },
                                validity: NonNullable,
                                stats_set: ArrayStats {
                                    inner: RwLock {
                                        data: StatsSet {
                                            values: [],
                                        },
                                    },
                                },
                            },
                            BoolArray {
                                dtype: Bool(
                                    NonNullable,
                                ),
                                bits: BitBuffer {
                                    buffer: Buffer<u8> {
                                        length: 1,
                                        alignment: Alignment(
                                            1,
                                        ),
                                        as_slice: [1],
                                    },
                                    offset: 0,
                                    len: 1,
                                },
                                validity: NonNullable,
                                stats_set: ArrayStats {
                                    inner: RwLock {
                                        data: StatsSet {
                                            values: [],
                                        },
                                    },
                                },
                            },
                        ],
                        stats_set: ArrayStats {
                            inner: RwLock {
                                data: StatsSet {
                                    values: [],
                                },
                            },
                        },
                    },
                ],
                validity: NonNullable,
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
        ],
        validity: NonNullable,
        stats_set: ArrayStats {
            inner: RwLock {
                data: StatsSet {
                    values: [],
                },
            },
        },
    },
    projection_expr: Some(
        Expression {
            scalar_fn: BoundExpression {
                vtable: vortex.pack,
                options: PackOptions {
                    names: FieldNames(
                        [
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                            FieldName(
                                "",
                            ),
                        ],
                    ),
                    nullability: Nullable,
                },
            },
            children: [
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.get_item,
                        options: FieldName(
                            "",
                        ),
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.root,
                                options: EmptyOptions,
                            },
                            children: [],
                        },
                    ],
                },
            ],
        },
    ),
    filter_expr: Some(
        Expression {
            scalar_fn: BoundExpression {
                vtable: vortex.binary,
                options: And,
            },
            children: [
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.binary,
                        options: Eq,
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.get_item,
                                options: FieldName(
                                    "",
                                ),
                            },
                            children: [
                                Expression {
                                    scalar_fn: BoundExpression {
                                        vtable: vortex.root,
                                        options: EmptyOptions,
                                    },
                                    children: [],
                                },
                            ],
                        },
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.literal,
                                options: Scalar {
                                    dtype: Struct(
                                        StructFields {
                                            names: FieldNames(
                                                [
                                                    FieldName(
                                                        "}}4\n",
                                                    ),
                                                    FieldName(
                                                        "",
                                                    ),
                                                ],
                                            ),
                                            dtypes: [
                                                FieldDType {
                                                    inner: Owned(
                                                        Primitive(
                                                            F32,
                                                            NonNullable,
                                                        ),
                                                    ),
                                                },
                                                FieldDType {
                                                    inner: Owned(
                                                        Bool(
                                                            NonNullable,
                                                        ),
                                                    ),
                                                },
                                            ],
                                        },
                                        NonNullable,
                                    ),
                                    value: ScalarValue(
                                        List(
                                            [
                                                ScalarValue(
                                                    Primitive(
                                                        F32(
                                                            0.01148897,
                                                        ),
                                                    ),
                                                ),
                                                ScalarValue(
                                                    Bool(
                                                        false,
                                                    ),
                                                ),
                                            ],
                                        ),
                                    ),
                                },
                            },
                            children: [],
                        },
                    ],
                },
                Expression {
                    scalar_fn: BoundExpression {
                        vtable: vortex.binary,
                        options: Gte,
                    },
                    children: [
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.get_item,
                                options: FieldName(
                                    "",
                                ),
                            },
                            children: [
                                Expression {
                                    scalar_fn: BoundExpression {
                                        vtable: vortex.root,
                                        options: EmptyOptions,
                                    },
                                    children: [],
                                },
                            ],
                        },
                        Expression {
                            scalar_fn: BoundExpression {
                                vtable: vortex.literal,
                                options: Scalar {
                                    dtype: Struct(
                                        StructFields {
                                            names: FieldNames(
                                                [
                                                    FieldName(
                                                        "}}4\n",
                                                    ),
                                                    FieldName(
                                                        "",
                                                    ),
                                                ],
                                            ),
                                            dtypes: [
                                                FieldDType {
                                                    inner: Owned(
                                                        Primitive(
                                                            F32,
                                                            NonNullable,
                                                        ),
                                                    ),
                                                },
                                                FieldDType {
                                                    inner: Owned(
                                                        Bool(
                                                            NonNullable,
                                                        ),
                                                    ),
                                                },
                                            ],
                                        },
                                        NonNullable,
                                    ),
                                    value: ScalarValue(
                                        List(
                                            [
                                                ScalarValue(
                                                    Primitive(
                                                        F32(
                                                            1.3096109e-35,
                                                        ),
                                                    ),
                                                ),
                                                ScalarValue(
                                                    Bool(
                                                        false,
                                                    ),
                                                ),
                                            ],
                                        ),
                                    ),
                                },
                            },
                            children: [],
                        },
                    ],
                },
            ],
        },
    ),
    compressor_strategy: Compact,
}
```
</details>

### Summary

- **Target**: `file_io`
- **Crash File**: `crash-f28bbf8290b4f456ae3b11d62c2f8bbc9ed8cd90`
- **Branch**: develop
- **Commit**: d757be1ef72230d10be059f551c6702846446024
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/20970890896/artifacts/5117906757

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/20970890896/artifacts/5117906757
   - Or find `io-fuzzing-crash-artifacts` at: https://github.com/vortex-data/vortex/actions/runs/20970890896
   - Extract the zip file

2. Reproduce locally:
```bash
# The artifact contains file_io/crash-f28bbf8290b4f456ae3b11d62c2f8bbc9ed8cd90
cargo +nightly fuzz run -D --sanitizer=none file_io file_io/crash-f28bbf8290b4f456ae3b11d62c2f8bbc9ed8cd90 -- -rss_limit_mb=0
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run -D --sanitizer=none file_io file_io/crash-f28bbf8290b4f456ae3b11d62c2f8bbc9ed8cd90 -- -rss_limit_mb=0
```

---
*Auto-created by fuzzing workflow with Claude analysis*

### PR DESCRIPTION
**Pull request by connortsui20**
Fixes: https://github.com/vortex-data/vortex/issues/5947

Adds support for comparing struct arrays via Arrow. The existing code uses the vectorized comparisons which are not implemented for the nested types. This adds that in as well as documents the Arrow behavior more explicitly.

Also adds a regression test similar to the fuzzer crash.

### CODE REVIEW

File: vortex-array/src/compute/compare.rs [hunk 1]
```diff
@@ -319,6 +319,38 @@ where
...
+    lhs: &dyn arrow_array::Array,
+    rhs: &dyn arrow_array::Array,
+    operator: Operator,
+) -> VortexResult<BooleanArray> {
+    let cmp = make_comparator(lhs, rhs, SortOptions::default())?;
+
+    let values = (0..lhs.len())
+        .map(|i| {
+            let cmp_result = cmp(i, i);
+            match operator {
```
Comment (a10y) [inline vortex-array/src/compute/compare.rs:339]: can we pull this out of the map?

**Review by a10y — APPROVED** [review]

**Comment by connortsui20** [comment]
whoops it was auto merged, follow up soon

**Comment by connortsui20** [comment]
https://github.com/vortex-data/vortex/pull/5985
