### PR TITLE
fix[vortex-array]: check NaN for inferring is constant with min/max

### LINKED ISSUE #3660: The internal mutability of stats set leak between array/is very confusing
Consider 

```
    let array_data = ChunkedArray::from_iter([
        PrimitiveArray::from_iter([f16::ONE, f16::NAN]).to_array(),
        PrimitiveArray::from_iter([f16::ZERO]).to_array(),
    ])
    .to_array();
    let expected_array = array_data.clone();

    println!(
        "before write {:?}, children {}",
        expected_array.statistics().get(IsConstant),
        expected_array
            .as_::<ChunkedVTable>()
            .chunks()
            .iter()
            .map(|c| format!("{:?}", c.statistics().get(IsConstant)))
            .join(",")
    );

    let _full_buff = VortexWriteOptions::default()
        .write(ByteBufferMut::empty(), array_data.to_array_stream())
        .await
        .vortex_unwrap();

    println!(
        "after write {:?}, children {}",
        expected_array.statistics().get(IsConstant),
        expected_array
            .as_::<ChunkedVTable>()
            .chunks()
            .iter()
            .map(|c| format!("{:?}", c.statistics().get(IsConstant)))
            .join(",")
    );
```

The output is 

```
before write None, children None,None
after write None, children Some(Exact(ScalarValue(Bool(true)))),Some(Exact(ScalarValue(Bool(true))))
```

### PR DESCRIPTION
**Pull request by joseph-isaacs**
I think that in the future min == max doesn't imply is constant for all types e.g. truncated str. I think we should reconsider this.

Closes https://github.com/vortex-data/vortex/issues/3660

### CODE REVIEW

File: vortex-array/src/compute/is_constant.rs [hunk 1]
```diff
@@ -136,17 +136,21 @@ fn is_constant_impl(
...
-        if min == max {
+        // min/max are equal and exact and there are no NaNs
+        if min.is_exact()
+            && min == max
+            && array
+                .dtype()
+                .is_float()
+                .then(|| {
+                    array.statistics().get_as::<u64>(Stat::NaNCount) == Some(Precision::exact(0u64))
+                })
```
Comment (AdamGS) [inline vortex-array/src/compute/is_constant.rs]: we already know the nan-count is 0 here

Comment (joseph-isaacs) [reply vortex-array/src/compute/is_constant.rs]: Well this fixes a bug

Comment (joseph-isaacs) [reply vortex-array/src/compute/is_constant.rs]: Where is that check?

Comment (AdamGS) [reply vortex-array/src/compute/is_constant.rs]: lines 126-136

Comment (joseph-isaacs) [reply vortex-array/src/compute/is_constant.rs]: Nans are valid

Comment (AdamGS) [reply vortex-array/src/compute/is_constant.rs]: oh those are float-nans, got it

File: vortex-array/src/compute/is_constant.rs [hunk 2]
```diff
@@ -136,17 +136,19 @@ fn is_constant_impl(
...
+    let min = array.statistics().get_scalar(Stat::Min, array.dtype());
+    let max = array.statistics().get_scalar(Stat::Max, array.dtype());
 
     if let Some((min, max)) = min.zip(max) {
-        if min == max {
+        // min/max are equal and exact and there are no NaNs
+        if min.is_exact()
+            && min == max
+            && if array.dtype().is_float() {
+                array.statistics().get_as::<u64>(Stat::NaNCount) == Some(Precision::exact(0u64))
```
Comment (robert3005) [inline vortex-array/src/compute/is_constant.rs]: nan_count(array)? == 0? You still have to compute the nan_count otherwise you might get a false positive still?

Comment (joseph-isaacs) [reply vortex-array/src/compute/is_constant.rs]: in what case if there is no stat this equality will not hold, so is constant will not be set

Comment (gatesn) [reply vortex-array/src/compute/is_constant.rs]: I think the question is: if you're this deep into the short-circuit call (min max are present, and equal), then you may as well perform actual nan_count compute instead of also requiring that stat to be pre-computed.

Comment (robert3005) [reply vortex-array/src/compute/is_constant.rs]: I think the overall thing is that it's faster to fallback to is_constant than doing nan_count here. Is there a nicer way of expressing this than an if withing an if condition?

Comment (joseph-isaacs) [reply vortex-array/src/compute/is_constant.rs]: Is there something you want to change here? 

By all means push a small change it you want so we can merge

**Review by robert3005 — APPROVED** [review]
