### PR TITLE
fix[vortex-dict]: avoid full materialization in min_max

### LINKED ISSUE #5121: panic: attempt to add with overflow while computing stats for VarBin
### Describe the bug

This happens when merging two files on both our fork (0.53.0 + cherry picks) and 797160dc9d7633d18d87f8ef50ce642ecd1f3964. The panic itself seems to be an overflow in the Take operation, which seems unexpected.

```
thread 'bisect_opt::tests::test_minimal_repro' panicked at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/arrays/varbin/compute/take.rs:70:9:
attempt to add with overflow
stack backtrace:
   0:        0x104efc8dc - std::backtrace_rs::backtrace::libunwind::trace::h674dcd02776dcc9c
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/../../backtrace/src/backtrace/libunwind.rs:117:9
   1:        0x104efc8dc - std::backtrace_rs::backtrace::trace_unsynchronized::haccaae8fb80e4531
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/../../backtrace/src/backtrace/mod.rs:66:14
   2:        0x104efc8dc - std::sys::backtrace::_print_fmt::h3191fc6495b0a516
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:66:9
   3:        0x104efc8dc - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h373e57e2286956dc
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:39:26
   4:        0x104f181e4 - core::fmt::rt::Argument::fmt::hcee930b009d69e38
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/fmt/rt.rs:173:76
   5:        0x104f181e4 - core::fmt::write::h2c4a0b98b09e3b30
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/fmt/mod.rs:1465:25
   6:        0x104ef9d64 - std::io::default_write_fmt::h1b8f25d7cf9c86a4
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/io/mod.rs:639:11
   7:        0x104ef9d64 - std::io::Write::write_fmt::h00b4007fff731b84
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/io/mod.rs:1954:13
   8:        0x104efc790 - std::sys::backtrace::BacktraceLock::print::h3eb1535b8d3666ca
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:42:9
   9:        0x104efde18 - std::panicking::default_hook::{{closure}}::hf623c44b740b115f
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:300:27
  10:        0x104efdc68 - std::panicking::default_hook::h8875fb31ec87dfad
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:327:9
  11:        0x104efe8a0 - std::panicking::rust_panic_with_hook::hdd8ceeeb04975c2b
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:833:13
  12:        0x104efe4ac - std::panicking::begin_panic_handler::{{closure}}::hdf417b72ab8ffff8
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:699:13
  13:        0x104efcd88 - std::sys::backtrace::__rust_end_short_backtrace::h507d79c50996742e
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:168:18
  14:        0x104efe1b0 - __rustc[5224e6b81cd82a8f]::rust_begin_unwind
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:697:5
  15:        0x104fa1a40 - core::panicking::panic_fmt::h3505bfbec5a0b799
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:75:14
  16:        0x104fa1fd4 - core::panicking::panic_const::panic_const_add_overflow::h742455be0b74543c
                               at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:175:17
  17:        0x1041f0f9c - <u16 as core::ops::arith::AddAssign>::add_assign::hf8311ecec12541ee
                               at /Users/asubiotto/.rustup/toolchains/1.89-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/arith.rs:762:51
  18:        0x1041191a4 - vortex_array::arrays::varbin::compute::take::take::h2e5676da285a2c0d
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/arrays/varbin/compute/take.rs:70:9
  19:        0x10404e600 - vortex_array::arrays::varbin::compute::take::<impl vortex_array::compute::take::TakeKernel for vortex_array::arrays::varbin::vtable::VarBinVTable>::take::h7e5895dcd4b2543d
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/arrays/varbin/compute/take.rs:22:20
  20:        0x103cb11bc - <vortex_array::compute::take::TakeKernelAdapter<V> as vortex_array::compute::Kernel>::invoke::ha2f260b127bb94b5
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:227:17
  21:        0x103c2a1d0 - vortex_array::compute::take::take_impl::hf9ac51b834dac4eb
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:158:38
  22:        0x103c2982c - <vortex_array::compute::take::Take as vortex_array::compute::ComputeFnVTable>::invoke::hb4e984fa36e88253
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:78:27
  23:        0x103daf1c0 - vortex_array::compute::ComputeFn::invoke::hb8347e89d09ae3ae
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/mod.rs:144:34
  24:        0x103c295c8 - vortex_array::compute::take::take::h6da6f4d17589eff8
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:46:10
  25:        0x1025efdd0 - vortex_fsst::compute::<impl vortex_array::compute::take::TakeKernel for vortex_fsst::array::FSSTVTable>::take::hbff6c64a9a1a8717
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/encodings/fsst/src/compute/mod.rs:26:13
  26:        0x102608140 - <vortex_array::compute::take::TakeKernelAdapter<V> as vortex_array::compute::Kernel>::invoke::h1465c710e7352c88
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:227:17
  27:        0x103c2a1d0 - vortex_array::compute::take::take_impl::hf9ac51b834dac4eb
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:158:38
  28:        0x103c2982c - <vortex_array::compute::take::Take as vortex_array::compute::ComputeFnVTable>::invoke::hb4e984fa36e88253
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:78:27
  29:        0x103daf1c0 - vortex_array::compute::ComputeFn::invoke::hb8347e89d09ae3ae
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/mod.rs:144:34
  30:        0x103c295c8 - vortex_array::compute::take::take::h6da6f4d17589eff8
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/take.rs:46:10
  31:        0x1026bbc38 - vortex_dict::compute::min_max::<impl vortex_array::compute::min_max::MinMaxKernel for vortex_dict::array::DictVTable>::min_max::h8b9b2be632c2753a
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/encodings/dict/src/compute/min_max.rs:12:18
  32:        0x1026de8d4 - <vortex_array::compute::min_max::MinMaxKernelAdapter<V> as vortex_array::compute::Kernel>::invoke::hd61498d93ad608ef
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/min_max.rs:209:23
  33:        0x103fafd00 - vortex_array::compute::min_max::min_max_impl::h02cfe5c6f6d01734
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/min_max.rs:163:38
  34:        0x103faec78 - <vortex_array::compute::min_max::MinMax as vortex_array::compute::ComputeFnVTable>::invoke::h55982b74ef2a9de6
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/min_max.rs:80:15
  35:        0x103daf1c0 - vortex_array::compute::ComputeFn::invoke::hb8347e89d09ae3ae
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/mod.rs:144:34
  36:        0x103fae774 - vortex_array::compute::min_max::min_max::he10116a286a021a9
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/compute/min_max.rs:36:10
  37:        0x103cb4c4c - vortex_array::stats::array::StatsSetRef::compute_stat::hced7325eb9423d35
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-array/src/stats/array.rs:141:26
  38:        0x102197384 - vortex_layout::layouts::zoned::zone_map::StatsAccumulator::push_chunk::h4a844e1a42ed718a
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-layout/src/layouts/zoned/zone_map.rs:193:49
  39:        0x1021b382c - vortex_layout::layouts::file_stats::FileStatsAccumulator::process::h76a70a1d1770c2b1
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-layout/src/layouts/file_stats.rs:96:21
  40:        0x1021ed2b0 - vortex_layout::layouts::file_stats::accumulate_stats::{{closure}}::h9c190cda380ecdff
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-layout/src/layouts/file_stats.rs:30:36
  41:        0x10215db90 - <futures_util::stream::stream::scan::Scan<St,S,Fut,F> as futures_core::stream::Stream>::poll_next::h071c5ebd6866bffd
                               at /Users/asubiotto/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/scan.rs:92:38
  42:        0x102173d24 - <vortex_layout::sequence::SequentialStreamAdapter<S> as futures_core::stream::Stream>::poll_next::hc9470e3e0a517ee7
                               at /Users/asubiotto/Developer/github.com/vortex-data/vortex/vortex-layout/src/sequence.rs:305:48
  43:        0x10213d420 - <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next::habf86760b7552d9e
                               at /Users/asubiotto/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  44:        0x10213accc - <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::h391e77d65b021b53
                               at /Users/asubiotto/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/map.rs:58:47
  45:        0x10213d52c - <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next::hbc73d8a8e666528a
                               at /Users/asubiotto/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-core-0.3.31/src/stream.rs:130:33
  46:        0x10213be94 - futures_util::stream::stream::StreamExt::poll_next_unpin::h3ec3ab0de6e44692
                               at /Users/asubiotto/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/mod.rs:1638:24
  47:        0x1021280c0 - <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll::h4bd48b25634bdef1
                               at /Users/asubiotto/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/stream/stream/next.rs:32:21
  48:        0x102135f80 - <vortex_layout::layouts::struct_::writer::StructStrategy as vortex_layout::strategy::LayoutStrategy>::write_stream::{{closure}}::{{closure}}::hdbd9ea17dd9d76aa
```

### To Reproduce

I can share a reproduction with two ~250KB files if necessary.

### PR DESCRIPTION
**Pull request by asubiotto**
Prior to this commit, min_max on dictionaries would materialize the full dictionary. This commit deduplicates codes and checks whether they fully cover the values slice, in which case min_max can be run on the values slice. Even if the codes do not fully cover the values, we can materialize without duplicates, which should make take()ing the values slice cheaper.

The main motivation behind this change is to avoid panics caused by offset overflows due to this materialization of duplicates:

Closes #5121

### CODE REVIEW

File: encodings/dict/src/compute/min_max.rs [hunk 1]
```diff
@@ -1,16 +1,148 @@
...
+use vortex_dtype::match_each_unsigned_integer_ptype;
 use vortex_error::VortexResult;
+use vortex_mask::Mask;
 
 use crate::{DictArray, DictVTable};
 
 impl MinMaxKernel for DictVTable {
     fn min_max(&self, array: &DictArray) -> VortexResult<Option<MinMaxResult>> {
-        min_max(&take(array.values(), array.codes())?)
+        let Mask::AllTrue(_) = array.codes().validity_mask() else {
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: can you explain (in a comment) why we only handle all_true specially.

**Review by joseph-isaacs — COMMENTED** [review]
Are you trying to catch the case where all values are referenced in by a valid code?

**Comment by joseph-isaacs** [comment]
I wonder if we want to add value metadata that sorts if each value is accessible

File: encodings/dict/src/compute/min_max.rs [hunk 2]
```diff
@@ -1,16 +1,148 @@
...
+        let values_len = array.values().len();
+        match_each_unsigned_integer_ptype!(codes_primitive.ptype(), |P| {
+            let mut codes = codes_primitive
+                .as_slice::<P>()
+                .iter()
+                // First dedup of consecutive codes before collecting should
+                // make this operation a little cheaper.
+                .dedup()
+                .copied()
+                .collect::<Vec<_>>();
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: since we are allocating an indices Vec, why don't we:
 - allocate a `BitBuffer` 
 - use the index to trace value liveness,
 - convert that into a Mask
 - apply the mask to values and compute (min_max) since invalid values are ignored.


If this makes sense why don't we add a values liveness method to Dict that returns a BitBuffer/Mask?

Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: I felt like anything is better than fully materializing the dictionary, but I can take a stab at this. I don't think we should put it into dict unless we see a need to share the code/use it elsewhere

File: encodings/dict/src/compute/min_max.rs (hunk 1 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: I think if any of the codes are null, that's pretty much undefined behavior so I preferred to just fall back to take rather than fiddle with validity masks. Will add a comment.

File: encodings/dict/src/compute/min_max.rs (hunk 2 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: Done.

**Comment by asubiotto** [comment]
Updated to use a BitBuffer, thanks for the suggestion! Curious to hear your thoughts about code validity. I can definitely handle it, just not sure it's worth it..

**Comment by asubiotto** [comment]
Urgh, I think I confused myself. Nullable codes are valid, it's the values that shouldn't be null. Will update.

**Comment by asubiotto** [comment]
Ok, this is now RFAL. Updated to handle all types of validity.

File: encodings/dict/src/compute/min_max.rs [hunk 3]
```diff
@@ -1,16 +1,144 @@
...
-        min_max(&take(array.values(), array.codes())?)
+        let codes_validity = array.codes().validity_mask();
+        if codes_validity.all_false() {
+            return Ok(None);
+        }
+
+        let codes_primitive = array.codes().to_primitive();
+        let values_len = array.values().len();
+        match_each_unsigned_integer_ptype!(codes_primitive.ptype(), |P| {
+            let mut referenced = BitBufferMut::new_unset(values_len);
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: You want to use `BitBuffer::collect_bool`

File: encodings/dict/src/compute/min_max.rs [hunk 4]
```diff
@@ -1,16 +1,144 @@
...
+            for (code_idx, &code) in codes_primitive.as_slice::<P>().iter().enumerate() {
+                if codes_validity.value(code_idx)
+                    && let Some(value_idx) = code.to_usize()
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: This should panic/bail (not drop). Also use & not `&&` in the collect_bool return

File: encodings/dict/src/compute/min_max.rs [hunk 5]
```diff
@@ -1,16 +1,144 @@
...
+            if bit_buffer.true_count() == values_len {
+                // Codes fully cover all values, compute min_max directly on the
+                // values.
+                return min_max(array.values());
+            }
+
+            // Only some values are referenced, filter to only those values
+            // using a mask.
+            let mask = Mask::from_buffer(bit_buffer);
+            min_max(&filter(array.values(), &mask)?)
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: Don't filter use a min_max(mask()). Its much cheeper

Comment (joseph-isaacs) [reply encodings/dict/src/compute/min_max.rs]: You also don't need to special case, since mask(a, AllTrue()) is handled.

File: encodings/dict/src/compute/min_max.rs [hunk 6]
```diff
@@ -1,16 +1,144 @@
...
+        if codes_validity.all_false() {
+            return Ok(None);
+        }
+
+        let codes_primitive = array.codes().to_primitive();
+        let values_len = array.values().len();
+        match_each_unsigned_integer_ptype!(codes_primitive.ptype(), |P| {
+            let mut referenced = BitBufferMut::new_unset(values_len);
+            for (code_idx, &code) in codes_primitive.as_slice::<P>().iter().enumerate() {
+                if codes_validity.value(code_idx)
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: You likely want to ignore validity and logical `and` at the end since it will operate over u64 not u1

**Review by joseph-isaacs — COMMENTED** [review]
Thanks for adding this change

File: encodings/dict/src/compute/min_max.rs (hunk 3 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: I'm not sure this fits the pattern well. This way we allocate `values_len` bits. If I use collect_bool, I believe the complexity will be O(codes*values) to maintain O(values) space because I only get given value indices, while this is just one O(codes) pass. I could unroll but again not sure if this is a premature optimization.

File: encodings/dict/src/compute/min_max.rs (hunk 4 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: I'm going to follow the convention in the rest of the dict crate:
https://github.com/vortex-data/vortex/blob/10a2c864a1e8420dacdc483afec50c683306467a/encodings/dict/src/array.rs#L178-L180

File: encodings/dict/src/compute/min_max.rs (hunk 5 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: Good point, done! Had to invert the meaning of the bit buffer (I can also change that back and use `!` here, whatever you prefer)

File: encodings/dict/src/compute/min_max.rs (hunk 6 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: I don't think I can because the two masks don't have equal lengths (one is validity with length codes, the other is reference values with length values).

**Comment by asubiotto** [comment]
Addressed the latest comments.

File: encodings/dict/src/compute/min_max.rs (hunk 5 above)
Comment (joseph-isaacs) [reply encodings/dict/src/compute/min_max.rs]: I think this works.

File: encodings/dict/src/compute/min_max.rs (hunk 3 above)
Comment (joseph-isaacs) [reply encodings/dict/src/compute/min_max.rs]: Hmm you are correct, good call. We should use a `Vec<bool>` here and collect_bool to convert into bits. I am happy to do this as a follow up.

File: encodings/dict/src/compute/min_max.rs (hunk 6 above)
Comment (joseph-isaacs) [reply encodings/dict/src/compute/min_max.rs]: You are correct. I would want to zip the validity with the code. To avoid the checked access.

**Review by joseph-isaacs — APPROVED** [review]
I think we can do a few perf improvements but happy to follow up

File: encodings/dict/Cargo.toml [hunk 7]
```diff
@@ -21,6 +21,7 @@ arrow = ["dep:arrow-array"]
 [dependencies]
 arrow-array = { workspace = true, optional = true }
 arrow-buffer = { workspace = true }
+itertools = { workspace = true }
```
Comment (joseph-isaacs) [inline encodings/dict/Cargo.toml]: shall we remove this?

Comment (asubiotto) [reply encodings/dict/Cargo.toml]: Oops, yes.

File: encodings/dict/src/compute/min_max.rs [hunk 8]
```diff
@@ -1,16 +1,135 @@
...
+        let codes_primitive = array.codes().to_primitive();
+        let values_len = array.values().len();
+        match_each_unsigned_integer_ptype!(codes_primitive.ptype(), |P| {
+            // mask() sets values to null where the mask is true, so we start
+            // with a fully-set bit buffer.
+            let mut unreferenced = BitBufferMut::new_set(values_len);
+            for (code_idx, &code) in codes_primitive.as_slice::<P>().iter().enumerate() {
+                if codes_validity.value(code_idx) {
+                    #[allow(clippy::cast_possible_truncation)]
+                    unreferenced.unset(code as usize);
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: can we use set_unchecked?

Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: I tried to, but I don't think it's public unfortunately.

File: encodings/dict/src/compute/min_max.rs (hunk 3 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: We discussed separately: this is a potential improvement but we should validate this with benchmarking so leaving this for future work.

File: encodings/dict/src/compute/min_max.rs (hunk 6 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: Great idea, done.

File: encodings/dict/Cargo.toml (hunk 7 above)
Comment (asubiotto) [reply encodings/dict/Cargo.toml]: Removed some other dependencies that seemed unused while I was here.

File: encodings/dict/src/compute/min_max.rs (hunk 8 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: Made it pub

File: encodings/dict/src/compute/min_max.rs [hunk 9]
```diff
@@ -1,16 +1,140 @@
...
+            codes_validity.iter_bools(|validity_iter| {
+                // mask() sets values to null where the mask is true, so we start
+                // with a fully-set bit buffer.
+                let mut unreferenced = BitBufferMut::new_set(values_len);
+                for (&code, is_valid) in codes_primitive.as_slice::<P>().iter().zip(validity_iter) {
+                    if is_valid {
+                        // SAFETY: code is valid, so it must be in range.
+                        #[allow(clippy::cast_possible_truncation)]
+                        unsafe {
+                            unreferenced.unset_unchecked(code as usize);
```
Comment (joseph-isaacs) [inline encodings/dict/src/compute/min_max.rs]: I know that I suggested this but it unsafe, since we don't validate code in dict creation

**Review by joseph-isaacs — CHANGES_REQUESTED** [review]

File: encodings/dict/src/compute/min_max.rs (hunk 3 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: Benchmarking validated Vec<bool> was the right approach here. Done.

File: encodings/dict/src/compute/min_max.rs (hunk 8 above)
Comment (asubiotto) [reply encodings/dict/src/compute/min_max.rs]: Seems like we can't guarantee safety here, so made it private again.

**Review by joseph-isaacs — APPROVED** [review]
thanks for this
