### PR TITLE
Fix: ConstantArray float sum behaves the same way as primitive array

### LINKED ISSUE #5508: Fuzzing Crash: Sum aggregation produces incorrect result for F32 ChunkedArray
### Analysis

**Crash Location**: `fuzz/fuzz_targets/array_ops.rs:93` (in `assert_scalar_eq`)

**Error Message**:
```
called `Result::unwrap()` on an `Err` value: Scalar mismatch: expected -2048669274505641600000000000f64, got -2048669274505644600000000000f64 in step 1
```

**Stack Trace**:
```
   0: std::backtrace_rs::backtrace::libunwind::trace
   1: std::backtrace_rs::backtrace::trace_unsynchronized
   2: std::backtrace::Backtrace::create
   3: assert_scalar_eq at ./fuzz/fuzz_targets/array_ops.rs:187:13
   4: __libfuzzer_sys_run at ./fuzz/fuzz_targets/array_ops.rs:93:17
   5: rust_fuzzer_test_input
   6: {closure#0}
   7: do_call<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
```

**Root Cause**:

The fuzzer detected a floating-point precision/rounding error in the Sum aggregation operation. The test performs:

1. **Step 0**: FillNull operation on a ChunkedArray<F32> with fill value `6.1811675e16`
   - Input: ChunkedArray with 2 chunks (30 elements + 25 elements = 55 total)
   - Some elements are null (validity: Array with specific bit pattern)
   - Output: All nulls filled, producing array with cached sum statistic: `-2.0486692745056416e27`

2. **Step 1**: Sum operation
   - Expected sum (from step 0's cached stats): `-2048669274505641600000000000` (as f64)
   - Actual computed sum: `-2048669274505644600000000000` (as f64)
   - **Difference**: ~3e18 (about 0.00015% relative error)

The issue appears to be one of:
1. **Inconsistent precision handling**: F32 values being summed with different intermediate precision between the stat computation path and the actual sum operation
2. **Stat caching bug**: The cached sum statistic from FillNull may be computed differently than the sum() function
3. **Chunked array sum bug**: The sum across multiple chunks may accumulate rounding errors differently

Given that the input is F32 (single precision) but the sum is returned as F64 (double precision), the discrepancy suggests different code paths are handling the F32→F64 promotion and accumulation differently.

<details>
<summary>Debug Output</summary>

```
FuzzArrayAction {
    array: ChunkedArray {
        dtype: Primitive(
            F32,
            Nullable,
        ),
        len: 55,
        chunk_offsets: PrimitiveArray {
            dtype: Primitive(
                U64,
                NonNullable,
            ),
            buffer: Buffer<u8> {
                length: 24,
                alignment: Alignment(
                    8,
                ),
                as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0, ...],
            },
            validity: NonNullable,
            stats_set: ArrayStats {
                inner: RwLock {
                    data: StatsSet {
                        values: [],
                    },
                },
            },
        },
        chunks: [
            PrimitiveArray {
                dtype: Primitive(
                    F32,
                    Nullable,
                ),
                buffer: Buffer<u8> {
                    length: 120,
                    alignment: Alignment(
                        4,
                    ),
                    as_slice: [255, 119, 71, 65, 69, 69, 69, 69, 71, 71, 71, 71, 71, 71, 71, 71, ...],
                },
                validity: Array(
                    BoolArray {
                        dtype: Bool(
                            NonNullable,
                        ),
                        buffer: BitBuffer {
                            buffer: Buffer<u8> {
                                length: 4,
                                alignment: Alignment(
                                    1,
                                ),
                                as_slice: [241, 255, 255, 63],
                            },
                            offset: 0,
                            len: 30,
                        },
                        validity: NonNullable,
                        stats_set: ArrayStats {
                            inner: RwLock {
                                data: StatsSet {
                                    values: [],
                                },
                            },
                        },
                    },
                ),
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
            PrimitiveArray {
                dtype: Primitive(
                    F32,
                    Nullable,
                ),
                buffer: Buffer<u8> {
                    length: 100,
                    alignment: Alignment(
                        4,
                    ),
                    as_slice: [67, 67, 71, 46, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, ...],
                },
                validity: AllInvalid,
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
        ],
        stats_set: ArrayStats {
            inner: RwLock {
                data: StatsSet {
                    values: [],
                },
            },
        },
    },
    actions: [
        (
            FillNull(
                Scalar {
                    dtype: Primitive(
                        F32,
                        NonNullable,
                    ),
                    value: ScalarValue(
                        Primitive(
                            F32(
                                6.1811675e16,
                            ),
                        ),
                    ),
                },
            ),
            Array(
                PrimitiveArray {
                    dtype: Primitive(
                        F32,
                        NonNullable,
                    ),
                    buffer: Buffer<u8> {
                        length: 220,
                        alignment: Alignment(
                            4,
                        ),
                        as_slice: [255, 119, 71, 65, 100, 153, 91, 91, 100, 153, 91, 91, 100, 153, 91, 91, ...],
                    },
                    validity: NonNullable,
                    stats_set: ArrayStats {
                        inner: RwLock {
                            data: StatsSet {
                                values: [
                                    (
                                        Sum,
                                        Exact(
                                            ScalarValue(
                                                Primitive(
                                                    F64(
                                                        -2.0486692745056416e27,
                                                    ),
                                                ),
                                            ),
                                        ),
                                    ),
                                ],
                            },
                        },
                    },
                },
            ),
        ),
        (
            Sum,
            Scalar(
                Scalar {
                    dtype: Primitive(
                        F64,
                        Nullable,
                    ),
                    value: ScalarValue(
                        Primitive(
                            F64(
                                -2.0486692745056416e27,
                            ),
                        ),
                    ),
                },
            ),
        ),
    ],
}
```
</details>

### Summary

- **Target**: `array_ops`
- **Crash File**: `crash-e454ae57750bd10f192943c9d6193054b843b31f`
- **Branch**: develop
- **Commit**: 4a0051e579060e54c2432cb3aa126908890b5e00
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/19647675916/artifacts/4665932738

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/19647675916/artifacts/4665932738
   - Or find `operations-fuzzing-crash-artifacts` at: https://github.com/vortex-data/vortex/actions/runs/19647675916
   - Extract the zip file

2. Reproduce locally:
```bash
# The artifact contains array_ops/crash-e454ae57750bd10f192943c9d6193054b843b31f
cargo +nightly fuzz run --sanitizer=none array_ops array_ops/crash-e454ae57750bd10f192943c9d6193054b843b31f
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run --sanitizer=none array_ops array_ops/crash-e454ae57750bd10f192943c9d6193054b843b31f
```

---
*Auto-created by fuzzing workflow with Claude analysis*

### PR DESCRIPTION
**Pull request by robert3005**
fix #5508

Signed-off-by: Robert Kruszewski <github@robertk.io>

### CODE REVIEW

File: vortex-array/src/arrays/constant/compute/sum.rs [hunk 1]
```diff
@@ -138,21 +137,19 @@ fn sum_float(
...
     let initial = accumulator
         .as_primitive()
         .as_::<f64>()
         .vortex_expect("cannot be null");
-    Ok(Some(initial + array_sum))
+    let v = primitive_scalar
+        .as_::<f64>()
+        .vortex_expect("cannot be null");
+
+    let mut sum = initial;
```
Comment (a10y) [inline vortex-array/src/arrays/constant/compute/sum.rs:149]: can we add a comment for why we do this? i can imagine someone coming along in the future and changing this back to the multiply

Comment (robert3005) [reply vortex-array/src/arrays/constant/compute/sum.rs:149]: Sure, fwiw the numbers in the test are chosen so that this will fail if you change it to multiply

**Review by a10y — APPROVED** [review]
