### PR TITLE
Performance: `ListViewArray` zero-copyable to `ListArray` optimizations

### LINKED ISSUE #5053: ListView to List conversion is slow
### Describe the bug

Currently converting ListView to List goes through scalar operations. Ideally we would avoid double copy (to a scalar and to the target array) to produce list arrays

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by connortsui20**
Tracking Issue: https://github.com/vortex-data/vortex/issues/4699
Closes: https://github.com/vortex-data/vortex/issues/5053

This PR introduces a performance optimization for `ListViewArray` by adding an `is_zero_copy_to_list` flag that tracks whether the `ListViewArray` can be (near) constant-time converted to a `ListArray` without copying data.

When this flag is true (indicating sorted offsets with no gaps and no overlaps), conversions can bypass the very expensive rebuild process (which just calls `append_scalar` in a loop). 

Additionally, this PR refactors all `ListViewArray` constructor call sites and compute operations throughout the codebase to properly maintain this new invariant. The only time you can set this flag is via the `new_unchecked` constructor which is unsafe, which means the caller better be careful to know what they are doing.

Some things that are not included in this PR:
- Making conversion _actually_ zero-copy would require implementing logic to always allocate an additional `offsets` slot for an `n+1`th offset in `ListViewArray`. This is because `ListArray` has `n+1` offsets, and from a plain `ListViewArray` we have to reallocate the offsets to make space.
- `reset_offsets` right now is probably more expensive than it could be since it uses the `sub_scalar` compute function. We know in advance that `reset_offsets` should _never_ fail in the non-recursive case.
- Validation of this `is_zctl` flag is **SUPER** expensive, but it can be made a bit less expensive by using a `BitBuffer` to track references + a flag for overlaps.
- It would probably be nice to have an `check_is_zero_copy_to_list` function on `ListViewArray` that sets the flag if it detects it is zero-copyable to a `ListArray`. This would be nice when we are reading from disk or converting from an Arrow `GenericListView`.
- This PR **does not** change the on-disk format, which means we lose this metadata when writing to disk. I think that this flag is somewhat similar to the `is_sorted` statistic, but at the same time I feel like it is not correct to store this as a statistic? Not sure.

### CODE REVIEW

File: vortex-array/src/arrays/listview/compute/filter.rs [hunk 1]
```diff
@@ -46,17 +46,24 @@ impl FilterKernel for ListViewVTable {
         );
 
         // Simply filter the offsets and sizes arrays.
-        // Filters keep scalars in order, and it cannot cause overlaps to form. However, filters
-        // **will** create gaps of unused elements.
         let new_offsets = compute::filter(offsets.as_ref(), selection_mask)?;
         let new_sizes = compute::filter(sizes.as_ref(), selection_mask)?;
 
+        // Filters will create gaps of unused elements.
+        let is_zctl = false;
```
Comment (a10y) [inline vortex-array/src/arrays/listview/compute/filter.rs]: can just inline this and the comment to the constructor call

File: vortex-array/src/arrays/listview/compute/take.rs [hunk 2]
```diff
@@ -64,23 +64,27 @@ impl TakeKernel for ListViewVTable {
             )?
         });
 
+        // Take can reorder offsets, create gaps, and may introduce overlaps if the `indices`
+        // contain duplicates.
+        let is_zctl = false;
```
Comment (a10y) [inline vortex-array/src/arrays/listview/compute/take.rs]: also can inline into constructor call

File: vortex-array/src/arrays/listview/conversion.rs [hunk 3]
```diff
@@ -12,27 +12,35 @@ use crate::vtable::ValidityHelper;
...
         return Canonical::empty(list.dtype()).into_listview();
     }
 
-    let len = list.len();
+    // We reset the offsets here because mostly for convenience, and also because callers of this
+    // function might not expect the output `ListViewArray` to have a bunch of leading and trailing
+    // garbage data when they turn it back into a `ListArray`.
+    let list = list
+        .reset_offsets(false)
+        .vortex_expect("TODO(connor)[ListView]: This can't fail");
```
Comment (a10y) [inline vortex-array/src/arrays/listview/conversion.rs:30]: you don't have to do this right now, but i think that `Canonical::compact` should be infallible. I don't think there's ever a valid case right now where it could return an error since we've made validity and other array ops infallilble. Then we can delete this expect

Comment (connortsui20) [reply vortex-array/src/arrays/listview/conversion.rs:30]: Yeah I think this should come later (see my updated PR description above) and it can be optimized better

**Comment by joseph-isaacs** [comment]
What perf changes did you expect from the benchmarks?

**Comment by connortsui20** [comment]
@joseph-isaacs none since none of our benchmarks really test the conversion between list and listview (we have a test file that didn't finish on develop but finishes in 3-4 sec on this branch). Maybe we can add that as a be regression benchmark?

File: fuzz/src/array/mask.rs [hunk 4]
```diff
@@ -57,13 +57,18 @@ pub fn mask_canonical_array(canonical: Canonical, mask: &Mask) -> VortexResult<A
...
+
+            // SAFETY: Since we are only masking the validity and everything else comes from an
+            // already valid `ListViewArray`, all of the invariants are still upheld.
+            unsafe {
+                ListViewArray::new_unchecked(
+                    array.elements().clone(),
+                    array.offsets().clone(),
+                    array.sizes().clone(),
+                    new_validity,
+                    array.is_zero_copy_to_list(),
```
Comment (joseph-isaacs) [inline fuzz/src/array/mask.rs]: This feels leeky here

File: vortex-array/src/arrays/listview/tests/operations.rs [hunk 5]
```diff
@@ -156,9 +155,16 @@ fn test_slice_edge_cases(
...
-    let listview = ListViewArray::try_new(elements, offsets, sizes, Validity::NonNullable)
-        .unwrap()
-        .into_array();
+    let listview = unsafe {
+        ListViewArray::new_unchecked(
+            elements,
+            offsets,
+            sizes,
+            Validity::NonNullable,
+            true, // Is zero-copy to list.
```
Comment (joseph-isaacs) [inline vortex-array/src/arrays/listview/tests/operations.rs]: Seems like a `with_zero_copy` method would read better here

File: vortex-array/src/arrays/listview/array.rs [hunk 6]
```diff
@@ -345,11 +388,87 @@ where
...
+    Ok(())
+}
+
+/// Helper function to validate if the [`ListViewArray`] components are actually zero-copyable to
+/// [`ListArray`](crate::arrays::ListArray).
+fn validate_zctl(
+    elements: &dyn Array,
+    offsets_primitive: PrimitiveArray,
+    sizes_primitive: PrimitiveArray,
+) -> VortexResult<()> {
```
Comment (joseph-isaacs) [inline vortex-array/src/arrays/listview/array.rs:459]: is this tested?

**Review by joseph-isaacs — COMMENTED** [review]
Its nice we can avoid changing serialised array. Its telling that we always have a is_zctl comments everywhere

File: vortex-array/src/arrays/listview/array.rs [hunk 7]
```diff
@@ -128,39 +137,61 @@ impl ListViewArray {
...
+    ///   (even if the corresponding view is defined as null by the validity array).
     /// - If validity is an array, its length must equal `offsets.len()`.
+    /// - If the `is_zctl` flag is true, then the [`ListViewArray`] is zero-copyable to a
+    ///   [`ListArray`].
     pub unsafe fn new_unchecked(
         elements: ArrayRef,
         offsets: ArrayRef,
         sizes: ArrayRef,
         validity: Validity,
+        is_zctl: bool,
```
Comment (gatesn) [inline vortex-array/src/arrays/listview/array.rs]: In general, boolean arguments to _any_ function are a no no.

But here, I think this logic should be wrapped up in a `From<ListArray> for ListView` impl, rather than the user ever being able to pass this flag. Even the serde `build` function can check the flag and go via ListArray.

File: vortex-array/src/arrays/listview/array.rs (hunk 6 above)
Comment (connortsui20) [reply vortex-array/src/arrays/listview/array.rs:459]: Yes at every call site where we set is_zctl to true

File: vortex-array/src/arrays/listview/array.rs (hunk 7 above)
Comment (connortsui20) [reply vortex-array/src/arrays/listview/array.rs]: I think the issue with that here is we need a way to specify something is zero-copyable without  going through a `ListArray` (see the call sites where we change one component and then reconstruct things, like in slice or mask).

I think I like @joseph-isaacs's idea of adding an unsafe builder-like `with_zctl` method, but at the same time I feel that also makes it even harder to reason about the unsafety (harder than it already was) as you now need to worry about two unsafe calls instead of 1. Maybe that's fine?

File: fuzz/src/array/mask.rs (hunk 4 above)
Comment (connortsui20) [reply fuzz/src/array/mask.rs]: Leaky in what way? This is basically identical to the `mask` compute function impl

File: vortex-array/src/arrays/listview/array.rs (hunk 7 above)
Comment (connortsui20) [reply vortex-array/src/arrays/listview/array.rs]: I'm going to add an unsafe `with_zctl` method

File: vortex-array/src/arrays/listview/rebuild.rs [hunk 8]
```diff
@@ -53,121 +66,112 @@ impl ListViewArray {
...
-        // 2. The sizes array is unchanged, so each (new_offset, size) pair still describes a
-        //    valid range within the compacted elements array.
-        // 3. The validity is unchanged and still matches the array length.
+    /// Rebuilds a [`ListViewArray`] by trimming any unused / unreferenced leading and trailing
+    /// elements, which is defined as a contiguous run of values in the `elements` array that are
+    /// not referecened by any views in the corresponding [`ListViewArray`].
+    fn rebuild_trim_elements(&self) -> ListViewArray {
+        let start = if self.is_zero_copy_to_list() {
+            // If offsets are sorted, then the minimum offset is the first offset.
+            self.offset_at(0)
```
Comment (a10y) [inline vortex-array/src/arrays/listview/rebuild.rs:116]: does this hold if the first item is null?

Comment (connortsui20) [reply vortex-array/src/arrays/listview/rebuild.rs:116]: We have the constraint in `ListArray` where even if there are null elements defined by the validity mask, the offsets still must be sorted. So if the `ListViewArray` came from a `ListArray` that had a null first element, this is still valid.

Also when we validate offsets and sizes we completely ignore nulls since for `ListViewArray` we have the constraint that the views must be valid even if the validity mask specifies the view is null.

See https://arrow.apache.org/docs/format/Columnar.html#listview-layout, specifically:

> Every list-view value, including null values, has to guarantee the following invariants:

This does deserve a comment though

Edit: Added the comment in https://github.com/vortex-data/vortex/pull/5129/commits/258a35a5d8c1a8a4e5147a8a65adfa2af6b41243

**Review by a10y — APPROVED** [review]
Looks good, also ran it again with our broken test case file and perf on the last commit is back to acceptable. Ran the fuzzer for a few minutes and made sure it didn't catch issues either.

Let's ship it
