### PR TITLE
fix: Spawn datafusion write tasks

### LINKED ISSUE #4315: Datafusion VortexSink hangs when writing > 40_960 entries
While experimenting with `vortex-datafusion`, I observed that any attempt to write more than 40_960 entries (regardless of schema) causes the execution to hang indefinitely.

Minimized example that reproduces the issue:
```rust
use datafusion::arrow::array::Int8Array;
use datafusion::arrow::datatypes::{DataType, Field, Schema};
use datafusion::arrow::record_batch::RecordBatch;
use datafusion::datasource::file_format::format_as_file_type;
use datafusion::logical_expr::LogicalPlanBuilder;
use datafusion::prelude::SessionContext;
use std::default::Default;
use std::sync::Arc;
use tempfile::TempDir;
use vortex_datafusion::VortexFormatFactory;

const ENTRIES: usize = 40_961; // Works as expected for 0 to 40960, hangs for 40961

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let dir = TempDir::new()?;

    let session = SessionContext::new();

    let data = session.read_batch(RecordBatch::try_new(
        Arc::new(Schema::new(vec![Field::new("a", DataType::Int8, false)])),
        vec![Arc::new(Int8Array::from(vec![0i8; ENTRIES]))],
    )?)?;

    let logical_plan = LogicalPlanBuilder::copy_to(
        data.logical_plan().clone(),
        dir.path().to_str().unwrap().to_string(),
        format_as_file_type(Arc::new(VortexFormatFactory::default())),
        Default::default(),
        vec![],
    )?
    .build()?;

    session
        .execute_logical_plan(logical_plan)
        .await?
        .collect()
        .await?;

    Ok(())
}
```

> [!NOTE]
> Changing `ENTRIES` to `40_960` (or lower) allows the process to succeed

### PR DESCRIPTION
**Pull request by AdamGS**
Closes https://github.com/vortex-data/vortex/issues/4315, spawns writer tasks so the upstream data producer doesn't block.

### CODE REVIEW

File: vortex-datafusion/src/persistent/sink.rs [hunk 1]
```diff
@@ -95,24 +96,49 @@ impl FileSink for VortexSink {
...
+        // 1. We can probably be better at signaling how much memory we're consuming (potentially when reading too), see ParquetSink::spawn_writer_tasks_and_join.
         while let Some((path, rx)) = file_stream_rx.recv().await {
             let row_counter = row_counter.clone();
-            let stream = ReceiverStream::new(rx).map(move |rb| {
-                row_counter.fetch_add(rb.num_rows() as u64, Ordering::Relaxed);
-                VortexResult::Ok(ArrayRef::from_arrow(rb, false))
+            let object_store = object_store.clone();
+            let dtype = DType::from_arrow(self.config.output_schema.clone());
+
+            // We need to spawn work because there's a dependency between
```
Comment (robert3005) [inline vortex-datafusion/src/persistent/sink.rs]: dependency between...? The suspense is killing me

Comment (AdamGS) [reply vortex-datafusion/src/persistent/sink.rs]: 😂

Comment (AdamGS) [reply vortex-datafusion/src/persistent/sink.rs]: expanded a bit, hard to capture it in a reasonably-sized comment, and its also a private implementation details of datafusion that I assume doesn't really have any guarantees.
I'll try and find some time next week to improve of the public docs there (in datafusion) a bit, maybe will help us get some clarity about the behavior here.

**Review by robert3005 — APPROVED** [review]
