### PR TITLE
fix: BitPackedArray must be unsigned

### LINKED ISSUE #929: [bug] FastLanes signed integer array round trip failed
Hi Vortex! I recently played a bit on Vortex <-> Arrow with FastLane encoding.

However, it seems that current implementation automatically convert signed interger to unsigned variant, as shown in the following code: https://github.com/spiraldb/vortex/blob/develop/encodings/fastlanes/src/bitpacking/compress.rs#L33-L40

Here's a minimal reproducible code, it will panic because the `Int64Array` is converted back to `UInt64Array`
```rust
use arrow::{
    array::{AsArray, Int64Array, UInt64Array},
    datatypes::{Int64Type, UInt64Type},
};
use vortex::{arrow::FromArrowArray, IntoCanonical};
use vortex_fastlanes::{find_best_bit_width, BitPackedArray};

fn main() {
    let vortex_array =
        vortex::Array::from_arrow(&Int64Array::from_iter(-500..500), false).as_primitive();

    let bitpacked_array = BitPackedArray::encode(
        vortex_array.as_ref(),
        find_best_bit_width(&vortex_array).unwrap(),
    )
    .unwrap();

    println!("bitpacked_array: {:?}", bitpacked_array);

    let canonical_array = bitpacked_array
        .into_canonical()
        .unwrap()
        .into_arrow()
        .unwrap();
    let arrow_array_again = canonical_array.as_primitive::<Int64Type>();
    println!("arrow_array_again: {:?}", arrow_array_again);
}
```

I tried to comment out the `.to_unsigned()` etc, and it seems to work again.
I haven't read FastLane paper carefully, can you provide some hints on why to convert it into unsigned values?

### PR DESCRIPTION
**Pull request by lwwmanning**
fixes #929

### CODE REVIEW

File: encodings/fastlanes/src/bitpacking/compress.rs [hunk 1]
```diff
@@ -395,4 +396,14 @@ mod test {
                 assert_eq!(scalar, *v);
             });
     }
+
+    #[test]
```
Comment (robert3005) [inline encodings/fastlanes/src/bitpacking/compress.rs:400]: Should_panic? If you unwrap the error would be easier to assert

**Review by AdamGS — APPROVED** [review]
LGTM

**Review by robert3005 — APPROVED** [review]
