### PR TITLE
Fix null coercion of scalars

### LINKED ISSUE #2171: Vortex / DataFusion null casting
In order to be fully compute-engine agnostic, Vortex has chosen to never implicitly cast or coerce data types. I think this is the right decision.

However, we don't respect this in a two places:
* CompareFn allows eq_ignore_nullability and up-casts nullability
* PrimitiveScalar::checked_binary_numeric

This is weird.

Combine this with the weird (wrong) way that we convert DataFusion literal expressions (scalars) into Vortex scalars. For non-null values, we always return the equivalent *nullable* Vortex DType with `Scalar::from(Option<T>)`. For null values.... we return `DType::Null` which would break everything, so we clearly don't hit this code path.

Due to CompareFn nullability upcasting, we _always_ propagate comparison results with literals as nullable, even if the column is non-nullable, and the scalar is non-nullable. For example `a < 10` would return a nullable booelan column even when a is non-nullable. This is wrong.

Other compute functions _don't_ perform nullability upcasting. In fact, they would return an error. If DataFusion pushed down `a + 10` to us, we would fail because 10 always turns into a nullable scalar, and we cannot add that to the non-nullable `a` column. This never happens at the moment because DataFusion doesn't do push-down projection, only push-down filtering.

What's the fix?

* DataFusion Scalar -> Vortex Scalar should take an explicit nullability, same as array conversion.
* DataFusion Literal Expr -> Vortex Literal Expr should use the "tightest" nullability, e.g. if nullable if its null, and non-nullable if it has a value. This is the wrong DType, but we will upcast later.
* After performing full expression conversion, we must do a second pass to insert cast expressions to fix nullability. This is easy enough to write because DataFusion has already casted all dtypes when converting to PhysicalExpr, just without nullability.
* All compute functions should fail if dtypes to not exactly match on both sides.
* We should consider type-specific scalars to be generic over exact DType, e.g. `TypedScalar<NullableBool>` and therefore we can safely define Ord, not just PartialOrd

Alternatively
* We support implicit nullability casting (but not other casting!)
* We fix all compute functions to support this, rather than check for `lhs.dtype() == rhs.dtype()`
* We allow PartialOrd for typed scalars even with mismatched nullability.
* We still choose the tightest nullability on the data fusion literal conversion.
* We don't need to further rewrite the DataFusion expression

### PR DESCRIPTION
**Pull request by gatesn**
Fixes #2171

### CODE REVIEW

File: vortex-array/src/builders/mod.rs [hunk 1]
```diff
@@ -88,7 +88,7 @@ pub fn builder_with_capacity(dtype: &DType, capacity: usize) -> Box<dyn ArrayBui
 pub trait ArrayBuilderExt: ArrayBuilder {
     /// A generic function to append a scalar to the builder.
     fn append_scalar(&mut self, scalar: &Scalar) -> VortexResult<()> {
-        if !scalar.dtype().eq_ignore_nullability(self.dtype()) {
+        if scalar.dtype() != self.dtype() {
```
Comment (lwwmanning) [inline vortex-array/src/builders/mod.rs:115]: I don't mind being strict here, but we obviously could potentially choose to accept the scalar in the additional case where `scalar.dtype().eq_ignore_nullability(self.dtype()) && !scalar.is_null()`...

File: vortex-array/src/compute/boolean.rs [hunk 2]
```diff
@@ -72,10 +72,21 @@ pub fn or_kleene(lhs: impl AsRef<Array>, rhs: impl AsRef<Array>) -> VortexResult
...
+            "Boolean operations aren't supported on arrays of different lengths: {} and {}",
+            lhs.len(),
+            rhs.len()
+        )
     }
-    if !lhs.dtype().is_boolean() || !rhs.dtype().is_boolean() {
-        vortex_bail!("Boolean operations are only supported on boolean arrays")
+    if !lhs.dtype().is_boolean()
+        || !rhs.dtype().is_boolean()
+        || !lhs.dtype().eq_ignore_nullability(rhs.dtype())
```
Comment (lwwmanning) [inline vortex-array/src/compute/boolean.rs:91]: nit: could simplify as `!matches!(lhs.dtype(), DType::Boolean(_)) || ...`

File: vortex-layout/src/layouts/chunked/stats_table.rs [hunk 3]
```diff
@@ -146,9 +151,13 @@ impl StatsAccumulator {
...
 
     pub fn push_chunk(&mut self, array: &Array) -> VortexResult<()> {
+        if &self.column_dtype != array.dtype() {
+            vortex_bail!("Chunk dtype does not match expected stats column dtype");
+        }
+
         for (s, builder) in self.stats.iter().zip_eq(self.builders.iter_mut()) {
             if let Some(v) = array.statistics().compute(*s) {
-                builder.append_scalar(&Scalar::new(s.dtype(array.dtype()), v))?;
+                builder.append_scalar(&Scalar::new(s.dtype(array.dtype()).as_nullable(), v))?;
```
Comment (lwwmanning) [inline vortex-layout/src/layouts/chunked/stats_table.rs]: should Stat::dtype() function just always return a `Nullable` dtype...?

File: vortex-array/src/builders/mod.rs (hunk 1 above)
Comment (gatesn) [reply vortex-array/src/builders/mod.rs:115]: I think for builders it's reasonable to be strict right?

File: vortex-layout/src/layouts/chunked/stats_table.rs (hunk 3 above)
Comment (gatesn) [reply vortex-layout/src/layouts/chunked/stats_table.rs]: No, this is only in the context of a stats table where a chunk encoding may not know how to compuite a stat, therefore it's missing, even though the DType of the statistic is non-nullable (i.e. matches that of the column)

Comment (joseph-isaacs) [reply vortex-layout/src/layouts/chunked/stats_table.rs]: +1

File: vortex-scalar/src/utf8.rs [hunk 4]
```diff
@@ -7,19 +7,29 @@ use vortex_error::{vortex_bail, vortex_err, VortexError, VortexExpect as _, Vort
 
 use crate::{InnerScalarValue, Scalar, ScalarValue};
 
-#[derive(Debug, Hash, PartialEq, Eq)]
+#[derive(Debug, Hash)]
 pub struct Utf8Scalar<'a> {
```
Comment (joseph-isaacs) [inline vortex-scalar/src/utf8.rs:11]: Can we make the scalars a TypedScalar<'a, T>? So we can share these, definitions

File: docs/concepts/compute.md [hunk 5]
```diff
@@ -34,4 +34,10 @@ codes.
...
 * `filter(Array, mask: Mask) -> Array`
-    * Filter the array based on the given mask.
\ No newline at end of file
+    * Filter the array based on the given mask.
+
+## Type Coercion
+
+To maximise compatibility with compute engines, Vortex does not perform any implicit type coercion in its compute
+functions or expressions. The exception to this is upcasting the nullability of input data types. For example,
+it is valid to compare a `u32` and `u32?` array, resulting in a `bool?` array.
```
Comment (joseph-isaacs) [inline docs/concepts/compute.md:43]: What about `list(u32)?` compared to `list(u32?)`.

File: vortex-array/src/builders/mod.rs (hunk 1 above)
Comment (joseph-isaacs) [reply vortex-array/src/builders/mod.rs:115]: +1

File: vortex-scalar/src/utf8.rs (hunk 4 above)
Comment (gatesn) [reply vortex-scalar/src/utf8.rs:11]: Not right now

**Comment by gatesn** [comment]
I think this is blocked on #2174

**Comment by gatesn** [comment]
Nope.. this seems like it's a DataFusion bug? https://github.com/apache/datafusion/issues/14394

**Review by AdamGS — APPROVED** [review]
