### PR TITLE
Duckdb 1.5-variegata

### LINKED ISSUE #5889: Upgrade to DuckDB 1.5.0
- [x] `DictionaryVector::SetDictionaryId` replaced I think by `DictionaryVector::CreateReusableDictionary` 
  * See https://github.com/duckdb/duckdb/pull/19332
- [x] `ObjectCacheEntry` has additional virtual function for estimated size
  * See https://github.com/duckdb/duckdb/pull/20157
- [x] Annoying: testing pre-release https://github.com/vortex-data/vortex/pull/6658
- [x] Duckdbfs regression: curl backend may fail for some of URLs https://github.com/duckdb/duckdb-httpfs/pull/261 https://github.com/duckdb/duckdb-httpfs/pull/262

### PR DESCRIPTION
**Pull request by myrrc**
1.5 API changes:

- Add support for reusable dictionaries. Remove duckdb_vx_set_dictionary_vector_id in favor of reusable dictionaries.
- Add estimated_size to duckdb_vx_object_cache_put
- Replace set_variables with set_variable_defaults in database options.
- Replace DUCKDB_STANDARD_VECTOR_SIZE with C++ API constant.
- Add error on Bloom filter pushdown request, otherwise we get a duckdb assertion and a leak https://github.com/vortex-data/vortex/pull/6627#issuecomment-3991614737 when we try to get an ExpressionFilter in duckdb_vx_table_filter_get_expression but it's a Bloom filter
- Build httpfs statically if we're on a commit

https://github.com/vortex-data/vortex/issues/5767

Continuation of https://github.com/vortex-data/vortex/pull/5901

### CODE REVIEW

**Comment by myrrc** [comment]
Testing this change is tricky as 1.5 is not released, thus there are no artifacts. I'll open a patch to spin up our own building jobs and cache artifacts in own S3, so we could test pre-releases.

**Comment by myrrc** [comment]
So far I've managed to build CI's httpfs statically, but there is a strange error on localhost test access:

```
thread 'e2e_test::vortex_scan_test::test_vortex_scan_over_http' panicked at vortex-duckdb/src/e2e_test/vortex_scan_test.rs:398:10:
called `Result::unwrap()` on an `Err` value: Other error: Failed to execute query: Binder Error: Other error: {"exception_type":"IO","exception_message":"Could not resolve hostname error for HTTP HEAD to 'http://127.0.0.1:37375//.tmph5IRUz.vortex'"}
Backtrace:
   0: std::backtrace::Backtrace::create
   1: vortex_duckdb::duckdb::file_system::fs_error
   2: <vortex_duckdb::filesystem::DuckDbFileSystem as vortex_io::filesystem::FileSystem>::open_read::{{closure}}

```

Accessing an https:// endpoint works fine so there's an issue with duckdb filesystem specifically for localhost, but I'm yet to determine whether that's something that's an issue in 1.5 (i.e. curl) or our code is wired up incorrectly (though the error is coming from duckdb itself so it's unlikely)

**Comment by myrrc** [comment]
The issue is in changes in https/core duckdb between 1.4 and 1.5, because 'SET httpfs_client_implementation = httplib' makes the test pass.

**Comment by myrrc** [comment]
Default dev duckdb[-fs] `928e9127e2` works correctly for localhost:

```
memory D LOAD httpfs;
memory D SELECT * FROM 'http://127.0.0.1:12345/123.csv';
┌───────────────┬─────────┬─────────┬─────────┬────────────┐
│    column0    │ column1 │ column2 │ column3 │  column4   │
│    varchar    │  int64  │  int64  │ double  │    date    │
├───────────────┼─────────┼─────────┼─────────┼────────────┤
│ San Francisco │      46 │      50 │    0.25 │ 1994-11-27 │
│ San Francisco │      43 │      57 │     0.0 │ 1994-11-29 │
│ Hayward       │      37 │      54 │    NULL │ 1994-11-29 │
└───────────────┴─────────┴─────────┴─────────┴────────────┘
```

**Comment by myrrc** [comment]
This is the tester script:

```python
#!/bin/python
from pathlib import Path
from subprocess import check_output
import http.server as hs
import json

port = 12345
#raw = check_output("ip -j -4 addr show scope global", shell=True, text=True)
#ip = json.loads(raw)[0]["addr_info"][0]["local"]
serve = "/home/myrrc/test.csv"
ip = "127.0.0.1"
print(f"http://{ip}:{port}")

class Handler(hs.BaseHTTPRequestHandler):
    def form(self, names):
        self.send_response(200)
        self.end_headers()
        self.wfile.write((Path(serve).read_text()).encode("utf-8"))

    def do_GET(self):
        self.form("")

    def do_HEAD(self):
        self.form("")

try:
    hs.HTTPServer((ip, port), Handler).serve_forever()
except KeyboardInterrupt:
    pass

```

Also works for private ips (192.168.*)

**Comment by myrrc** [comment]
The error in curl backend is due to URL parsing.

```
memory D LOAD httpfs;
memory D SELECT * FROM 'http://127.0.0.1:12345/1.csv';
127.0.0.1 - - [24/Feb/2026 10:35:54] "HEAD /1.csv HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2026 10:35:54] "GET /1.csv HTTP/1.1" 200 -
┌───────────────┬─────────┬─────────┬─────────┬────────────┐
│    column0    │ column1 │ column2 │ column3 │  column4   │
│    varchar    │  int64  │  int64  │ double  │    date    │
├───────────────┼─────────┼─────────┼─────────┼────────────┤
│ San Francisco │      46 │      50 │    0.25 │ 1994-11-27 │
│ San Francisco │      43 │      57 │     0.0 │ 1994-11-29 │
│ Hayward       │      37 │      54 │    NULL │ 1994-11-29 │
└───────────────┴─────────┴─────────┴─────────┴────────────┘
memory D SELECT * FROM 'http://127.0.0.1:12345//./1.csv';
IO Error:
Could not resolve hostname error for HTTP HEAD to 'http://127.0.0.1:12345//./1.csv'
```

**Comment by myrrc** [comment]
When adding curl verbose logging, the path is also different

```
~/duckdb-httpfs ./build/debug/duckdb -c "SELECT * FROM 'http://127.0.0.1:8000//1.csv';"
* Could not resolve host: 1.csv
* shutting down connection #0
* Could not resolve host: 1.csv
* shutting down connection #0
* Could not resolve host: 1.csv
* shutting down connection #0
* Could not resolve host: 1.csv
* shutting down connection #0
IO Error:
Could not resolve hostname error for HTTP HEAD to 'http://127.0.0.1:8000//1.csv'
~/duckdb-httpfs ./build/debug/duckdb -c "SELECT * FROM 'http://127.0.0.1:8000/1.csv';"
*   Trying 127.0.0.1:8000...
* connect to 127.0.0.1 port 8000 from 127.0.0.1 port 50582 failed: Connection refused
* Failed to connect to 127.0.0.1 port 8000 after 0 ms: Could not connect to server
* closing connection #0
*   Trying 127.0.0.1:8000..
```

**Comment by myrrc** [comment]
https://github.com/vortex-data/vortex/issues/6706#issuecomment-3983465349

**Comment by myrrc** [comment]
```
0x0000fffff4e8314c in ?? () from /lib/aarch64-linux-gnu/libc.so.6
(gdb) bt
#0  0x0000fffff4e8314c in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000fffff6396a20 in void duckdb::TupleDataValueStore<duckdb::string_t>(duckdb::string_t const&, unsigned char* const restrict&, unsigned long const&, unsigned char*&) ()
   from /home/myrrc/vortex/target/duckdb-lib-7f992e5a96662d66134577cf9d8a5bad9053847e/libduckdb.so
#2  0x0000fffff63b37e8 in void duckdb::TupleDataTemplatedScatter<duckdb::string_t>(duckdb::Vector const&, duckdb::TupleDataVectorFormat const&, duckdb::SelectionVector const&, unsigned long, duckdb::TupleDataLayout const&, duckdb::Vector const&, duckdb::Vector&, unsigned long, duckdb::UnifiedVectorFormat const&, duckdb::vector<duckdb::TupleDataScatterFunction, true, std::allocator<duckdb::TupleDataScatterFunction> > const&) ()
   from /home/myrrc/vortex/target/duckdb-lib-7f992e5a96662d66134577cf9d8a5bad9053847e/libduckdb.so
#3  0x0000fffff63c32e8 in duckdb::TupleDataCollection::Scatter(duckdb::TupleDataChunkState&, duckdb::Vector const&, unsigned long, duckdb::SelectionVector const&, unsigned long) const ()
   from /home/myrrc/vortex/target/duckdb-lib-7f992e5a96662d66134577cf9d8a5bad9053847e/libduckdb.so
#4  0x0000fffff63c34f0 in duckdb::TupleDataCollection::Scatter(duckdb::TupleDataChunkState&, duckdb::DataChunk const&, duckdb::SelectionVector const&, unsigned long) const ()
   from /home/myrrc/vortex/target/duckdb-lib-7f992e5a96662d66134577cf9d8a5bad9053847e/libduckdb.so
#5  0x0000fffff63c6ccc in duckdb::PartitionedTupleData::AppendUnified(duckdb::PartitionedTupleDataAppendState&, duckdb::DataChunk&, duckdb::SelectionVector const&, unsigned long) ()
   from /home/myrrc/vortex/target/duckdb-lib-7f992e5a96662d66134577cf9d8a5bad9053847e/libduckdb.so
#6  0x0000fffff68e3274 in duckdb::JoinHashTable::Build(duckdb::PartitionedTupleDataAppendState&, duckdb::DataChunk&, duckdb::DataChunk&) ()
```

^ Stacktrace for the segfault

**Comment by myrrc** [comment]
Looks like we're copying some wrong-sized memory region

```
#1  0x0000fffff6745b00 in duckdb::TupleDataValueStore<duckdb::string_t>(const duckdb::string_t &, duckdb::data_t * const __restrict__&, const duckdb::idx_t &, duckdb::data_ptr_t &) (source=..., 
    row_location=@0xffffb40af968: 0xffffb41ccf18 "\377\377\377\377", 
    offset_in_row=@0xffffaf7eb240: 20, heap_location=@0xffffb4029018: 0xffdeb7ff2018 "0\b")
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:39
39			FastMemcpy(heap_location, source.GetPointer(), source.GetSize());
```

**Comment by myrrc** [comment]
I believe the issue is in somewhere else. If I comment the specific copying code, it errors elsewhere:

```
#1  0x0000fffff664992c in duckdb::string_t::StringComparisonOperators::Equals (a=..., b=...)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/types/string_type.hpp:98
#2  duckdb::string_t::StringComparisonOperators::Equals (a=..., b=...)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/types/string_type.hpp:157
#3  duckdb::string_t::operator== (this=<optimized out>, r=...)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/types/string_type.hpp:214
#4  duckdb::Equals::Operation<duckdb::string_t> (left=..., right=...)

```

**Comment by myrrc** [comment]
Full stacktrace:

```
#0  0x0000fffff503314c in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000fffff650df70 in duckdb::TupleDataValueStore<duckdb::string_t>(const duckdb::string_t &, duckdb::data_t * const __restrict__&, const duckdb::idx_t &, duckdb::data_ptr_t &) (source=..., 
    row_location=@0xffffc41d4718: 0xffffc41dc4f8 "\377\377\377\377\260[", 
    offset_in_row=@0xffffaefdb240: 20, heap_location=@0xffffc4000948: 0xffdd2bfbf018 "0\b")
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:42
#2  0x0000fffff6525510 in duckdb::TupleDataTemplatedScatterInternal<duckdb::string_t, true, false, true> (source_format=..., append_sel=..., append_count=15, layout=..., row_locations=..., 
    heap_locations=..., col_idx=1)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:757
#3  duckdb::TupleDataTemplatedScatter<duckdb::string_t> (source=..., source_format=..., 
    append_sel=..., append_count=15, layout=..., row_locations=..., heap_locations=..., col_idx=1, 
    dummy_arg=..., child_functions=...)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:789
#4  0x0000fffff6534b68 in duckdb::TupleDataCollection::Scatter (this=this@entry=0xffffc41da640, 
    chunk_state=..., source=..., column_id=<optimized out>, append_sel=..., 
    append_count=append_count@entry=15)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:712
#5  0x0000fffff6534d70 in duckdb::TupleDataCollection::Scatter (this=this@entry=0xffffc41da640, 
    chunk_state=..., new_chunk=..., append_sel=..., append_count=append_count@entry=15)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:690
#6  0x0000fffff6538acc in duckdb::PartitionedTupleData::AppendUnified (this=0xffffc41676b0, 
--Type <RET> for more, q to quit, c to continue without paging--
    state=..., input=..., append_sel=..., append_count=<optimized out>)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/partitioned_tuple_data.cpp:83
#7  0x0000fffff6a580d4 in duckdb::JoinHashTable::Build (this=this@entry=0xffffc411c490, 
    append_state=..., keys=..., payload=...)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/join_hashtable.cpp:447
#8  0x0000fffff6968630 in duckdb::PhysicalHashJoin::Sink (this=<optimized out>, context=..., 
    chunk=..., input=...)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/join/physical_hash_join.cpp:348
#9  0x0000fffff6bbafd8 in duckdb::PipelineExecutor::ExecutePushInternal (
    this=this@entry=0xffffc41da8f0, input=..., chunk_budget=..., initial_idx=initial_idx@entry=0)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:336
#10 0x0000fffff6bc00d4 in duckdb::PipelineExecutor::Execute (this=this@entry=0xffffc41da8f0, 
    max_chunks=max_chunks@entry=18446744073709551615)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:253
#11 0x0000fffff6bc0368 in duckdb::PipelineExecutor::Execute (this=this@entry=0xffffc41da8f0)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:282
#12 0x0000fffff6bc0464 in duckdb::PipelineTask::ExecuteTask (this=0xfffff00151a0, 
    mode=duckdb::TaskExecutionMode::PROCESS_ALL)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:52
#13 0x0000fffff6bb5a54 in duckdb::ExecutorTask::Execute (this=0xfffff00151a0, 
    mode=duckdb::TaskExecutionMode::PROCESS_ALL)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
#14 0x0000fffff6bc2548 in duckdb::TaskScheduler::ExecuteForever (this=0xaaaaad1f0eb0, 
    marker=0xaaaaad0fdc90)
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
#15 0x0000fffff531b4e0 in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
#16 0x0000fffff5015ef8 in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#17 0x0000fffff507de0c in ?? () from /lib/aarch64-linux-gnu/libc.so.6
```

The segfault itself is trying to memcpy from an invalid string_t: both length
values of inlined and non-inlined union types are too large, the pointer doesn't
actually point to a valid string.

```
#1  0x0000fffff650df70 in duckdb::TupleDataValueStore<duckdb::string_t>(const duckdb::string_t &, duckdb::data_t * const __restrict__&, const duckdb::idx_t &, duckdb::data_ptr_t &) (source=..., 
    row_location=@0xffffc41d4718: 0xffffc41dc4f8 "\377\377\377\377\260[", 
    offset_in_row=@0xffffaefdb240: 20, heap_location=@0xffffc4000948: 0xffdd2bfbf018 "0\b")
    at /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/common/types/row/tuple_data_scatter_gather.cpp:42
(gdb) list
37		} else {
38			// Copy non-inlined part
39			FastMemcpy(heap_location, source.GetPointer(), source.GetSize());
40			// Copy first 8 bytes of string_t
41			memcpy(row_location + offset_in_row, &source, string_t::HEADER_SIZE);
42			// Copy new heap pointer into the correct offset
43			Store<data_ptr_t>(heap_location, row_location + offset_in_row + string_t::HEADER_SIZE);
44			// Increment heap pointer
45			heap_location += source.GetSize();
46		}
(gdb) p source
$1 = (const duckdb::string_t &) @0xffffc41343e0: {static PREFIX_BYTES = 4, static INLINE_BYTES = 12, 
  static HEADER_SIZE = 8, static MAX_STRING_SIZE = 4294967295, static PREFIX_LENGTH = 4, 
  static INLINE_LENGTH = 12, value = {pointer = {length = 3288336448, prefix = "\377\377\000", 
      ptr = 0xffffc4000840 "0\b"}, inlined = {length = 3288336448, 
      inlined = "\377\377\000\000@\b\000\304\377\377\000"}}}
```

This error reproduces from time to time.

Our reproduction:

```
LD_LIBRARY_PATH=~/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src gdb --args ~/vortex/target/release/duckdb-bench tpcds --formats "vortex-compact"
```

LD_LIBRARY_PATH override as otherwise duckdb-bench uses copied libduckdb.so
with stripped debug symbols

Asan build:

```
LD_PRELOAD="/usr/lib/gcc/aarch64-linux-gnu/14/libasan.so /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so" ~/vortex/target/release/duckdb-bench tpcds --formats "vortex-compact"
```

Crashes occur only on vortex and vortex-compact

Asan/ubsan build

```
cd ~/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e
cmake -GNinja -DFORCE_DEBUG=1 -DFORCE_ASSERT=1 -DDEBUG_ALLOCATION=1 -DBUILD_UNITTESTS=0 -DENABLE_UNITTEST_CPP_TESTS=0 -DRUN_SLOW_VERIFIERS=1 -DRELEASE_SANITIZER=1 -DENABLE_SANITIZER=1 -DENABLE_UBSAN=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build/reldebug
cmake --build build/reldebug
```

Tsan build

```
cmake -GNinja -DENABLE_THREAD_SANITIZER=1 -DRELEASE_SANITIZER=1 -DBUILD_UNITTESTS=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build/reldebug/
```

Asan crash

```
==2603771==ERROR: AddressSanitizer: unknown-crash on address 0xbebebebebebebebe at pc 0xffff94c284bc bp 0xffe6e5af04a0 sp 0xffe6e5af04e0
READ of size 3200171710 at 0xbebebebebebebebe thread T361
    #0 0xffff94c284b8 in memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115
    #1 0xffff92f26a1c in void duckdb::TupleDataValueStore<duckdb::string_t>(duckdb::string_t const&, unsigned char* const restrict&, unsigned long const&, unsigned char*&) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x1096a1c) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #2 0xffff92f43ad8 in void duckdb::TupleDataTemplatedScatter<duckdb::string_t>(duckdb::Vector const&, duckdb::TupleDataVectorFormat const&, duckdb::SelectionVector const&, unsigned long, duckdb::TupleDataLayout const&, duckdb::Vector const&, duckdb::Vector&, unsigned long, duckdb::UnifiedVectorFormat const&, duckdb::vector<duckdb::TupleDataScatterFunction, true, std::allocator<duckdb::TupleDataScatterFunction> > const&) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x10b3ad8) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #3 0xffff92f532e4 in duckdb::TupleDataCollection::Scatter(duckdb::TupleDataChunkState&, duckdb::Vector const&, unsigned long, duckdb::SelectionVector const&, unsigned long) const (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x10c32e4) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #4 0xffff92f534ec in duckdb::TupleDataCollection::Scatter(duckdb::TupleDataChunkState&, duckdb::DataChunk const&, duckdb::SelectionVector const&, unsigned long) const (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x10c34ec) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #5 0xffff92f56d6c in duckdb::PartitionedTupleData::AppendUnified(duckdb::PartitionedTupleDataAppendState&, duckdb::DataChunk&, duckdb::SelectionVector const&, unsigned long) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x10c6d6c) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #6 0xffff93473270 in duckdb::JoinHashTable::Build(duckdb::PartitionedTupleDataAppendState&, duckdb::DataChunk&, duckdb::DataChunk&) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x15e3270) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #7 0xffff933847cc in duckdb::PhysicalHashJoin::Sink(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::OperatorSinkInput&) const (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x14f47cc) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #8 0xffff935d6174 in duckdb::PipelineExecutor::ExecutePushInternal(duckdb::DataChunk&, duckdb::ExecutionBudget&, unsigned long) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x1746174) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #9 0xffff935db270 in duckdb::PipelineExecutor::Execute(unsigned long) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x174b270) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #10 0xffff935db600 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x174b600) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #11 0xffff935d0bf0 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x1740bf0) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #12 0xffff935dd6e4 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x174d6e4) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #13 0xffff91cfb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #14 0xffff94bae2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #15 0xffff919f5ef4  (/lib/aarch64-linux-gnu/libc.so.6+0x85ef4) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)
    #16 0xffff91a5de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

Address 0xbebebebebebebebe is a wild pointer inside of access range of size 0x0000bebebebe.
SUMMARY: AddressSanitizer: unknown-crash ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_memintrinsics.inc:115 in memcpy
Thread T361 created by T0 here:
    #0 0xffff94c228c0 in pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:245
    #1 0xffff91cfb664 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb664) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #2 0xffff935d498c in duckdb::TaskScheduler::RelaunchThreadsInternal(int, bool) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x174498c) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #3 0xffff935d52b0 in duckdb::TaskScheduler::RelaunchThreads() (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x17452b0) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #4 0xffff935c3b80 in duckdb::DatabaseInstance::Initialize(char const*, duckdb::DBConfig*) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x1733b80) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #5 0xffff935c42ac in duckdb::DuckDB::DuckDB(char const*, duckdb::DBConfig*) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x17342ac) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #6 0xffff9348d42c in duckdb_open_internal(duckdb::DBInstanceCacheWrapper*, char const*, _duckdb_database**, _duckdb_config*, char**) (/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/release/src/libduckdb.so+0x15fd42c) (BuildId: 8f45ed76e84b1cc70de5bb93e26789678dd7da92)
    #7 0xaaaab7a410f0 in duckdb_bench::DuckClient::open_and_setup_database::h84eadcb2909f6b03 (/home/myrrc/vortex/target/release/duckdb-bench+0x2210f0) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #8 0xaaaab7a418fc in duckdb_bench::DuckClient::reopen::h51d51997049bda0d (/home/myrrc/vortex/target/release/duckdb-bench+0x2218fc) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #9 0xaaaab7a15688 in vortex_bench::runner::SqlBenchmarkRunner::run_all::hf369fd6622aef0c2 (/home/myrrc/vortex/target/release/duckdb-bench+0x1f5688) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #10 0xaaaab7a39470 in duckdb_bench::main::hf1d36d25774e2f24 (/home/myrrc/vortex/target/release/duckdb-bench+0x219470) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #11 0xaaaab7a17ddc in std::sys::backtrace::__rust_begin_short_backtrace::ha373f3e64f67a470 (/home/myrrc/vortex/target/release/duckdb-bench+0x1f7ddc) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #12 0xaaaab7a17cd8 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h9e658916dfca04cc (/home/myrrc/vortex/target/release/duckdb-bench+0x1f7cd8) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #13 0xaaaab944da38 in std::rt::lang_start_internal::h56a5cede0dc54b7b (/home/myrrc/vortex/target/release/duckdb-bench+0x1c2da38) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #14 0xaaaab7a3ec90 in main (/home/myrrc/vortex/target/release/duckdb-bench+0x21ec90) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
    #15 0xffff91992218  (/lib/aarch64-linux-gnu/libc.so.6+0x22218) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)
    #16 0xffff919922f8 in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x222f8) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)
    #17 0xaaaab7a0752c in _start (/home/myrrc/vortex/target/release/duckdb-bench+0x1e752c) (BuildId: 1c2bec910c9f8b9e6ac23683dd0d8a156ea510be)
```

**Comment by myrrc** [comment]
Sometimes I also get the following assertion in duckdb:

```
thread 'main' panicked at /home/myrrc/vortex/vortex-bench/src/runner.rs:274:29:
Other error: query 1 failed: Other error: Failed to execute query: INTERNAL Error: Failed to cast to type - table filter type mismatch

Stack Trace:

/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Exception::ToJSON(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, duckdb::ExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x3a8) [0xffff992eb878]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Exception::ToJSON(duckdb::ExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x44) [0xffff992ecf04]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Exception::Exception(duckdb::ExceptionType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x28) [0xffff992ecfc8]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::InternalException::InternalException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1c) [0xffff992eff3c]
/home/myrrc/vortex/target/release/duckdb-bench(+0x2c90a0) [0xaaaab6ae90a0]
/home/myrrc/vortex/target/release/duckdb-bench(+0x28b318) [0xaaaab6aab318]
/home/myrrc/vortex/target/release/duckdb-bench(+0x27f180) [0xaaaab6a9f180]
/home/myrrc/vortex/target/release/duckdb-bench(+0x27f7a0) [0xaaaab6a9f7a0]
/home/myrrc/vortex/target/release/duckdb-bench(+0x27fdc8) [0xaaaab6a9fdc8]
/home/myrrc/vortex/target/release/duckdb-bench(+0x2870b8) [0xaaaab6aa70b8]
/home/myrrc/vortex/target/release/duckdb-bench(+0x28bbb4) [0xaaaab6aabbb4]
/home/myrrc/vortex/target/release/duckdb-bench(+0x2cbc00) [0xaaaab6aebc00]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::TableScanGlobalSourceState::TableScanGlobalSourceState(duckdb::ClientContext&, duckdb::PhysicalTableScan const&)+0x2c4) [0xffff995da044]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::PhysicalTableScan::GetGlobalSourceState(duckdb::ClientContext&) const+0x34) [0xffff995d269c]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Pipeline::ResetSource(bool)+0x7c) [0xffff997b9060]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Pipeline::Reset()+0xf4) [0xffff997b9334]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Pipeline::Schedule(duckdb::shared_ptr<duckdb::Event, true>&)+0x18) [0xffff997c9958]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::PipelineEvent::Schedule()+0xa8) [0xffff997c9a30]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Event::CompleteDependency()+0x48) [0xffff997b86c8]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Event::Finish()+0x124) [0xffff997b8544]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::Event::Finish()+0x124) [0xffff997b8544]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::HashJoinFinalizeTask::ExecuteTask(duckdb::TaskExecutionMode)+0x40) [0xffff9957a640]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode)+0x60) [0xffff997bd0c0]
/home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/build/reldebug/src/libduckdb.so(duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*)+0x148) [0xffff997c8668]
/lib/aarch64-linux-gnu/libstdc++.so.6(+0xdb4e0) [0xffff97f6b4e0]
/usr/lib/gcc/aarch64-linux-gnu/14/libasan.so(+0x5e2ac) [0xffff9a9ee2ac]
/lib/aarch64-linux-gnu/libc.so.6(+0x85ef8) [0xffff97c65ef8]
/lib/aarch64-linux-gnu/libc.so.6(+0xede0c) [0xffff97ccde0c]


```

**Comment by myrrc** [comment]
When building with leak sanitizer, I also get the following stack trace:

```
=================================================================
==2627269==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3960 byte(s) in 165 object(s) allocated from:
    #0 0xffff815ea400 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0xaaaac038b654 in custom_labels_new (/home/myrrc/vortex/target/release/duckdb-bench+0xccb654) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #2 0xaaaabf94d6ec in vortex_duckdb::duckdb::table_function::init::init_local_callback::hf5bc7cc787ca038a (/home/myrrc/vortex/target/release/duckdb-bench+0x28d6ec) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #3 0xaaaabf98bf40 in vortex::c_init_local(duckdb::ExecutionContext&, duckdb::TableFunctionInitInput&, duckdb::GlobalTableFunctionState*) (/home/myrrc/vortex/target/release/duckdb-bench+0x2cbf40) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #4 0xffff80153390 in duckdb::TableScanLocalSourceState::TableScanLocalSourceState(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:88
    #5 0xffff80153390 in duckdb::TemplatedUniqueIf<duckdb::TableScanLocalSourceState, true>::templated_unique_single_t duckdb::make_uniq<duckdb::TableScanLocalSourceState, duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&>(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #6 0xffff80153390 in duckdb::PhysicalTableScan::GetLocalSourceState(duckdb::ExecutionContext&, duckdb::GlobalSourceState&) const /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:97
    #7 0xffff8033ec54 in duckdb::PipelineExecutor::PipelineExecutor(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:28
    #8 0xffff80345df8 in duckdb::TemplatedUniqueIf<duckdb::PipelineExecutor, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PipelineExecutor, duckdb::ClientContext&, duckdb::Pipeline&>(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #9 0xffff80345df8 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:35
    #10 0xffff8033c630 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
    #11 0xffff80347b64 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
    #12 0xffff7eaeb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #13 0xffff8156e2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #14 0xffff7e84de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

Indirect leak of 21120 byte(s) in 165 object(s) allocated from:
    #0 0xffff815ea400 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0xaaaac038b35c in careful_push(_custom_labels_ls*, custom_labels_string_t, custom_labels_string_t) (/home/myrrc/vortex/target/release/duckdb-bench+0xccb35c) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #2 0xaaaabf94d77c in vortex_duckdb::duckdb::table_function::init::init_local_callback::hf5bc7cc787ca038a (/home/myrrc/vortex/target/release/duckdb-bench+0x28d77c) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #3 0xaaaabf98bf40 in vortex::c_init_local(duckdb::ExecutionContext&, duckdb::TableFunctionInitInput&, duckdb::GlobalTableFunctionState*) (/home/myrrc/vortex/target/release/duckdb-bench+0x2cbf40) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #4 0xffff80153390 in duckdb::TableScanLocalSourceState::TableScanLocalSourceState(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:88
    #5 0xffff80153390 in duckdb::TemplatedUniqueIf<duckdb::TableScanLocalSourceState, true>::templated_unique_single_t duckdb::make_uniq<duckdb::TableScanLocalSourceState, duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&>(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #6 0xffff80153390 in duckdb::PhysicalTableScan::GetLocalSourceState(duckdb::ExecutionContext&, duckdb::GlobalSourceState&) const /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:97
    #7 0xffff8033ec54 in duckdb::PipelineExecutor::PipelineExecutor(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:28
    #8 0xffff80345df8 in duckdb::TemplatedUniqueIf<duckdb::PipelineExecutor, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PipelineExecutor, duckdb::ClientContext&, duckdb::Pipeline&>(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #9 0xffff80345df8 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:35
    #10 0xffff8033c630 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
    #11 0xffff80347b64 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
    #12 0xffff7eaeb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #13 0xffff8156e2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #14 0xffff7e84de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

Indirect leak of 2610 byte(s) in 270 object(s) allocated from:
    #0 0xffff815ea400 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0xaaaac038b2d8 in careful_push(_custom_labels_ls*, custom_labels_string_t, custom_labels_string_t) (/home/myrrc/vortex/target/release/duckdb-bench+0xccb2d8) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #2 0xaaaac038b568 in custom_labels_careful_set (/home/myrrc/vortex/target/release/duckdb-bench+0xccb568) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #3 0xaaaabf94d77c in vortex_duckdb::duckdb::table_function::init::init_local_callback::hf5bc7cc787ca038a (/home/myrrc/vortex/target/release/duckdb-bench+0x28d77c) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #4 0xaaaabf98bf40 in vortex::c_init_local(duckdb::ExecutionContext&, duckdb::TableFunctionInitInput&, duckdb::GlobalTableFunctionState*) (/home/myrrc/vortex/target/release/duckdb-bench+0x2cbf40) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #5 0xffff80153390 in duckdb::TableScanLocalSourceState::TableScanLocalSourceState(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:88
    #6 0xffff80153390 in duckdb::TemplatedUniqueIf<duckdb::TableScanLocalSourceState, true>::templated_unique_single_t duckdb::make_uniq<duckdb::TableScanLocalSourceState, duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&>(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #7 0xffff80153390 in duckdb::PhysicalTableScan::GetLocalSourceState(duckdb::ExecutionContext&, duckdb::GlobalSourceState&) const /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:97
    #8 0xffff8033ec54 in duckdb::PipelineExecutor::PipelineExecutor(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:28
    #9 0xffff80345df8 in duckdb::TemplatedUniqueIf<duckdb::PipelineExecutor, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PipelineExecutor, duckdb::ClientContext&, duckdb::Pipeline&>(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #10 0xffff80345df8 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:35
    #11 0xffff8033c630 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
    #12 0xffff80347b64 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
    #13 0xffff7eaeb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #14 0xffff8156e2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #15 0xffff7e84de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

Indirect leak of 2430 byte(s) in 270 object(s) allocated from:
    #0 0xffff815ea400 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0xaaaac038b2f4 in careful_push(_custom_labels_ls*, custom_labels_string_t, custom_labels_string_t) (/home/myrrc/vortex/target/release/duckdb-bench+0xccb2f4) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #2 0xaaaac038b568 in custom_labels_careful_set (/home/myrrc/vortex/target/release/duckdb-bench+0xccb568) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #3 0xaaaabf94d77c in vortex_duckdb::duckdb::table_function::init::init_local_callback::hf5bc7cc787ca038a (/home/myrrc/vortex/target/release/duckdb-bench+0x28d77c) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #4 0xaaaabf98bf40 in vortex::c_init_local(duckdb::ExecutionContext&, duckdb::TableFunctionInitInput&, duckdb::GlobalTableFunctionState*) (/home/myrrc/vortex/target/release/duckdb-bench+0x2cbf40) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #5 0xffff80153390 in duckdb::TableScanLocalSourceState::TableScanLocalSourceState(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:88
    #6 0xffff80153390 in duckdb::TemplatedUniqueIf<duckdb::TableScanLocalSourceState, true>::templated_unique_single_t duckdb::make_uniq<duckdb::TableScanLocalSourceState, duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&>(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #7 0xffff80153390 in duckdb::PhysicalTableScan::GetLocalSourceState(duckdb::ExecutionContext&, duckdb::GlobalSourceState&) const /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:97
    #8 0xffff8033ec54 in duckdb::PipelineExecutor::PipelineExecutor(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:28
    #9 0xffff80345df8 in duckdb::TemplatedUniqueIf<duckdb::PipelineExecutor, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PipelineExecutor, duckdb::ClientContext&, duckdb::Pipeline&>(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #10 0xffff80345df8 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:35
    #11 0xffff8033c630 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
    #12 0xffff80347b64 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
    #13 0xffff7eaeb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #14 0xffff8156e2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #15 0xffff7e84de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

Indirect leak of 2175 byte(s) in 225 object(s) allocated from:
    #0 0xffff815ea400 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0xaaaac038b2d8 in careful_push(_custom_labels_ls*, custom_labels_string_t, custom_labels_string_t) (/home/myrrc/vortex/target/release/duckdb-bench+0xccb2d8) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #2 0xaaaabf94d77c in vortex_duckdb::duckdb::table_function::init::init_local_callback::hf5bc7cc787ca038a (/home/myrrc/vortex/target/release/duckdb-bench+0x28d77c) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #3 0xaaaabf98bf40 in vortex::c_init_local(duckdb::ExecutionContext&, duckdb::TableFunctionInitInput&, duckdb::GlobalTableFunctionState*) (/home/myrrc/vortex/target/release/duckdb-bench+0x2cbf40) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #4 0xffff80153390 in duckdb::TableScanLocalSourceState::TableScanLocalSourceState(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:88
    #5 0xffff80153390 in duckdb::TemplatedUniqueIf<duckdb::TableScanLocalSourceState, true>::templated_unique_single_t duckdb::make_uniq<duckdb::TableScanLocalSourceState, duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&>(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #6 0xffff80153390 in duckdb::PhysicalTableScan::GetLocalSourceState(duckdb::ExecutionContext&, duckdb::GlobalSourceState&) const /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:97
    #7 0xffff8033ec54 in duckdb::PipelineExecutor::PipelineExecutor(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:28
    #8 0xffff80345df8 in duckdb::TemplatedUniqueIf<duckdb::PipelineExecutor, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PipelineExecutor, duckdb::ClientContext&, duckdb::Pipeline&>(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #9 0xffff80345df8 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:35
    #10 0xffff8033c630 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
    #11 0xffff80347b64 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
    #12 0xffff7eaeb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #13 0xffff8156e2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #14 0xffff7e84de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

Indirect leak of 2025 byte(s) in 225 object(s) allocated from:
    #0 0xffff815ea400 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0xaaaac038b2f4 in careful_push(_custom_labels_ls*, custom_labels_string_t, custom_labels_string_t) (/home/myrrc/vortex/target/release/duckdb-bench+0xccb2f4) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #2 0xaaaabf94d77c in vortex_duckdb::duckdb::table_function::init::init_local_callback::hf5bc7cc787ca038a (/home/myrrc/vortex/target/release/duckdb-bench+0x28d77c) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #3 0xaaaabf98bf40 in vortex::c_init_local(duckdb::ExecutionContext&, duckdb::TableFunctionInitInput&, duckdb::GlobalTableFunctionState*) (/home/myrrc/vortex/target/release/duckdb-bench+0x2cbf40) (BuildId: b7f3c405e0fb17131300bf90673498aea160497d)
    #4 0xffff80153390 in duckdb::TableScanLocalSourceState::TableScanLocalSourceState(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:88
    #5 0xffff80153390 in duckdb::TemplatedUniqueIf<duckdb::TableScanLocalSourceState, true>::templated_unique_single_t duckdb::make_uniq<duckdb::TableScanLocalSourceState, duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&>(duckdb::ExecutionContext&, duckdb::TableScanGlobalSourceState&, duckdb::PhysicalTableScan const&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #6 0xffff80153390 in duckdb::PhysicalTableScan::GetLocalSourceState(duckdb::ExecutionContext&, duckdb::GlobalSourceState&) const /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/execution/operator/scan/physical_table_scan.cpp:97
    #7 0xffff8033ec54 in duckdb::PipelineExecutor::PipelineExecutor(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline_executor.cpp:28
    #8 0xffff80345df8 in duckdb::TemplatedUniqueIf<duckdb::PipelineExecutor, true>::templated_unique_single_t duckdb::make_uniq<duckdb::PipelineExecutor, duckdb::ClientContext&, duckdb::Pipeline&>(duckdb::ClientContext&, duckdb::Pipeline&) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/include/duckdb/common/helper.hpp:66
    #9 0xffff80345df8 in duckdb::PipelineTask::ExecuteTask(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/pipeline.cpp:35
    #10 0xffff8033c630 in duckdb::ExecutorTask::Execute(duckdb::TaskExecutionMode) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/executor_task.cpp:52
    #11 0xffff80347b64 in duckdb::TaskScheduler::ExecuteForever(std::atomic<bool>*) /home/myrrc/vortex/target/duckdb-source-7f992e5a96662d66134577cf9d8a5bad9053847e/duckdb-7f992e5a96662d66134577cf9d8a5bad9053847e/src/parallel/task_scheduler.cpp:307
    #12 0xffff7eaeb4dc  (/lib/aarch64-linux-gnu/libstdc++.so.6+0xdb4dc) (BuildId: 42f7f063581c06d0944bac51464a918ebb9a54d8)
    #13 0xffff8156e2a8 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #14 0xffff7e84de08  (/lib/aarch64-linux-gnu/libc.so.6+0xede08) (BuildId: 94ff8ab28d4939c80a3e048c763805a37e51edc5)

SUMMARY: AddressSanitizer: 34320 byte(s) leaked in 1320 allocation(s).
```

**Comment by myrrc** [comment]
The segfault can be reproduced without vortex-bench, just running query 5 from tpc-ds given the pre-generated database by `gen-data`:

```
~/duckdb-vortex ~/duckdb-vortex/build/release/duckdb /home/myrrc/vortex/vortex-bench/data/tpcds/1.0/vortex-compact/duckdb.db -f ~/vortex/vortex-bench/tpcds/05.sql 
```

**Comment by myrrc** [comment]
The simplest reproduction is

```
COPY (SELECT 'A' as s_store_id)
TO '/home/myrrc/vortex-hashjoin-segfault/test.vortex' (FORMAT vortex);

SELECT first(sales) AS sales
FROM (
    SELECT s_store_id, 0 as sales FROM
        read_vortex('/home/myrrc/vortex-hashjoin-segfault/test.vortex')
    UNION ALL SELECT s_store_id, 0 as sales FROM
        read_vortex('/home/myrrc/vortex-hashjoin-segfault/test.vortex')
)
GROUP BY s_store_id;

```

**Comment by 0ax1** [comment]
Turns out we need to initialize columns for chunks that are not part of the projection to fix tpc-ds:
```
    /// Export the data into the next chunk.
    ///
    /// Returns `true` if a chunk was exported, `false` if all rows have been exported.
    pub fn export(&mut self, chunk: &mut DataChunkRef) -> VortexResult<bool> {
        if self.remaining == 0 {
            return Ok(false);
        }

        let chunk_len = duckdb_vector_size().min(self.remaining);
        let position = self.array_len - self.remaining;
        self.remaining -= chunk_len;
        chunk.set_len(chunk_len);

        // Write projected Vortex fields into the first N chunk columns.
        for (i, field) in self.fields.iter_mut().enumerate() {
            field.export(position, chunk_len, chunk.get_vector_mut(i), &mut self.ctx)?;
        }

        // The chunk may have more columns than we project into (e.g.
        // zero-projection scans like `COUNT(*)`). NULL-fill remaining
        // columns so DuckDB doesn't read uninitialised memory.
        let n_chunk_cols = chunk.column_count();
        for i in self.fields.len()..n_chunk_cols {
            let vec = chunk.get_vector_mut(i);
            // Converting the vector to a constant null reference marks every
            // row as NULL, which is safe regardless of the vector's logical type.
            unsafe {
                vec.set_validity(&Mask::AllFalse(chunk_len), 0, chunk_len);
            }
        }

        Ok(true)
    }
```

**Comment by robert3005** [comment]
What, why are they even reading unreferenced columns?

**Comment by gatesn** [comment]
Yah this seems weird? We never had to do it in the past. Is this a new 1.5 thing?

**Comment by robert3005** [comment]
I would be curious to know the query and the number of non projected columns. Maybe we do need to fill out a dummy column in case of 0 column projections?

**Comment by 0ax1** [comment]
> Yah this seems weird? We never had to do it in the past. Is this a new 1.5 thing?

Yes, it's a 1.5 thing.

**Comment by 0ax1** [comment]
> I would be curious to know the query and the number of non projected columns. Maybe we do need to fill out a dummy column in case of 0 column projections?

tpcds query 5. gotta check back on the exact counts. Note that the zero-projection scan in the doc is just an example, and not the tpcds 5 case. We should check what the Parquet extension does in DuckDB cc: @myrrc in terms of initializing (or not) unprojected columns.

In my understanding the Parquet ext only writes to projected columns, so the bug is likely on the Vortex side. We're probably missing on writing some of the columns here, which should not just be NULL initialized. 

It's not clear whether the issue popped up bc of bumping DDB to 1.5 or  bumping Vortex to the commit we're using here.

File: vortex-duckdb/build.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ static DUCKDB_VERSION: Lazy<DuckDBVersion> = Lazy::new(|| {
         parse_version(&version)
     } else {
         // The default DuckDB version to use when DUCKDB_VERSION env var is not set.
-        DuckDBVersion::Release("1.4.2".to_owned())
+        DuckDBVersion::Commit("7f992e5a96662d66134577cf9d8a5bad9053847e".to_owned())
```
Comment (0ax1) [inline vortex-duckdb/build.rs]: We have to wait until `1.5.0` is released to merge this and wrap this as `DuckDBVersion::Release`, in order to not build from source by default.

**Review by 0ax1 — CHANGES_REQUESTED** [review]

**Comment by myrrc** [comment]
On the invalid chunk passed, the bug is also reproduced without a GROUP BY:

```
COPY (SELECT 0 AS i) TO '/home/myrrc/duckdb-tpcds-segfault/test.vortex';
SELECT i, 0 AS t FROM '/home/myrrc/duckdb-tpcds-segfault/test.vortex';
SELECT t FROM (SELECT i, 0 AS t FROM '/home/myrrc/duckdb-tpcds-segfault/test.vortex');
```

The origin is unclear, but for the first correctly handled query duckdb tells us in init_global and init_local
that there is 1 column, 1 projection, and then offers a chunk with 1 output column.

On the other query, duckdb tells us there is 1 column but zero projections. Vortex then forms an empty array. However, duckdb returns an output chunk with 1 column, so the semantics of TableFunctionInitInput's column_ids vs. projection_ids is unclear.

Our current match is that chunks columns === projections_ids.size(), but this doesn't hold for second query.

My guess is that optimizer in 1.5 correctly assumes we don't need an output column (because first over a constant is a constant) but then something strange happens in output chunk allocation.

**Comment by myrrc** [comment]
Even simpler reproduction:

```
COPY (SELECT 1) TO '/home/myrrc/duckdb-tpcds-segfault/test.vortex';
SELECT 0 FROM '/home/myrrc/duckdb-tpcds-segfault/test.vortex';
```

My second guess is a bug on our side because duckdb 1.5 does pass a chunk with 1 column (or 2, or columns present in the input file) for a .parquet, so we don't handle these correctly

**Comment by myrrc** [comment]
A non-related but ugly error is on request to write to non-existent file:

```
Executor Error:
Other error: send error send failed because receiver is gone
```

The error message should be more clear

**Comment by myrrc** [comment]
Uninitialized read fixed in #6831

File: vortex-duckdb/build.rs (hunk 1 above)
Comment (myrrc) [reply vortex-duckdb/build.rs]: +1

File: .github/actions/setup-rust/action.yml [hunk 2]
```diff
@@ -50,9 +50,23 @@ runs:
...
-      uses: ./.github/actions/setup-protoc
+      uses: arduino/setup-protoc@v3
+      with:
+        version: "29.3"
+        repo-token: ${{ inputs.repo-token }}
+
+    - name: Install Ninja (for DuckDB build system)
+      uses: seanmiddleditch/gha-setup-ninja@master
+
+    - name: Install Sweep
```
Comment (0ax1) [inline .github/actions/setup-rust/action.yml:64]: Do we need this, and if so why? @gatesn

File: .github/actions/setup-rust/action.yml [hunk 3]
```diff
@@ -50,9 +50,23 @@ runs:
...
+      shell: bash
+      if: ${{ inputs.timestamp == 'true' && github.ref_name == 'develop' }}
+      run: cargo install cargo-sweep
+
+    - name: Timestamp Cache
```
Comment (0ax1) [inline .github/actions/setup-rust/action.yml:69]: Same here

File: vortex-duckdb/cpp/config.cpp [hunk 4]
```diff
@@ -75,8 +75,9 @@ int duckdb_vx_config_has_key(duckdb_config config, const char *key) {
 
         std::string key_str(key);
 
-        // Check if the key exists in set_variables (primary location)
-        if (db_config->options.set_variables.find(key_str) != db_config->options.set_variables.end()) {
+        // Check if the key exists in set_variable_defaults (primary location)
+        if (db_config->options.set_variable_defaults.find(key_str) !=
```
Comment (0ax1) [inline vortex-duckdb/cpp/config.cpp:79]: I know this line existed before but isn't there a `.contains` in 2026 in std library? 🙂

File: vortex-duckdb/build.rs [hunk 5]
```diff
@@ -29,7 +29,7 @@ static DUCKDB_VERSION: Lazy<DuckDBVersion> = Lazy::new(|| {
         parse_version(&version)
     } else {
         // The default DuckDB version to use when DUCKDB_VERSION env var is not set.
-        DuckDBVersion::Release("1.4.2".to_owned())
+        DuckDBVersion::Release("1.5.0".to_owned())
```
Comment (0ax1) [inline vortex-duckdb/build.rs:32]: ✨

File: vortex-duckdb/cpp/config.cpp (hunk 4 above)
Comment (myrrc) [reply vortex-duckdb/cpp/config.cpp:79]: Only from c++20.

File: .github/actions/setup-rust/action.yml (hunk 2 above)
Comment (0ax1) [reply .github/actions/setup-rust/action.yml:64]: Landing this now but let's follow up.

**Review by 0ax1 — APPROVED** [review]
🦆

**Comment by dimitarvdimitrov** [comment]
:shipit:
