### PR TITLE
vortex-metrics v2

### LINKED ISSUE #6078: VortexMetrics Memory Growth: Children Accumulate Indefinitely in Long-Lived Sessions Resulting in OOM
### Discussed in https://github.com/vortex-data/vortex/discussions/5946

<div type='discussions-op-text'>

<sup>Originally posted by **sgrebnov** January 13, 2026</sup>
### Issue Description

`VortexMetrics` accumulates child metrics indefinitely when `VortexSession` is reused across multiple queries, causing memory leaks in production workloads. The `child_with_tags()` method stores strong references to children that are never cleared, leading to memory growth in high-throughput scenarios.

### Expected Behavior

No memory growth when `VortexSession` is re-used across multiple queries

### Actual Behavior

Memory growth when `VortexSession` is re-used across multiple queries

Current behavior:
image

With temporary disabled metrics (memory is higher due to larger data)

image
 

```
pub fn child_with_tags(&self, additional_tags: impl Into<DefaultTags>) -> Self {
        let child = Self::new_with_tags(self.inner.default_tags.merge(&additional_tags.into()));
        // TEMPORARY: Disabled child tracking to prevent memory leak during queries
        // self.inner.children.write().push(child.clone());
        child

```

### Reproduction Steps

**Ownership chain:**
```
VortexSession (Arc<SessionVars>)
  └─> DashMap<TypeId, Box<dyn SessionVar>>
      └─> Box<VortexMetrics> (root)
          └─> Arc<Inner>
              └─> children: RwLock<Vec<VortexMetrics>>  ← NEVER CLEARED
```

```rust
pub fn child_with_tags(&self, tags: impl IntoIterator<Item = (String, String)>) -> Self {
    let child = Self { inner: Arc::new(...) };
    self.inner.children.write().push(child.clone());  // ← Strong reference, never removed
    child
}
```

Each query creates many children (one per partition × files), but they're never cleared:
1. `VortexSession` is designed to be long-lived and reused
2. Children stay alive as long as root `VortexMetrics` exists
3. Root exists as long as any `VortexSession` clone exists

**Questions / Notes**
1. VortexSession to be per-query (new session each time) or long-lived?
2. Root cause has been identified using [heaptrack](https://github.com/KDE/heaptrack), I can share a heaptrack heap profile  if it helps.

### OS Version Information

Ubuntu 24.04

### I acknowledge that:

- [X] I have searched the Vortex repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
- [X] I have checked the "Preview" tab on all text fields to ensure that everything looks right, and have wrapped all configuration and code in code blocks with a group of three backticks (` ``` `) on separate lines.</div>

### PR DESCRIPTION
**Pull request by AdamGS**
Closes https://github.com/vortex-data/vortex/issues/6078.

This PR reworks our metrics crate to simplify it and makes it much harder to make it use unbounded amounts of memory. The implementation is inspired by our current use of `witchcraft-metrics`, the `metrics` crate, DataFusion's metrics and some reading of the OTel spec.

It includes several changes:
1. `VortexMetrics` is replaced by the new `MetricsRegistry` trait, which allows user to integrate metrics to whatever metrics backend they have.
1. Removes metrics from the session, making it the responsibility of the user to wire it correctly between various components.
1. No more hierarchical metrics instances, just wire labels if they exist.
1. Removes the `witchcraft-metrics` dependency. It does many things we don't care about or that are opinionated in a way that I don't think is intuitive or useful for most users. It also makes our external API less dependent on other crates we have no control over.
1. Histograms are now f64 and don't use exponential decay, Timers only speak in `Duration`, and counters are u64s. It also introduces a `Gauge` type which I don't think we actually use and I might just delete.

I've tested it by running our DF benchmarks with `--show-metrics` and that seems to not change, if anyone else has made use of the metrics, I would love to help test and debug them in another context.

### CODE REVIEW

File: wasm-test/.gitignore [hunk 1]
```diff
@@ -0,0 +1 @@
+Cargo.lock
```
Comment (AdamGS) [inline wasm-test/.gitignore:1]: this is just some housekeeping I ran into

File: vortex-metrics/src/lib.rs [hunk 2]
```diff
@@ -6,300 +6,254 @@
...
+    pub fn gauge(self, name: impl Into<Cow<'static, str>>) -> Gauge {
+        self.registry.register_gauge(name.into(), self.labels)
+    }
 }
 
-impl<'a> Iterator for VortexMetricsIter<'a> {
-    type Item = (MetricId, &'a Metric);
+/// Default metrics registry, stores all state in-memory.
+#[derive(Default, Clone)]
+pub struct DefaultMetricsRegistry {
```
Comment (robert3005) [inline vortex-metrics/src/lib.rs:145]: Debating whether we want a RwLock or Mutex here

File: vortex-metrics/src/timer.rs [hunk 3]
```diff
@@ -0,0 +1,90 @@
+// SPDX-License-Identifier: Apache-2.0
+// SPDX-FileCopyrightText: Copyright the Vortex contributors
+
+#![allow(clippy::expect_used)]
+#![allow(clippy::unwrap_in_result)]
```
Comment (robert3005) [inline vortex-metrics/src/timer.rs]: can we remove these?

File: vortex-metrics/src/histogram.rs [hunk 4]
```diff
@@ -0,0 +1,62 @@
+// SPDX-License-Identifier: Apache-2.0
+// SPDX-FileCopyrightText: Copyright the Vortex contributors
+
+#![allow(clippy::expect_used)]
+#![allow(clippy::unwrap_in_result)]
```
Comment (robert3005) [inline vortex-metrics/src/histogram.rs]: remove these

File: vortex-metrics/src/gauge.rs [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+                .is_ok()
+            {
+                break;
+            }
+        }
+    }
+
+    /// Sets the gauge to a specific value.
+    pub fn set(&self, value: f64) {
+        _ = self.0.swap(value.to_bits(), Ordering::AcqRel);
```
Comment (robert3005) [inline vortex-metrics/src/gauge.rs:59]: this is `store` instead

**Review by robert3005 — COMMENTED** [review]
I made couple small comments. The thing that I am not convinced by is double arcing. But I can see how it ends up being necessary

File: vortex-metrics/src/lib.rs (hunk 2 above)
Comment (AdamGS) [reply vortex-metrics/src/lib.rs:145]: I don't think we ever take a `read` lock here unless its after the scan is finished and there's no contention

File: vortex-metrics/src/gauge.rs (hunk 5 above)
Comment (AdamGS) [reply vortex-metrics/src/gauge.rs:59]: my understanding is that using `swap` here makes the memory ordering such that I can do `gauge.get()` and then a `gague.set(..)` and get a consistent ordering.

File: vortex-metrics/src/timer.rs (hunk 3 above)
Comment (AdamGS) [reply vortex-metrics/src/timer.rs]: moved them to the smallest scope possible

File: vortex-metrics/src/gauge.rs (hunk 5 above)
Comment (robert3005) [reply vortex-metrics/src/gauge.rs:59]: Can we leave a comment here? On the surface it makes sense to use store but as you point out swap makes the store wait for a get if there’s one ongoing so you get consistent ordering

**Review by robert3005 — APPROVED** [review]
Feel free to merge it once you add a comment about swap in gauge
