### PR TITLE
Fix RunEndArray filter

### LINKED ISSUE #1368: RunEnd filter produces wrong result

### PR DESCRIPTION
**Pull request by robert3005**
fix #1368

### CODE REVIEW

File: encodings/runend/src/compute.rs [hunk 1]
```diff
@@ -160,6 +160,8 @@ impl FilterFn for RunEndArray {
 // Code adapted from apache arrow-rs https://github.com/apache/arrow-rs/blob/b1f5c250ebb6c1252b4e7c51d15b8e77f4c361fa/arrow-select/src/filter.rs#L425
 fn filter_run_ends<R: NativePType + AddAssign + From<bool> + AsPrimitive<u64>>(
     run_ends: &[R],
```
Comment (robert3005) [inline encodings/runend/src/compute.rs:162]: I tried converting this to `impl Iterator<Item = usize>` but still need to pass the length and would needlesly widen type of the ends.

**Review by lwwmanning — APPROVED** [review]

File: encodings/runend/src/compute.rs (hunk 1 above)
Comment (gatesn) [reply encodings/runend/src/compute.rs:162]: You can do impl Iterator<usize> + ExactSizeIterator

Comment (robert3005) [reply encodings/runend/src/compute.rs:162]: Oooo, let me try that
