### PR TITLE
    duckdb: read from local path, correct err on invalid path

### LINKED ISSUE #6841: Relative paths cause `Neither URL nor path error` because `Url::from_file_path` requires absolute paths
## Description

When using a relative path with the Vortex DuckDB integration, the system returns the error:

`Neither URL nor path ...`

This appears to be caused by the following code:

https://github.com/vortex-data/vortex/blob/5ec8d2f2492753d415a888f67857eac288f7625c/vortex-duckdb/src/multi_file.rs#L44

The implementation uses:

`Url::from_file_path(...)`

However, [Url::from_file_path](https://docs.rs/url/latest/url/struct.Url.html#method.from_file_path) only accepts absolute paths. When a relative path is provided, the function returns `Err`, which leads to the observed error.

## Reproduction

Example usage with a relative path with Vortex 0.61.0:

`SELECT * FROM read_vortex('./data/file.vortex');`

### Result:

`query failed: Binder Error: Other error: Neither URL nor path: 'data/file.vortex'`
Using an absolute path works correctly.

## Root Cause

`Url::from_file_path` requires an absolute filesystem path, but the code does not normalize relative paths before passing them to it.

## Proposed Fix

Convert relative paths to absolute paths before calling Url::from_file_path, for example using:

```rust
let glob_url = Url::parse(glob_url_str).or_else(|_| {
            let path = Path::new(glob_url_str);

           let path = if glob_url_str.contains(['*', '?', '[']) {           
                path.to_path_buf()
            } else {
                std::fs::canonicalize(path)
                    .map_err(|_| vortex_err!("Neither URL nor path: '{}'", glob_url_str))?
            };

            Url::from_file_path(path)
                .map_err(|_| vortex_err!("Neither URL nor path: '{}'", glob_url_str))
        })?;
```

While `std::fs::canonicalize` requires the file to exist, this should not be a problem in this context because the file must exist in order to be read anyway.

Related discussion:
https://github.com/vortex-data/vortex/issues/6599

## Summary

The error occurs because relative paths are passed directly to Url::from_file_path.
Normalizing the path to an absolute path (e.g. via std::fs::canonicalize) should resolve the issue.

### Steps to reproduce

Cannot reproduce it with current DuckDB extension since the bug has not been introduced to it, I have a repo to build Vortex 0.61.0 DuckDB extension.  https://github.com/Lychee-Technology/duckdb-static

### Environment

- Vortex 0.61.0
- Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by myrrc**
Fix two bugs for duckdb integration:
1. Allow relative path reads as in SELECT * FROM 'test.vortex'.
   Threw "neither url not a path" previously.
2. Show correct error when trying to write to a non-existent path.
   Threw "send error cannot send because receiver is gone".

### CODE REVIEW

File: vortex-duckdb/src/copy.rs [hunk 1]
```diff
@@ -130,13 +130,13 @@ impl CopyFunction for VortexCopyFunction {
...
-        let write_task = handle.spawn(async move {
-            // Use DuckDB FS exclusively to match the DuckDB client context configuration.
-            let writer = DuckDbFsWriter::new(ctx, &file_path).map_err(|e| {
-                vortex_err!("Failed to create DuckDB FS writer for {file_path}: {e}")
-            })?;
-            SESSION.write_options().write(writer, array_stream).await
-        });
+
+        // Use DuckDB FS exclusively to match the DuckDB client context configuration.
+        let writer = DuckDbFsWriter::new(ctx, &file_path)
```
Comment (0ax1) [inline vortex-duckdb/src/copy.rs:135]: Do we have a good grip on whether there's a write perf difference between the two? Is it weird to not use DDB FS by default for reading but for writing files?

**Review by 0ax1 — COMMENTED** [review]
2 questions

File: vortex-duckdb/src/copy.rs (hunk 1 above)
Comment (myrrc) [reply vortex-duckdb/src/copy.rs:135]: I didn't examine this one, the only difference I made is move the file open handle from the async task. What has happened before is that although we threw on non-existent file, duckdb still spawned the executor to write to it and failed again.

**Review by 0ax1 — APPROVED** [review]

File: vortex-duckdb/src/copy.rs (hunk 1 above)
Comment (myrrc) [reply vortex-duckdb/src/copy.rs:135]: There is a distinction: we read and write files using duckdb if vortex_filesystem is updated, but we ultimately use duckdb API for opening and closing files.
