### PR TITLE
fix[vortex-array]: fix rebuild_trim_elements overflow

### LINKED ISSUE #6973: vortex-array: rebuild_trim_elements overflows calculating end offset
### What happened?

Seeing this:
```
`offsets + sizes` somehow overflowed:
  Arrow error: Arithmetic overflow: Overflow happened on: 215 + 46
```

It seems to me that instead of/in addition to casting offsets/sizes to the larger width we should consider casting to the the next width? I guess the problem is that the "end" offset is implicit, so it's fine to narrow the start offset of the last range even though the end offset overflows the width.

### Steps to reproduce

I have a vortex file and minimal reproduction test if necessary

### Environment

- Vortex version: 0.59.4 + cherry picks

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asubiotto**
This commit just casts offsets and sizes to u64/i64 before summing for simplicitly. We could make the logic more complicated but not sure it's worth it.

## Summary

Closes: #6973 

## Testing

Regression test added

### CODE REVIEW

**Review by connortsui20 — APPROVED** [review]
I think this is probably fine given we narrow these in the compressor anyways. If for some reason this is bad (it probably isn't) then we can just do the next size up.

**Comment by asubiotto** [comment]
This shouldn't be relevant for the offsets/sizes width. This code path essentially only computes the "end" offset which is cast to a usize below to slice the elements.

File: vortex-array/src/arrays/listview/rebuild.rs [hunk 1]
```diff
@@ -294,21 +296,16 @@ impl ListViewArray {
...
             } else {
-                (
-                    self.offsets().cast(self.sizes().dtype().clone())?,
-                    self.sizes().clone(),
-                )
-            };
+                PType::I64
+            });
+            let offsets = self.offsets().cast(wide_dtype.clone())?;
+            let sizes = self.sizes().cast(wide_dtype)?;
```
Comment (0ax1) [inline vortex-array/src/arrays/listview/rebuild.rs:308]: For types smaller than 64bit this will unconditionally widen => allocate a new buffer + do an element-wise copy.

Comment (asubiotto) [reply vortex-array/src/arrays/listview/rebuild.rs:308]: Yes, this is what I mean by "we could make the logic more complicated". To avoid the unconditional widening we would probably have to attempt the sum and then fall back to widening to the next largest width.

Comment (0ax1) [reply vortex-array/src/arrays/listview/rebuild.rs:308]: Yeah I see, I guess we can act on this in case it shows up in perf profiles.

Comment (asubiotto) [reply vortex-array/src/arrays/listview/rebuild.rs:308]: Definitely! We're always profiling after all 😄
