### PR TITLE
fix: vortex-tui browse with search

### LINKED ISSUE #5223: vx browse is wrong
### Describe the bug

vx browse presents the incorrect type.

### To Reproduce

Download the statpopgen dataset.
```
cargo run --profile release --bin query_bench statpopgen --scale-factor 1
```
Check the type of the GT field:
```
cargo run --bin vx tree bench-vortex/data/statpopgen/10000/vortex-file-compressed/gnomad.genomes.v3.1.2.hgdp_tgp.chr21.vortex | grep GT:
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/vx tree bench-vortex/data/statpopgen/10000/vortex-file-compressed/gnomad.genomes.v3.1.2.hgdp_tgp.chr21.vortex`
    GT: vortex.list(list(u64?)?, len=8192) nbytes=9.18 MB (6.74%)
    PGT: vortex.list(list(i32?)?, len=8192) nbytes=396.71 kB (0.29%)
    GT: vortex.list(list(u64?)?, len=1808) nbytes=1.97 MB (4.32%)
    PGT: vortex.list(list(i32?)?, len=1808) nbytes=317.04 kB (0.69%)
```
Now try to browse to it:
```
cargo run --bin vx browse bench-vortex/data/statpopgen/10000/vortex-file-compressed/gnomad.genomes.v3.1.2.hgdp_tgp.chr21.vortex
```
Type `/` then `GT`. Hit enter.
Image
```
╭────────────────────────────────Vortex Browser────────────────────────────────╮
│ File Layout │ Segments                                                       │
│╭Layout Info─────────────────────────────────────────────────────────────────╮│
││Kind: vortex.stats                                                          ││
││Row Count: 10000                                                            ││
││Schema: bool?                                                               ││
││Children: 2                                                                 ││
││Segment data size: 2.02 kB                                                  ││
││Statistics: max min sum null_count                                          ││
││                                                                            ││
││                                                                            ││
│╰────────────────────────────────────────────────────────────────────────────╯│
│╭Child Layouts───────────────────────────────────────────────────────────────╮│
││data                                                                        ││
││zones                                                                       ││
││                                                                            ││
││                                                                            ││
││                                                                            ││
││                                                                            ││
││                                                                            ││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰────press q to quit |  ← to go up a level | ENTER to select | / to search─────╯

```

### Expected behavior

I expected it to be list(list(u64))

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by a10y**
Fixes #5223 

We ordered the results by score, but we _selected_ the result by its child ordinal in the layout tree.

https://github.com/user-attachments/assets/d325bf7a-1975-4a0d-873c-1623072b0a27

### CODE REVIEW

File: vortex-tui/src/browse/ui/layouts.rs [hunk 1]
```diff
@@ -237,25 +237,22 @@ fn render_children_list(app: &mut AppState, area: Rect, buf: &mut Buffer) {
...
                 .filter_map(|(idx, name)| {
                     matcher
                         .fuzzy_match(&name, &search_filter)
-                        .map(|score| (idx, name.to_string(), score))
+                        .map(|_| (idx, name.to_string()))
                 })
                 .collect_vec();
 
-            // Sort by score (higher is better)
-            scored_matches.sort_by(|a, b| b.2.cmp(&a.2));
```
Comment (a10y) [inline vortex-tui/src/browse/ui/layouts.rs:252]: This was the bug. We store a filter state which is a Vec<bool> indicating which children fuzzy-match the filter.

In the Enter key handler, we select the n-th `true` value in the filter. Before for the `GT` filter, this was selecting `NEGATIVE_TRAIN_SITE` because that was the 1158th child, instead of `GT` which was the first result by score, but was the 1181st child in the layout.

**Review by robert3005 — APPROVED** [review]

**Comment by danking** [comment]
Thank you @a10y !
