### PR TITLE
fix UB and run tests with miri

### LINKED ISSUE #5: Run tests with MIRI
something like `RUST_BACKTRACE=1 MIRIFLAGS="-Zmiri-strict-provenance -Zmiri-symbolic-alignment-check" cargo +nightly miri test`

### PR DESCRIPTION
**Pull request by lwwmanning**
fixes #5

### CODE REVIEW

File: vortex-array/src/array/varbinview/compute.rs [hunk 1]
```diff
@@ -32,9 +32,13 @@ impl ScalarAtFn for VarBinViewArray {
...
-            slice(&self.views(), start * VIEW_SIZE, stop * VIEW_SIZE)?
-                .into_array_data()
-                .into_array(),
+            slice(
+                &self.views(),
+                start * VIEW_SIZE_TO_U64_SIZE,
+                stop * VIEW_SIZE_TO_U64_SIZE,
+            )?
+            .into_array_data()
+            .into_array(),
```
Comment (robert3005) [inline vortex-array/src/array/varbinview/compute.rs]: I think those two lines can be removed completely

File: vortex-array/src/array/varbinview/mod.rs [hunk 2]
```diff
@@ -106,7 +105,9 @@ impl Debug for BinaryView {
     }
 }
 
-pub const VIEW_SIZE: usize = mem::size_of::<BinaryView>();
+// this is a hack; views are 16 bytes with 8-byte alignment
```
Comment (robert3005) [inline vortex-array/src/array/varbinview/mod.rs]: Not sure what kind of hack you're referring to. You can link to c++ code definition to show that this is the same as theirs

**Comment by robert3005** [comment]
The ci error you’re hitting is from not having installed Miri. It’s a component of the rust toolchain

File: vortex-array/src/array/varbinview/builder.rs [hunk 3]
```diff
@@ -1,17 +1,26 @@
...
+use vortex_buffer::allocator::MinAlignmentAllocator;
+use vortex_buffer::Buffer;
+use vortex_dtype::{DType, PType};
 
 use crate::array::primitive::PrimitiveArray;
 use crate::array::varbinview::{BinaryView, Inlined, Ref, VarBinViewArray, VIEW_SIZE};
 use crate::validity::Validity;
 use crate::{ArrayData, IntoArray, IntoArrayData, ToArray};
 
+// BinaryView has 8 byte alignment (because that's what's in the arrow spec), but arrow-rs
```
Comment (gatesn) [inline vortex-array/src/array/varbinview/builder.rs]: Why is it erroneous?

File: vortex-array/src/array/varbinview/mod.rs [hunk 4]
```diff
@@ -195,9 +194,11 @@ impl VarBinViewArray {
         ))
     }
 
+    const BUILDER_BLOCK_SIZE: u32 = 16 * 1024;
```
Comment (gatesn) [inline vortex-array/src/array/varbinview/mod.rs]: Why are we overriding this?

Comment (lwwmanning) [reply vortex-array/src/array/varbinview/mod.rs]: can remove for now, not sure if @robert3005 had a reason

File: vortex-array/src/array/varbinview/mod.rs [hunk 5]
```diff
@@ -31,13 +31,12 @@ mod variants;
 
 #[derive(Clone, Copy, Debug)]
 #[repr(C, align(8))]
-struct Inlined {
+pub struct Inlined {
```
Comment (gatesn) [inline vortex-array/src/array/varbinview/mod.rs:34]: Why have these become pub?

File: vortex-array/src/array/varbinview/mod.rs (hunk 4 above)
Comment (robert3005) [reply vortex-array/src/array/varbinview/mod.rs]: I thought 8k was very conservative and 16k was a better default. Mostly after our interview questions

File: vortex-array/src/array/varbinview/mod.rs (hunk 5 above)
Comment (lwwmanning) [reply vortex-array/src/array/varbinview/mod.rs:34]: so I didn't need to allow dead_code on their constructors (in case we want to use them later). also, the BinaryView union type is public but these aren't, which is... weird?

**Review by gatesn — APPROVED** [review]

File: vortex-array/src/array/varbinview/mod.rs (hunk 4 above)
Comment (lwwmanning) [reply vortex-array/src/array/varbinview/mod.rs]: yeah, arrow has an issue to increase it because 8K is too conservative https://github.com/apache/arrow-rs/issues/6094
