### PR TITLE
fix: listview size & offset ptype mismatch

### LINKED ISSUE #6773: Fuzzing Crash: VortexError in array_ops
### Analysis

**Crash Location**: `vortex-array/src/scalar_fn/fns/binary/mod.rs:109:return_dtype`

**Error Message**:
```
`offsets + sizes` somehow overflowed:
  Other error: incompatible types for arithmetic operation: u32 u16
```

<details>
<summary>Stack Trace</summary>

```
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:689:5
   1: core::panicking::panic_fmt
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/panicking.rs:80:14
   2: panic_display<vortex_error::VortexError>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/panicking.rs:259:5
   3: {closure#1}<alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>, vortex_error::VortexError>
             at ./vortex-error/src/lib.rs:500:9
   4: unwrap_or_else<alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>, vortex_error::VortexError, vortex_error::{impl#11}::vortex_expect::{closure_env#1}<alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>, vortex_error::VortexError>>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/core/src/result.rs:1622:23
   5: vortex_expect<alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>, vortex_error::VortexError>
             at ./vortex-error/src/lib.rs:340:14
   6: rebuild_trim_elements
             at ./vortex-array/src/arrays/listview/rebuild.rs:301:22
   7: rebuild
             at ./vortex-array/src/arrays/listview/rebuild.rs:65:55
   8: compact
             at ./vortex-array/src/canonical.rs:174:23
   9: compress
             at ./vortex-btrblocks/src/canonical_compressor.rs:119:33
  10: compress_array
             at ./fuzz/src/array/mod.rs:534:14
  11: run_fuzz_action
             at ./fuzz/src/array/mod.rs:569:33
  12: __libfuzzer_sys_run
             at ./fuzz/fuzz_targets/array_ops.rs:14:11
  13: rust_fuzzer_test_input
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/src/lib.rs:363:60
  14: {closure#0}
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/src/lib.rs:62:9
  15: do_call<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:581:40
  16: __rust_try
  17: catch_unwind<i32, libfuzzer_sys::test_input_wrap::{closure_env#0}>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panicking.rs:544:19
  18: catch_unwind<libfuzzer_sys::test_input_wrap::{closure_env#0}, i32>
             at /rustc/db3e99bbab28c6ca778b13222becdea54533d908/library/std/src/panic.rs:359:14
  19: test_input_wrap
             at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libfuzzer-sys-0.4.12/src/lib.rs:60:22
   ... (15 more frames truncated)
```
</details>

### Root Cause Analysis

The crash is a VortexError panic in ListViewArray's rebuild_trim_elements (vortex-array/src/arrays/listview/rebuild.rs:301), triggered when computing offsets + sizes during a compact operation. The binary add fails because the offsets and sizes arrays have diverged to different primitive types (u32 and u16) after a sequence of take and filter operations on the ListViewArray, and the arithmetic return_dtype check (vortex-array/src/scalar_fn/fns/binary/mod.rs:109) requires both operands to have identical primitive types. The root cause is that ListViewArray operations (take, filter, compact) can independently widen or cast the offsets array without applying the same transformation to the sizes array, leaving them with mismatched primitive types. The fix should ensure that offsets and sizes are cast to a common primitive type before the binary add in rebuild_trim_elements, or that upstream operations maintain type consistency between the two arrays.

### Summary

- **Target**: `array_ops`
- **Crash File**: `crash-468aa6666d9655f9e0dbe8b93c1fd6cce42062a1`
- **Branch**: develop
- **Commit**: 27542d34d1f9d31d72d41796279ee89c1835a020
- **Crash Artifact**: https://github.com/vortex-data/vortex/actions/runs/22649343772/artifacts/5751461780

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/vortex-data/vortex/actions/runs/22649343772/artifacts/5751461780
   - Extract the zip file

2. Reproduce locally:
```bash
cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-468aa6666d9655f9e0dbe8b93c1fd6cce42062a1 -- -rss_limit_mb=0
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-468aa6666d9655f9e0dbe8b93c1fd6cce42062a1 -- -rss_limit_mb=0
```

---
*Auto-created by fuzzing workflow*

### PR DESCRIPTION
**Pull request by 0ax1**
fixes: https://github.com/vortex-data/vortex/issues/6773

### CODE REVIEW

File: vortex-array/src/arrays/listview/rebuild.rs [hunk 1]
```diff
@@ -293,11 +294,24 @@ impl ListViewArray {
...
+            // Offsets and sizes can have different primitive types.
+            // Cast both to a common type as required by `Operator::Add`.
+            let offsets_ptype = self.offsets().dtype().as_ptype();
+            let sizes_ptype = self.sizes().dtype().as_ptype();
+            let common = DType::Primitive(
+                if offsets_ptype.byte_width() >= sizes_ptype.byte_width() {
+                    offsets_ptype
+                } else {
+                    sizes_ptype
+                },
```
Comment (joseph-isaacs) [inline vortex-array/src/arrays/listview/rebuild.rs]: is max not defined?

**Review by joseph-isaacs — APPROVED** [review]
