### PR TITLE
Avoid some potential stack overflow cases with deep expression trees

### LINKED ISSUE #6296: DuckDB on MacOS with `debug` build, can fail with an "illegal hardware instruction"
### What happened?

Running the tpcds benchmark with the duckdb tool and the default `debug` profile fails with sigill.

### Steps to reproduce

`cargo run --bin duckdb-bench -- tpcds -i1 --formats vortex`

### Environment

- Latest Vortex repo as of this writing cfb89bff690f34e859cb0eba6fd6b75d7e57f210
- Running on MacOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AdamGS**
Closes https://github.com/vortex-data/vortex/issues/6296

1. Collect large `AND`/`OR` expressions into balanced trees instead of a left/right leaning tree, making any recursion into them shorter.
2. Drop `Expression` iteratively instead of the default recursive approach.
3. Following https://github.com/vortex-data/vortex/pull/6251, using encoding ids instead of deep `Array::display_tree` in logs and errors.

### CODE REVIEW

File: vortex-array/src/expr/exprs/binary.rs [hunk 1]
```diff
@@ -474,26 +473,53 @@ pub fn and(lhs: Expression, rhs: Expression) -> Expression {
...
+            next_level.push(combine(left, right));
+        }
+
+        // Handle the remainder (odd element)
+        if let Some(last) = chunks.remainder().first() {
+            next_level.push(last.clone());
+        }
+
+        exprs = next_level;
+    }
```
Comment (joseph-isaacs) [inline vortex-array/src/expr/exprs/binary.rs:519]: can we do this better?

File: vortex-array/src/expr/exprs/binary.rs [hunk 2]
```diff
@@ -474,26 +473,50 @@ pub fn and(lhs: Expression, rhs: Expression) -> Expression {
...
+
+        for target_idx in 0..(exprs.len() / 2) {
+            let item_idx = target_idx * 2;
+            let new = combine(exprs[item_idx].clone(), exprs[item_idx + 1].clone());
+            exprs[target_idx] = new;
+        }
+
+        if !exprs.len().is_multiple_of(2) {
+            exprs[exprs_len / 2] = exprs[exprs.len() - 1].clone();
+            exprs.truncate(exprs_len.div_ceil(2));
```
Comment (joseph-isaacs) [inline vortex-array/src/expr/exprs/binary.rs]: move out of check?

File: vortex-array/src/expr/exprs/binary.rs [hunk 3]
```diff
@@ -474,26 +473,50 @@ pub fn and(lhs: Expression, rhs: Expression) -> Expression {
...
+        let exprs_len = exprs.len();
+
+        for target_idx in 0..(exprs.len() / 2) {
+            let item_idx = target_idx * 2;
+            let new = combine(exprs[item_idx].clone(), exprs[item_idx + 1].clone());
+            exprs[target_idx] = new;
+        }
+
+        if !exprs.len().is_multiple_of(2) {
+            exprs[exprs_len / 2] = exprs[exprs.len() - 1].clone();
```
Comment (joseph-isaacs) [inline vortex-array/src/expr/exprs/binary.rs]: combine here?

File: vortex-array/src/expr/exprs/binary.rs (hunk 1 above)
Comment (gatesn) [reply vortex-array/src/expr/exprs/binary.rs:519]: Classic review comment

File: vortex-array/src/expr/exprs/binary.rs (hunk 3 above)
Comment (AdamGS) [reply vortex-array/src/expr/exprs/binary.rs]: done

File: vortex-array/src/expr/exprs/binary.rs (hunk 2 above)
Comment (AdamGS) [reply vortex-array/src/expr/exprs/binary.rs]: done

File: vortex-array/src/expr/expression.rs [hunk 4]
```diff
@@ -44,9 +44,9 @@ impl Expression {
     /// Create a new expression node from a scalar_fn expression and its children.
     pub fn try_new(
         scalar_fn: ScalarFn,
-        children: impl Into<Arc<[Expression]>>,
+        children: impl IntoIterator<Item = Expression>,
     ) -> VortexResult<Self> {
-        let children: Arc<[Expression]> = children.into();
+        let children = Vec::from_iter(children);
```
Comment (joseph-isaacs) [inline vortex-array/src/expr/expression.rs:49]: take a vec. otherwise a vec need to be collected here? or is there a opt around this?

Comment (AdamGS) [reply vortex-array/src/expr/expression.rs:49]: I just tried to keep the general shape of the API intact

File: vortex-array/src/expr/exprs/binary.rs (hunk 1 above)
Comment (AdamGS) [reply vortex-array/src/expr/exprs/binary.rs:519]: I've personally found it inspiring

**Review by joseph-isaacs — APPROVED** [review]
NIcE
