### PR TITLE
Converting LogicalValidity into Validity requires passing Nullability

### LINKED ISSUE #1740: Transient benchmark patch application failure
This stack trace was found from bench test. The error message is `l_linestatus on_disk_vortex(compressed=true): External error: External error: Arrow error: External error: Failed to canonicalize field l_extendedprice: Can't patch a non-nullable validity with nullable validity`

<details>
<summary>Stack trace</summary>

```
[453](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:454)
Failed to execute select
[454](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:455)
    l_returnflag,
[455](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:456)
    l_linestatus,
[456](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:457)
    sum(l_quantity) as sum_qty,
[457](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:458)
    sum(l_extendedprice) as sum_base_price,
[458](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:459)
    sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
[459](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:460)
    sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
[460](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:461)
    avg(l_quantity) as avg_qty,
[461](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:462)
    avg(l_extendedprice) as avg_price,
[462](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:463)
    avg(l_discount) as avg_disc,
[463](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:464)
    count(*) as count_order
[464](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:465)
from
[465](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:466)
    lineitem
[466](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:467)
where
[467](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:468)
        l_shipdate <= date '1998-09-02'
[468](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:469)
group by
[469](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:470)
    l_returnflag,
[470](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:471)
    l_linestatus
[471](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:472)
order by
[472](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:473)
    l_returnflag,
[473](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:474)
thread 'main' panicked at /home/runner/work/vortex/vortex/bench-vortex/src/tpch/execute.rs:35:14:
[474](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:475)
    l_linestatus on_disk_vortex(compressed=true): External error: External error: Arrow error: External error: Failed to canonicalize field l_extendedprice: Can't patch a non-nullable validity with nullable validity
[475](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:476)
called `Result::unwrap()` on an `Err` value: ()
[476](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:477)
stack backtrace:
[477](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:478)
Backtrace:
[478](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:479)
   0: vortex_array::validity::Validity::patch
[479](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:480)
             at /home/runner/work/vortex/vortex/vortex-array/src/validity.rs:301:17
[480](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:481)
   1: vortex_array::array::primitive::patch::<impl vortex_array::array::primitive::PrimitiveArray>::patch
[481](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:482)
             at /home/runner/work/vortex/vortex/vortex-array/src/array/primitive/patch.rs:19:13
[482](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:483)
   2: vortex_alp::alp::compress::decompress
[483](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:484)
             at /home/runner/work/vortex/vortex/encodings/alp/src/alp/compress.rs:78:9
[484](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:485)
   3: <vortex_alp::alp::array::ALPArray as vortex_array::canonical::IntoCanonical>::into_canonical
[485](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:486)
             at /home/runner/work/vortex/vortex/encodings/alp/src/alp/array.rs:138:9
[486](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:487)
   4: vortex_array::canonical::IntoCanonical::into_arrow
[487](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:488)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:372:9
[488](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:489)
   5: <E as vortex_array::canonical::IntoCanonicalVTable>::into_arrow
[489](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:490)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:399:9
[490](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:491)
   6: <vortex_array::data::ArrayData as vortex_array::canonical::IntoCanonical>::into_arrow
[491](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:492)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:471:9
[492](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:493)
   7: vortex_array::canonical::struct_to_arrow::{{closure}}
[493](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:494)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:201:13
[494](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:495)
   8: core::iter::adapters::map::map_try_fold::{{closure}}
[495](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:496)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/adapters/map.rs:95:28
[496](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:497)
   9: core::iter::traits::iterator::Iterator::try_fold
[497](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:498)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/traits/iterator.rs:2405:21
[498](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:499)
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
[499](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:500)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/adapters/map.rs:121:9
[500](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:501)
  11: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
[501](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:502)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/adapters/mod.rs:191:9
[502](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:503)
  12: core::iter::traits::iterator::Iterator::try_for_each
[503](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:504)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/traits/iterator.rs:2467:9
[504](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:505)
  13: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
[505](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:506)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/adapters/mod.rs:174:14
[506](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:507)
  14: alloc::vec::Vec<T,A>::extend_desugared
[507](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:508)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/alloc/src/vec/mod.rs:3093:35
[508](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:509)
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
[509](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:510)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/alloc/src/vec/spec_extend.rs:17:9
[510](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:511)
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
[511](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:512)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/alloc/src/vec/spec_from_iter_nested.rs:41:9
[512](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:513)
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
[513](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:514)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/alloc/src/vec/spec_from_iter.rs:33:9
[514](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:515)
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
[515](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:516)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/alloc/src/vec/mod.rs:2989:9
[516](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:517)
  19: core::iter::traits::iterator::Iterator::collect
[517](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:518)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/traits/iterator.rs:2000:9
[518](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:519)
  20: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
[519](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:520)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/result.rs:1958:51
[520](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:521)
  21: core::iter::adapters::try_process
[521](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:522)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/adapters/mod.rs:160:17
[522](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:523)
  22: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
[523](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:524)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/result.rs:1958:9
[524](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:525)
  23: core::iter::traits::iterator::Iterator::collect
[525](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:526)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/iter/traits/iterator.rs:2000:9
[526](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:527)
  24: vortex_array::canonical::struct_to_arrow
[527](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:528)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:204:10
[528](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:529)
  25: vortex_array::canonical::Canonical::into_arrow
[529](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:530)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:78:37
[530](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:531)
  26: vortex_array::canonical::IntoCanonical::into_arrow
[531](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:532)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:372:9
[532](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:533)
  27: <E as vortex_array::canonical::IntoCanonicalVTable>::into_arrow
[533](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:534)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:399:9
[534](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:535)
  28: <vortex_array::data::ArrayData as vortex_array::canonical::IntoCanonical>::into_arrow
[535](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:536)
             at /home/runner/work/vortex/vortex/vortex-array/src/canonical.rs:471:9
[536](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:537)
  29: vortex_array::arrow::record_batch::<impl core::convert::TryFrom<vortex_array::array::struct_::StructArray> for arrow_array::record_batch::RecordBatch>::try_from
[537](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:538)
             at /home/runner/work/vortex/vortex/vortex-array/src/arrow/record_batch.rs:52:25
[538](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:539)
  30: vortex_array::arrow::record_batch::<impl core::convert::TryFrom<vortex_array::data::ArrayData> for arrow_array::record_batch::RecordBatch>::try_from
[539](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:540)
             at /home/runner/work/vortex/vortex/vortex-array/src/arrow/record_batch.rs:44:9
[540](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:541)
  31: core::ops::function::FnMut::call_mut
[541](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:542)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/ops/function.rs:166:5
[542](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:543)
  32: <T as futures_util::fns::FnMut1<A>>::call_mut
[543](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:544)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/fns.rs:28:9
[544](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:545)
  33: <futures_util::fns::MapOkFn<F> as futures_util::fns::FnMut1<core::result::Result<T,E>>>::call_mut::{{closure}}
[545](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:546)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/fns.rs:195:21
[546](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:547)
  34: core::result::Result<T,E>::map
[547](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:548)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/result.rs:771:25
[548](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:549)
  35: <futures_util::fns::MapOkFn<F> as futures_util::fns::FnMut1<core::result::Result<T,E>>>::call_mut
[549](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:550)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/fns.rs:195:13
[550](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:551)
  36: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}
[551](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:552)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/stream/stream/map.rs:59:33
[552](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:553)
  37: core::option::Option<T>::map
[553](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:554)
             at /rustc/d6c8169c186ab16a3404cd0d0866674018e8a19e/library/core/src/option.rs:1105:29
[554](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:555)
  38: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
[555](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:556)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/stream/stream/map.rs:59:25
[556](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:557)
  39: <futures_util::stream::try_stream::MapOk<St,F> as futures_core::stream::Stream>::poll_next
[557](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:558)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/lib.rs:97:13
[558](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:559)
  40: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
[559](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:560)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.31/src/stream/stream/map.rs:58:26
[560](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:561)
  41: <S as futures_core::stream::TryStream>::try_poll_next
[561](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:562)
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.31/src/stream.rs:206:9
[562](https://github.com/spiraldb/vortex/actions/runs/12434787539/job/34719224743?pr=1736#step:7:563)
...
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

### PR DESCRIPTION
**Pull request by robert3005**
Without nullability we can't accurately reconstruct Validity as LogicalValidity
losses nonnullable state

fix #1740

### CODE REVIEW

File: vortex-array/src/validity.rs [hunk 1]
```diff
@@ -489,9 +490,12 @@ impl LogicalValidity {
         }
     }
 
-    pub fn into_validity(self) -> Validity {
+    pub fn into_validity(self, nullability: Nullability) -> Validity {
         match self {
```
Comment (gatesn) [inline vortex-array/src/validity.rs:503]: You should panic in here if nullability is NonNullable but logical is AllInvalid

Comment (robert3005) [reply vortex-array/src/validity.rs:503]: here you go. I was hoping we can do a stronger assertion, i.e. NonNullable implies AllValid but looks like in some cases we get an Array of all true :/

File: vortex-array/src/validity.rs [hunk 2]
```diff
@@ -489,9 +490,16 @@ impl LogicalValidity {
         }
     }
 
-    pub fn into_validity(self) -> Validity {
+    pub fn into_validity(self, nullability: Nullability) -> Validity {
+        assert!(
+            nullability == Nullability::Nullable || !matches!(self, Self::AllInvalid(_)),
```
Comment (lwwmanning) [inline vortex-array/src/validity.rs]: this isn't really a tight enough bound. It must be `Nullable` if *any* are invalid, whereas this only covers the *all* invalid case

Comment (robert3005) [reply vortex-array/src/validity.rs]: As I mentioned in the other comment, it's not cheap to write that assertion

Comment (robert3005) [reply vortex-array/src/validity.rs]: Hm, I think there is a bug here. I just pushed a commit to fix it. We were confusing nullability of validity array and nullability of the array itself

Comment (lwwmanning) [reply vortex-array/src/validity.rs]: Eh, I think we should add an invariant that--by construction--LogicalValidity has an Array iff `0 < true_count < len`. Too subtle to reason about otherwise, and it would make this check bound trivial to do cheaply.

In practice, we do this anyway on the path that typically constructs LogicalValidity, but the enum is pub, so it's possible to do otherwise

Comment (robert3005) [reply vortex-array/src/validity.rs]: I added stronger invariant here so now we assert that NonNullable implies AllValid. Making stronger invariant will require a bigger refactor

**Review by lwwmanning — APPROVED** [review]
