### PR TITLE
Exporting struct array to arrow respects vortex nullabilty

### LINKED ISSUE #6326: Fuzzing Crash: MaskedArray execution produces dtype mismatch
### Analysis

**Crash Location**: `vortex-array/src/vtable/dyn_.rs:execute`

**Error Message**:
```
to_canonical should succeed in fuzz test:
  Executed canonical dtype mismatch for Encoding<vortex_array::arrays::masked::vtable::MaskedVTable>
```

**Stack Trace**:
```
   3: execute<vortex_array::arrays::masked::vtable::MaskedVTable>
             at ./vortex-array/src/vtable/dyn_.rs:152:13
   4: execute
             at ./vortex-array/src/executor.rs:195:14
   5: execute<alloc::sync::Arc<dyn vortex_array::array::Array, alloc::alloc::Global>>
             at ./vortex-array/src/executor.rs:40:9
   6: execute
             at ./vortex-array/src/columnar.rs:105:27
   7: execute
             at ./vortex-array/src/canonical.rs:487:18
   8: execute<vortex_array::canonical::Canonical>
             at ./vortex-array/src/executor.rs:40:9
   9: to_canonical<vortex_array::arrays::masked::vtable::MaskedVTable>
             at ./vortex-array/src/array/mod.rs:609:14
```

**Root Cause**: The MaskedArray execute function is producing a canonical array with a dtype that doesn't match the input MaskedArray's dtype. This violates the debug assertion at vortex-array/src/vtable/dyn_.rs:152-156 which verifies that after execution, the result dtype must match the input dtype.

Based on the fuzzer debug output, the sequence is:
1. Start with a ChunkedArray containing VarBinArray and VarBinViewArray chunks (both Utf8, NonNullable)
2. Compress it (still NonNullable)
3. Apply a mask operation, creating a MaskedArray with Nullable dtype wrapping the compressed data
4. Try to convert to canonical - this triggers the crash

The issue appears to be in the dtype transformation during the mask operation or during the execution to canonical form. The MaskedArray's execute implementation (vortex-array/src/arrays/masked/vtable/mod.rs:110-129) calls `mask_validity_canonical` which should preserve dtype, but there seems to be a mismatch happening.

<details>
<summary>Debug Output</summary>

```
FuzzArrayAction {
    array: ChunkedArray {
        dtype: Utf8(
            NonNullable,
        ),
        len: 3,
        chunk_offsets: PrimitiveArray {
            dtype: Primitive(
                U64,
                NonNullable,
            ),
            buffer: BufferHandle(
                Host(
                    Buffer<u8> {
                        length: 24,
                        alignment: Alignment(
                            8,
                        ),
                        as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                    },
                ),
            ),
            validity: NonNullable,
            stats_set: ArrayStats {
                inner: RwLock {
                    data: StatsSet {
                        values: [],
                    },
                },
            },
        },
        chunks: [
            VarBinArray {
                dtype: Utf8(
                    NonNullable,
                ),
                bytes: BufferHandle(
                    Host(
                        Buffer<u8> {
                            length: 0,
                            alignment: Alignment(
                                1,
                            ),
                            as_slice: [],
                        },
                    ),
                ),
                offsets: PrimitiveArray {
                    dtype: Primitive(
                        U32,
                        NonNullable,
                    ),
                    buffer: BufferHandle(
                        Host(
                            Buffer<u8> {
                                length: 4,
                                alignment: Alignment(
                                    4,
                                ),
                                as_slice: [0, 0, 0, 0],
                            },
                        ),
                    ),
                    validity: NonNullable,
                    stats_set: ArrayStats {
                        inner: RwLock {
                            data: StatsSet {
                                values: [
                                    (
                                        IsSorted,
                                        Exact(
                                            ScalarValue(
                                                Bool(
                                                    true,
                                                ),
                                            ),
                                        ),
                                    ),
                                ],
                            },
                        },
                    },
                },
                validity: NonNullable,
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
            VarBinViewArray {
                dtype: Utf8(
                    NonNullable,
                ),
                buffers: [],
                views: BufferHandle(
                    Host(
                        Buffer<u8> {
                            length: 48,
                            alignment: Alignment(
                                16,
                            ),
                            as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                        },
                    ),
                ),
                validity: NonNullable,
                stats_set: ArrayStats {
                    inner: RwLock {
                        data: StatsSet {
                            values: [],
                        },
                    },
                },
            },
        ],
        stats_set: ArrayStats {
            inner: RwLock {
                data: StatsSet {
                    values: [],
                },
            },
        },
    },
    actions: [
        (
            Compress(
                Default,
            ),
            Array(
                ChunkedArray {
                    dtype: Utf8(
                        NonNullable,
                    ),
                    len: 3,
                    chunk_offsets: PrimitiveArray {
                        dtype: Primitive(
                            U64,
                            NonNullable,
                        ),
                        buffer: BufferHandle(
                            Host(
                                Buffer<u8> {
                                    length: 24,
                                    alignment: Alignment(
                                        8,
                                    ),
                                    as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                                },
                            ),
                        ),
                        validity: NonNullable,
                        stats_set: ArrayStats {
                            inner: RwLock {
                                data: StatsSet {
                                    values: [],
                                },
                            },
                        },
                    },
                    chunks: [
                        VarBinArray {
                            dtype: Utf8(
                                NonNullable,
                            ),
                            bytes: BufferHandle(
                                Host(
                                    Buffer<u8> {
                                        length: 0,
                                        alignment: Alignment(
                                            1,
                                        ),
                                        as_slice: [],
                                    },
                                ),
                            ),
                            offsets: PrimitiveArray {
                                dtype: Primitive(
                                    U32,
                                    NonNullable,
                                ),
                                buffer: BufferHandle(
                                    Host(
                                        Buffer<u8> {
                                            length: 4,
                                            alignment: Alignment(
                                                4,
                                            ),
                                            as_slice: [0, 0, 0, 0],
                                        },
                                    ),
                                ),
                                validity: NonNullable,
                                stats_set: ArrayStats {
                                    inner: RwLock {
                                        data: StatsSet {
                                            values: [
                                                (
                                                    IsSorted,
                                                    Exact(
                                                        ScalarValue(
                                                            Bool(
                                                                true,
                                                            ),
                                                        ),
                                                    ),
                                                ),
                                            ],
                                        },
                                    },
                                },
                            },
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [],
                                    },
                                },
                            },
                        },
                        VarBinViewArray {
                            dtype: Utf8(
                                NonNullable,
                            ),
                            buffers: [],
                            views: BufferHandle(
                                Host(
                                    Buffer<u8> {
                                        length: 48,
                                        alignment: Alignment(
                                            16,
                                        ),
                                        as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                                    },
                                ),
                            ),
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [],
                                    },
                                },
                            },
                        },
                    ],
                    stats_set: ArrayStats {
                        inner: RwLock {
                            data: StatsSet {
                                values: [],
                            },
                        },
                    },
                },
            ),
        ),
        (
            Mask(
                Values(
                    MaskValues {
                        buffer: BitBuffer {
                            buffer: Buffer<u8> {
                                length: 1,
                                alignment: Alignment(
                                    1,
                                ),
                                as_slice: [4],
                            },
                            offset: 0,
                            len: 3,
                        },
                        indices: OnceLock(
                            <uninit>,
                        ),
                        slices: OnceLock(
                            <uninit>,
                        ),
                        true_count: 1,
                        density: 0.3333333333333333,
                    },
                ),
            ),
            Array(
                VarBinViewArray {
                    dtype: Utf8(
                        Nullable,
                    ),
                    buffers: [],
                    views: BufferHandle(
                        Host(
                            Buffer<u8> {
                                length: 48,
                                alignment: Alignment(
                                    16,
                                ),
                                as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                            },
                        ),
                    ),
                    validity: Array(
                        BoolArray {
                            dtype: Bool(
                                NonNullable,
                            ),
                            bits: BufferHandle(
                                Host(
                                    Buffer<u8> {
                                        length: 1,
                                        alignment: Alignment(
                                            1,
                                        ),
                                        as_slice: [251],
                                    },
                                ),
                            ),
                            offset: 0,
                            len: 3,
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [],
                                    },
                                },
                            },
                        },
                    ),
                    stats_set: ArrayStats {
                        inner: RwLock {
                            data: StatsSet {
                                values: [],
                            },
                        },
                    },
                },
            ),
        ),
        (
            ScalarAt(
                [
                    0,
                ],
            ),
            ScalarVec(
                [
                    Scalar {
                        dtype: Utf8(
                            Nullable,
                        ),
                        value: ScalarValue(
                            BufferString(
                                BufferString {
                                    string: "",
                                },
                            ),
                        ),
                    },
                ],
            ),
        ),
        (
            Compress(
                Compact,
            ),
            Array(
                VarBinViewArray {
                    dtype: Utf8(
                        Nullable,
                    ),
                    buffers: [],
                    views: BufferHandle(
                        Host(
                            Buffer<u8> {
                                length: 48,
                                alignment: Alignment(
                                    16,
                                ),
                                as_slice: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...],
                            },
                        ),
                    ),
                    validity: Array(
                        BoolArray {
                            dtype: Bool(
                                NonNullable,
                            ),
                            bits: BufferHandle(
                                Host(
                                    Buffer<u8> {
                                        length: 1,
                                        alignment: Alignment(
                                            1,
                                        ),
                                        as_slice: [251],
                                    },
                                ),
                            ),
                            offset: 0,
                            len: 3,
                            validity: NonNullable,
                            stats_set: ArrayStats {
                                inner: RwLock {
                                    data: StatsSet {
                                        values: [],
                                    },
                                },
                            },
                        },
                    ),
                    stats_set: ArrayStats {
                        inner: RwLock {
                            data: StatsSet {
                                values: [],
                            },
                        },
                    },
                },
            ),
        ),
    ],
}
```
</details>

### Summary

- **Target**: `array_ops`
- **Crash File**: `crash-caec2ffa2e36c2363c142c55a4176bef24a9ef3c`
- **Branch**: develop
- **Commit**: db7811a
- **Crash Artifact**: https://github.com/spiraldb/vortex/actions/runs//artifacts/

### Reproduction

1. Download the crash artifact:
   - **Direct download**: https://github.com/spiraldb/vortex/actions/runs//artifacts/
   - Or find `fuzz-artifacts` at: https://github.com/spiraldb/vortex/actions/runs/
   - Extract the zip file

2. Reproduce locally:
```bash
# The artifact contains array_ops/crash-caec2ffa2e36c2363c142c55a4176bef24a9ef3c
cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-caec2ffa2e36c2363c142c55a4176bef24a9ef3c -- -rss_limit_mb=0
```

3. Get full backtrace:
```bash
RUST_BACKTRACE=full cargo +nightly fuzz run -D --sanitizer=none array_ops array_ops/crash-caec2ffa2e36c2363c142c55a4176bef24a9ef3c -- -rss_limit_mb=0
```

---
*Auto-created by fuzzing workflow with Claude analysis*

### PR DESCRIPTION
**Pull request by robert3005**
fix #6326

Signed-off-by: Robert Kruszewski <github@robertk.io>

### CODE REVIEW

File: fuzz/src/array/mod.rs [hunk 1]
```diff
@@ -370,21 +370,19 @@ impl<'a> Arbitrary<'a> for FuzzArrayAction {
...
                             .to_canonical()
                             .vortex_expect("to_canonical should succeed in fuzz test"),
-                        &Mask::from_iter(mask.iter().copied()),
+                        &mask,
                     )
                     .vortex_expect("mask_canonical_array should succeed in fuzz test");
                     // Update current_array to the result for chaining
                     current_array = expected_result.clone();
-                    (
-                        Action::Mask(Mask::from_iter(mask)),
```
Comment (joseph-isaacs) [inline fuzz/src/array/mod.rs:385]: keep these as seperate they share cached state

File: vortex-array/src/compute/mask.rs [hunk 2]
```diff
@@ -115,12 +115,13 @@ impl ComputeFnVTable for MaskFn {
...
 
-        if matches!(mask, Mask::AllFalse(_)) {
+        let mask_true_count = mask.true_count();
+        if mask_true_count == 0 {
             // Fast-path for empty mask
             return Ok(cast(array, &array.dtype().as_nullable())?.into());
         }
 
-        if matches!(mask, Mask::AllTrue(_)) {
+        if mask_true_count == mask.len() {
```
Comment (joseph-isaacs) [inline vortex-array/src/compute/mask.rs:124]: this is a east and common mistake to make are you sure it exists?

**Review by joseph-isaacs — COMMENTED** [review]
which one is the actual fix? can we have a test?

File: vortex-array/src/compute/mask.rs (hunk 2 above)
Comment (a10y) [reply vortex-array/src/compute/mask.rs:124]: why was this necessary?

Comment (a10y) [reply vortex-array/src/compute/mask.rs:124]: the nice thing about the old version was that it avoided scanning the indices for the fast paths

**Review by a10y — APPROVED** [review]
