### PR TITLE
dict layout writer to allow empty input stream

### LINKED ISSUE #3600: DictLayout doesn't handle empty input streams
I think this happens if you try to write an all null array (courtesy of the fuzzer). We fail in https://github.com/vortex-data/vortex/blob/8c1700afa25dd23daaae8a695576b15d02d3f782/vortex-layout/src/layouts/dict/writer/mod.rs#L422-L424 with the stream being empty

### PR DESCRIPTION
**Pull request by onursatici**
Fix https://github.com/vortex-data/vortex/issues/3600

### CODE REVIEW

File: vortex-layout/src/layouts/dict/writer/mod.rs [hunk 1]
```diff
@@ -99,8 +99,8 @@ impl LayoutStrategy for DictStrategy {
             })
             .await?;
             let stream = SequentialStreamAdapter::new(dtype.clone(), stream).sendable();
-            if !is_dict_encoding? {
-                // first chunk did not compress to dict, skip dict layout
+            if !is_dict_encoding.unwrap_or(false) {
```
Comment (robert3005) [inline vortex-layout/src/layouts/dict/writer/mod.rs]: I think we are swallowing errors here

Comment (onursatici) [reply vortex-layout/src/layouts/dict/writer/mod.rs]: yea you are right

Comment (onursatici) [reply vortex-layout/src/layouts/dict/writer/mod.rs]: looks better now I think, should have done it like this the first time. Only if Stream::peekable was easier to use here

**Review by robert3005 — APPROVED** [review]

**Comment by robert3005** [comment]
I think you have some tests failures because layout trees changed
