### PR TITLE
fix: Pruning expressions check NanCount where appropriate

### LINKED ISSUE #3958: Pushdown compare with NaN broken
We implement our `compare` binary comparison operation using the arrow_ord kernels. This uses the f32/f64 `total_cmp`, which includes NaN as >= all positive normal numbers.

This causes inconsistent behavior when pushing down a comparison operation against NaN to a file column that contains NaN.

Directly evaluating the following comparison results in `[false, false, true, true]`:

```
PrimitiveArray([1.0, 2.0, NaN, NaN]) >= f32::NAN
```

However, this is not the case when the filter is pushed down into a scan, because our min/max stats do not consider NaN. The pruning expression that gets pushed down is

```
$.max < f32::NAN --> 2.0 < f32::NAN = true
```

which causes the whole thing to get pruned and the result becomes `[false, false, false, false]`

https://github.com/vortex-data/vortex/blob/bba0e63e3e9bb271816edde5ed3fcc0e1924db5b/vortex-array/src/arrays/primitive/compute/min_max.rs#L43-L48

We need to either

1. Make the stats contain NaN, and preserve the `total_cmp` ordering in pushdown
2. Have a fallback `compare` kernel for float arrays with NaNCount > 0 that masks out the NaNs to false

### PR DESCRIPTION
**Pull request by a10y**
Fixes #3958 

NanCount stat is checked in the pruning evaluation if it is present (i.e. for float columns and literals)

- [x] Verify fixes fuzz failure
- [x] Add unit tests

Signed-off-by: Andrew Duffy <andrew@a10y.dev>

### CODE REVIEW

File: vortex-layout/src/layouts/zoned/reader.rs [hunk 1]
```diff
@@ -105,12 +113,35 @@ impl ZonedReader {
...
+                                Scalar::primitive(0u64, Nullability::NonNullable),
+                                nzones,
+                            )
+                            .into_array(),
+                        )?;
+                    }
+
                     // SAFETY: This is only fine to call because we perform validation above
-                    Ok(ZoneMap::unchecked_new(zones_array, present_stats))
+                    Ok(ZoneMap::new_unchecked(zones_array, present_stats))
```
Comment (a10y) [inline vortex-layout/src/layouts/zoned/reader.rs:129]: make the naming more idiomatic

File: vortex-array/src/arrays/struct_/mod.rs [hunk 2]
```diff
@@ -240,7 +241,7 @@ impl StructArray {
 
     /// Removes and returns a column from the struct array by name.
     /// If the column does not exist, returns `None`.
-    pub fn remove_column(&mut self, name: impl Into<FieldName>) -> Option<ArrayRef> {
+    pub fn drop(&mut self, name: impl Into<FieldName>) -> Option<ArrayRef> {
```
Comment (a10y) [inline vortex-array/src/arrays/struct_/mod.rs]: again, more idiomatic naming

Comment (a10y) [reply vortex-array/src/arrays/struct_/mod.rs]: Actually, this probably conflicts with the Drop trait impl...maybe `drop_column` ?

File: vortex-expr/src/pruning/pruning_expr.rs [hunk 3]
```diff
@@ -60,41 +70,29 @@ pub fn field_path_stat_field_name(field_path: &FieldPath, stat: Stat) -> FieldNa
...
-    let expr = expr.stat_falsification(&mut catalog)?;
-
-    // TODO(joe): filter access by used exprs
-    let mut relation: Relation<FieldPath, Stat> = Relation::new();
-    for ((field_path, stat), _) in catalog.usage.into_iter() {
-        relation.insert(field_path, stat)
-    }
-
-    Some((expr, relation))
-}
```
Comment (a10y) [inline vortex-expr/src/pruning/pruning_expr.rs:78]: this was only being used in the tests below, I don't think there's a use for a version of this function that doesn't check for stat availability so I just removed this

File: vortex-datafusion/src/persistent/source.rs [hunk 4]
```diff
@@ -176,9 +175,6 @@ impl FileSource for VortexSource {
             DisplayFormatType::Default | DisplayFormatType::Verbose => {
                 if let Some(predicate) = &self.predicate {
                     write!(f, ", predicate={predicate}")?;
-                    if let Some((pruning_predicate, _)) = pruning_expr(predicate) {
```
Comment (robert3005) [inline vortex-datafusion/src/persistent/source.rs:179]: brutal... if you get rid of this branch then all the cases are the same

File: vortex-array/src/arrays/struct_/mod.rs [hunk 5]
```diff
@@ -261,6 +262,29 @@ impl StructArray {
...
+        name: impl Into<FieldName>,
+        array: ArrayRef,
+    ) -> VortexResult<Self> {
+        let name = name.into();
+        let Some(struct_dtype) = self.dtype.as_struct() else {
+            unreachable!(
+                "struct arrays must have be a DType::Struct, this is likely an internal bug."
+            )
+        };
+
```
Comment (robert3005) [inline vortex-array/src/arrays/struct_/mod.rs]: `self.struct_fields()`

File: vortex-array/src/arrays/struct_/mod.rs [hunk 6]
```diff
@@ -261,6 +262,29 @@ impl StructArray {
 
         Some(field)
     }
+
+    /// Create a new StructArray by appending a new column onto the existing array.
+    pub fn with_column(
+        &mut self,
```
Comment (robert3005) [inline vortex-array/src/arrays/struct_/mod.rs]: why is this mut if you make a copy?

File: vortex-array/src/arrays/struct_/mod.rs (hunk 5 above)
Comment (a10y) [reply vortex-array/src/arrays/struct_/mod.rs]: nice, I just copied this from `remove_column` a few lines up, I'll switch them both over

File: vortex-array/src/arrays/struct_/mod.rs (hunk 6 above)
Comment (a10y) [reply vortex-array/src/arrays/struct_/mod.rs]: holdover, fixed now

File: vortex-datafusion/src/persistent/source.rs (hunk 4 above)
Comment (a10y) [reply vortex-datafusion/src/persistent/source.rs:179]: merged them

Comment (robert3005) [reply vortex-datafusion/src/persistent/source.rs:179]: I guess for pretty printing cases you want to not print `, ` tree case

Comment (a10y) [reply vortex-datafusion/src/persistent/source.rs:179]: ah yea, it looks like the TreeRender formatting is slightly different, needs `=` separated key-values pairs. I'll fix this

File: vortex-expr/src/exprs/binary.rs [hunk 7]
```diff
@@ -138,6 +138,20 @@ impl Display for BinaryExpr {
 
 impl AnalysisExpr for BinaryExpr {
```
Comment (joseph-isaacs) [inline vortex-expr/src/exprs/binary.rs:139]: We can add an example transformed predicate?

Comment (a10y) [reply vortex-expr/src/exprs/binary.rs:139]: There isn't really any documentation in this file, I've updated the pruning_expr unit tests. I agree could be some more documentation here

File: vortex-expr/src/exprs/binary.rs [hunk 8]
```diff
@@ -138,6 +138,20 @@ impl Display for BinaryExpr {
...
+            catalog: &mut dyn StatsCatalog,
+        ) -> Option<ExprRef> {
+            lhs.nan_count(catalog)
+                .into_iter()
+                .chain(rhs.nan_count(catalog))
+                .map(|nans| eq(nans, lit(0u64)))
+                .reduce(and)
+        }
+
         match self.operator {
```
Comment (joseph-isaacs) [inline vortex-expr/src/exprs/binary.rs:175]: can we apply the non nan check outside the match?

File: vortex-expr/src/exprs/get_item.rs
Comment (joseph-isaacs) [inline vortex-expr/src/exprs/get_item.rs:1]: we need to add nan_count to `extract_relevant_file_stats_as_struct_row`

File: vortex-expr/src/exprs/literal.rs [hunk 9]
```diff
@@ -112,6 +112,28 @@ impl AnalysisExpr for LiteralExpr {
...
+        match_each_float_ptype!(value.ptype(), |T| {
+            match value.typed_value::<T>() {
+                None => Some(lit(0u64)),
+                Some(value) => {
+                    if value.is_nan() {
+                        Some(lit(1u64))
+                    } else {
+                        Some(lit(0u64))
+                    }
+                }
```
Comment (joseph-isaacs) [inline vortex-expr/src/exprs/literal.rs]: Some(value) 
```suggestion
                Some(value) if value.is_nan() => Some(lit(1u64))
                 _ => Some(lit(0u64))
                }
```

File: vortex-expr/src/exprs/binary.rs (hunk 7 above)
Comment (joseph-isaacs) [reply vortex-expr/src/exprs/binary.rs:139]: Even this example would really help
`a > 2.0 ==> (a < 2.0) and a_nan_count == 0`

File: vortex-expr/src/exprs/binary.rs (hunk 8 above)
Comment (a10y) [reply vortex-expr/src/exprs/binary.rs:175]: Not easily no, b/c the AND/OR/numeric operators don't apply and they're all grouped together in the enum

File: vortex-expr/src/exprs/get_item.rs
Comment (a10y) [reply vortex-expr/src/exprs/get_item.rs:1]: done (i think)

File: vortex-expr/src/exprs/binary.rs (hunk 7 above)
Comment (a10y) [reply vortex-expr/src/exprs/binary.rs:139]: I added a comment in the function body, let me know if you think we need more

File: vortex-expr/src/exprs/binary.rs [hunk 10]
```diff
@@ -157,12 +190,55 @@ impl AnalysisExpr for BinaryExpr {
...
+
+                if let Some(nan_check) = make_nan_predicate(self.lhs(), self.rhs(), catalog) {
+                    Some(and(nan_check, min_max_check))
+                } else {
+                    Some(min_max_check)
+                }
+            }
+            Operator::Gte => {
+                // NaN is not captured by the min/max stat, so we must check NaNCount before pruning
+                let min_max_check = lt(self.lhs.max(catalog)?, self.rhs.min(catalog)?);
```
Comment (a10y) [inline vortex-expr/src/exprs/binary.rs:214]: This PR also cheekily fixes broken pruning predicate logic, this was `lt_eq` before 🫢

**Review by robert3005 — APPROVED** [review]

File: vortex-expr/src/exprs/binary.rs (hunk 8 above)
Comment (joseph-isaacs) [reply vortex-expr/src/exprs/binary.rs:175]: I dont see how?

Comment (joseph-isaacs) [reply vortex-expr/src/exprs/binary.rs:175]: its always the same chain and reduce and

File: vortex-expr/src/exprs/literal.rs (hunk 9 above)
Comment (joseph-isaacs) [reply vortex-expr/src/exprs/literal.rs]: is this is no?

**Review by joseph-isaacs — CHANGES_REQUESTED** [review]
Can we try and simplify the logic here

File: vortex-expr/src/exprs/literal.rs (hunk 9 above)
Comment (a10y) [reply vortex-expr/src/exprs/literal.rs]: no i incorporated this change, I just did it by hand to get formatting right

File: vortex-expr/src/exprs/binary.rs (hunk 8 above)
Comment (a10y) [reply vortex-expr/src/exprs/binary.rs:175]: I don't know how to do this without accessing the catalog spuriously. And the catalog is stateful, so I only want to access it in branches where the NanCount stat is actually needed.

Comment (joseph-isaacs) [reply vortex-expr/src/exprs/binary.rs:175]: I see, maybe make a lambda what make and expr and applies the and (nan) only for these.

On the other handle the stats catalogue was designed to allow for checking if the expr in actually in the final prune expr

File: vortex-expr/src/exprs/binary.rs [hunk 11]
```diff
@@ -138,6 +138,20 @@ impl Display for BinaryExpr {
...
+            lhs: &ExprRef,
+            rhs: &ExprRef,
+            catalog: &mut dyn StatsCatalog,
+        ) -> Option<ExprRef> {
+            lhs.nan_count(catalog)
+                .into_iter()
+                .chain(rhs.nan_count(catalog))
+                .map(|nans| eq(nans, lit(0u64)))
+                .reduce(and)
+        }
```
Comment (joseph-isaacs) [inline vortex-expr/src/exprs/binary.rs]: Why is this different to the other nan checks

Comment (a10y) [reply vortex-expr/src/exprs/binary.rs]: i think you're looking at an old revision, can you refresh? these line numbers are different now

File: vortex-expr/src/exprs/binary.rs [hunk 12]
```diff
@@ -148,7 +162,14 @@ impl AnalysisExpr for BinaryExpr {
...
                 let right = min_rhs.zip(max_lhs).map(|(a, b)| gt(a, b));
-                left.into_iter().chain(right).reduce(or)
+
+                let min_max_check = left.into_iter().chain(right).reduce(or);
+
+                // NaN is not captured by the min/max stat, so we must check NaNCount before pruning
+                make_nan_predicate(self.lhs(), self.rhs(), catalog)
+                    .into_iter()
+                    .chain(min_max_check)
+                    .reduce(and)
```
Comment (joseph-isaacs) [inline vortex-expr/src/exprs/binary.rs]: Here

File: vortex-expr/src/exprs/binary.rs (hunk 11 above)
Comment (joseph-isaacs) [reply vortex-expr/src/exprs/binary.rs]: I meant the one below (169)

File: vortex-expr/src/exprs/binary.rs (hunk 8 above)
Comment (a10y) [reply vortex-expr/src/exprs/binary.rs:175]: that's a good idea let me try that

Comment (joseph-isaacs) [reply vortex-expr/src/exprs/binary.rs:175]: https://github.com/vortex-data/vortex/blob/30fd768f7d60a9125a2bf122f0f0630d55126f48/vortex-expr/src/pruning/pruning_expr.rs#L71 here we can check if the expr in in the final pruning expr and drop other stats loads

File: vortex-expr/src/pruning/pruning_expr.rs [hunk 13]
```diff
@@ -284,14 +297,14 @@ mod tests {
         assert_eq!(&converted, &(expected_expr));
     }
 
-    #[test]
-    pub fn pruning_lt_column() {
+    #[rstest::rstest]
```
Comment (robert3005) [inline vortex-expr/src/pruning/pruning_expr.rs]:
```suggestion
    #[rstest]
```

File: vortex-expr/src/exprs/binary.rs (hunk 8 above)
Comment (a10y) [reply vortex-expr/src/exprs/binary.rs:175]: i just centralized the wrapping logic in one place, it was easier

**Review by joseph-isaacs — APPROVED** [review]
thanks
